app-editors/visual-studio-code: New Ebuild
gentoo/gentoo pull request #11674
Opened 2019-04-14 03:10 UTC by oniGino

Bug: https://bugs.gentoo.org/675742

* New Ebuild for Visual Studio Code (Pre Built Binary from Microsoft)

Signed-off-by: Gino McCarty <onigino@protonmail.com>

2019-09-01 00:12 UTC, Gaelan commented
The license here is wrong—the VS Code source is MIT, but the [official binaries have a EULA](https://code.visualstudio.com/license).

2019-09-10 04:58 UTC, oniGino commented
> The license here is wrong—the VS Code source is MIT, but the [official binaries have a EULA](https://code.visualstudio.com/license).

OK, inserted a text version of the license

2020-04-20 02:28 UTC, oniGino commented
any way to get this reviewed please? its been open forever

2020-07-29 02:19 UTC, rossbridger commented
I think the package name should be _visual-studio-code-bin_ since it's a binary build.

2020-08-01 20:10 UTC, oniGino commented
> I think the package name should be _visual-studio-code-bin_ since it's a binary build.

plenty of precedence for this, one popular example www-client/google-chrome
but if maintainers wants it changed I can

2020-08-02 00:59 UTC, rossbridger commented
Since building vscode directly from upstream source is also possible, there should be a name difference in case new package for building from source will also be available in the future, like dev-java/openjdk and dev-java/openjdk-bin.

2020-08-02 00:59 UTC, rossbridger commented
ping

2020-08-02 01:02 UTC, Gaelan commented
@rossbridger it's more of a chrome/chromium situation: There's "Visual Studio Code" (analogous to Google Chrome), which is a binaries distributed by MS under a proprietary license with some extra features, and the awkwardly-named "Code — OSS" (analogous to Chromium) which is what you get if you compile the open source project. So you can't compile "Visual Studio Code" from source per se

2020-08-02 01:13 UTC, rossbridger commented
@Gaelan I guess we can possibly rename the source build to something like visual-studio-code-oss or something, but it might still get confusing given Microsoft actually named its source respository [microsoft/vscode](https://github.com/microsoft/vscode), not vscode-oss or something else.

2020-08-03 09:30 UTC, oniGino commented
ok, i renamed it and bumped to latest release 1.47, thanks for the feedback.

2020-08-04 11:10 UTC, rossbridger commented
ping @gentoo/proxy-maint

2020-08-24 08:50 UTC, Azulinho commented on app-editors/visual-studio-code-bin/visual-studio-code-bin-1.47.3.ebuild
> +	fperms +x "/opt/${PN}/code"
this should be:

```fperms +x "/opt/${PN}/bin/code"```

2020-08-24 08:54 UTC, Azulinho commented on app-editors/visual-studio-code-bin/visual-studio-code-bin-1.47.3.ebuild
> +	dosym "../../opt/${PN}/code" "usr/bin/${PN}"
this should be

```dosym "../../opt/${PN}/bin/code" "usr/bin/${PN}"```

2020-09-15 06:29 UTC, thesamesam requested changes

2020-09-15 06:29 UTC, thesamesam commented on app-editors/visual-studio-code-bin/visual-studio-code-bin-1.47.3.ebuild
> +SRC_URI="https://update.code.visualstudio.com/${PV}/linux-x64/stable -> ${P}.tar.gz"
```suggestion
SRC_URI="amd64? ( https://update.code.visualstudio.com/${PV}/linux-x64/stable -> ${P}.tar.gz )"
```

2020-09-15 06:29 UTC, thesamesam commented on app-editors/visual-studio-code-bin/visual-studio-code-bin-1.47.3.ebuild
> +KEYWORDS="~amd64"
```suggestion
KEYWORDS="-* ~amd64"
```
because it's a binary and can't work [elsewhere](https://devmanual.gentoo.org/keywording/index.html)

2020-09-15 06:29 UTC, thesamesam commented on app-editors/visual-studio-code-bin/visual-studio-code-bin-1.47.3.ebuild
> +IUSE=""
We can [drop](https://dev.gentoo.org/~ulm/pms/head/pms.html#x1-620007.3) empty IUSE.

2020-09-15 06:29 UTC, thesamesam commented on app-editors/visual-studio-code-bin/visual-studio-code-bin-1.47.3.ebuild
> +	x11-libs/cairo"
Sort?

2020-09-15 06:29 UTC, thesamesam commented on app-editors/visual-studio-code-bin/visual-studio-code-bin-1.47.3.ebuild
> +	S="${WORKDIR}/VSCode-linux-x64"
We should set S in global scope, right below SRC_URI or right above the first phase definition. So we can get rid of pkg_setup here.

2020-10-14 13:15 UTC, rossbridger commented
@oniGino has been unresponsive for quite a while, certainly not on track for maintaining a frequently updated package like vscode. I think we can close this PR now.

2020-10-14 13:53 UTC, oniGino commented
> @oniGino has been unresponsive for quite a while, certainly not on track for maintaining a frequently updated package like vscode. I think we can close this PR now.

I have made every change requested for this PR and am waiting for review/merge. 

What else do you want?

2020-10-14 14:02 UTC, rossbridger commented
> I have made every change requested for this PR and am waiting for review/merge.
You have already received reviews in the past two months, but you haven't resolved any of them.

2021-01-03 15:48 UTC, closed without merging