media-fonts/source-han-sans: Version bump to 2.000 and 2.001
gentoo/gentoo pull request #12578
Opened 2019-07-30 12:30 UTC by shimataro

create v2.000 and v2.001 (copy of v1.004)

2020-09-01 12:44 UTC, shimataro commented
@rossbridger 
There is no special reason for it, so v2.000 can be removed safely :smiley:

2021-03-25 17:07 UTC, ajakk requested changes
You can also add a `Closes: https://bugs.gentoo.org/699610` to your commit message. Also, we will need the signoff to contain your real name according to [GLEP-76](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin)

2021-03-25 17:07 UTC, ajakk commented on media-fonts/source-han-sans/source-han-sans-2.000.ebuild
> +# Copyright 1999-2018 Gentoo Foundation
I think adding 2.000 is unnecessary if 2.001 is added too.

2021-03-25 17:07 UTC, ajakk commented on media-fonts/source-han-sans/source-han-sans-2.001.ebuild
> +EAPI=6
Please update to EAPI=7.

2021-03-25 17:07 UTC, ajakk commented on media-fonts/source-han-sans/source-han-sans-2.001.ebuild
> +inherit font
Newline between EAPI and inherit lines, please.

2021-03-25 17:07 UTC, ajakk commented on media-fonts/source-han-sans/source-han-sans-2.001.ebuild
> +S=${WORKDIR}
Should quote "${WORKDIR}"

2021-03-25 17:07 UTC, ajakk commented on media-fonts/source-han-sans/source-han-sans-2.001.ebuild
> +	use l10n_ko && FONT_S="${S}/SourceHanSansKR" font_src_install
Can we add the Hong Kong thing as mentioned in the bug? https://bugs.gentoo.org/699610

2021-06-20 03:49 UTC, ajakk commented
I guess no one is there :(

2021-06-20 03:49 UTC, closed without merging