app-shells/tasksh: Added tasksh 1.2.0
gentoo/gentoo pull request #12769
Opened 2019-08-23 04:40 UTC by mmagorsc

Tasksh is a shell for Taskwarrior.

Bug: https://bugs.gentoo.org/673534
Package-Manager: Portage-2.3.69, Repoman-2.3.11

2020-03-12 11:15 UTC, AndrewAmmerlaan commented
Hi there,

Sometimes 'new package' PRs get snowed under by all the other ones (new packages are low priority compared to fixes to already existing packages). If you'd like to make this ebuild available to the Gentoo users anyway, might I suggest the [GURU overlay](https://wiki.gentoo.org/wiki/Project:GURU). This is an ebuild repository maintained collaboratively by Gentoo users. To gain access to the repository, simply create an "Access request" on bugs.gentoo.org.

2021-03-25 17:18 UTC, ajakk requested changes

2021-03-25 17:18 UTC, ajakk commented on app-shells/tasksh/metadata.xml
> +    <email>max@magorsch.de</email>
A different email might be more appropriate now ;)

2021-03-25 17:18 UTC, ajakk commented on app-shells/tasksh/tasksh-1.2.0.ebuild
> +EAPI=6
Can we upgrade to EAPI=7?

2021-03-25 17:18 UTC, ajakk commented on app-shells/tasksh/tasksh-1.2.0.ebuild
> +inherit cmake-utils
`cmake-utils` has been deprecated, can we port to cmake.eclass?

2021-03-25 17:18 UTC, ajakk commented on app-shells/tasksh/tasksh-1.2.0.ebuild
> +	      cmake-utils_src_prepare
Looks like a tab and a bunch of spaces here, and the below indented blocks are multiple tabs, let's be consistent with one tab per indentation?

2022-08-31 05:54 UTC, ajakk commented
Feel free to reopen if you continue working on this.

2022-08-31 05:54 UTC, closed without merging