Adding aqbanking-5.99.33_beta and gwenhywfar-4.99.16_beta
gentoo/gentoo pull request #13015
Opened 2019-09-22 21:19 UTC by braegel

Atoms are required for PSD2 support. Any financial transaction api in europe has to enforce this.

2021-03-27 06:13 UTC, scardracs commented
Be sure to add both files on your manifest running ebuild *packagename* manifest and push Manifest again, this will fix you errors

2021-03-27 09:33 UTC, scardracs requested changes

2021-03-27 09:33 UTC, scardracs commented on net-libs/aqbanking/aqbanking-5.99.33_beta.ebuild
> +SRC_URI="https://www.aquamaniac.de/rdm/attachments/download/145/${PN}-${MY_PV}.tar.gz"
Looks like link has been changed into https://www.aquamaniac.de/rdm/projects/aqbanking/files

2021-03-27 09:33 UTC, scardracs commented on net-libs/aqbanking/aqbanking-5.99.33_beta.ebuild
> +# Copyright 1999-2019 Gentoo Authors
1999-2021

2021-03-27 09:33 UTC, scardracs commented on sys-libs/gwenhywfar/gwenhywfar-4.99.16_beta.ebuild
> +SRC_URI="https://www.aquamaniac.de/rdm/attachments/download/140/${PN}-${MY_PV}.tar.gz"
Same as before

2021-06-20 04:14 UTC, ajakk commented
I suppose nobody's there :(

2021-06-20 04:14 UTC, closed without merging