media-fonts/source-pro: version bump, update to source-sans-pro-2.045R-ro-1.095R-it / source-serif-pro-2.010R-ro-1.010R-it
gentoo/gentoo pull request #13931
Opened 2019-12-09 18:27 UTC by shimataro

Update to [source-sans-pro-2.045R-ro-1.095R-it](https://github.com/adobe-fonts/source-sans-pro/releases/tag/2.045R-ro%2F1.095R-it) / [source-serif-pro-2.010R-ro-1.010R-it](https://github.com/adobe-fonts/source-serif-pro/releases/tag/2.010R-ro%2F1.010R-it)

2021-03-26 02:04 UTC, ajakk requested changes
Ping @gentoo/fonts

2021-03-26 02:04 UTC, ajakk commented on media-fonts/source-pro/source-pro-20191209.ebuild
> +EAPI=6
Can we update to EAPI=7 at this point?

2021-03-26 02:04 UTC, ajakk commented on media-fonts/source-pro/source-pro-20191209.ebuild
> +inherit font
Newline in between EAPI and inherit lines, please.

2021-12-12 05:58 UTC, ajakk commented
I guess no one is there.

2021-12-12 05:58 UTC, closed without merging

2021-12-12 13:26 UTC, shimataro commented
Very sorry for late reply...
Since both fonts have new releases, I will modify ebuild file and create another PR later.

<https://github.com/adobe-fonts/source-serif/releases>
<https://github.com/adobe-fonts/source-sans/releases>