dev-util/android sdk update manager
gentoo/gentoo pull request #14170
Opened 2019-12-29 17:11 UTC by linux923344

2021-12-12 06:16 UTC, ajakk requested changes

2021-12-12 06:16 UTC, ajakk commented on dev-util/android-sdk-update-manager/android-sdk-update-manager-26.1.1.ebuild
> +EAPI="5"
Please update to EAPI 8.

2021-12-12 06:16 UTC, ajakk commented on dev-util/android-sdk-update-manager/android-sdk-update-manager-26.1.1.ebuild
> +IUSE=""
Can drop this no-op line

2021-12-12 06:16 UTC, ajakk commented on dev-util/android-sdk-update-manager/android-sdk-update-manager-26.1.1.ebuild
> +
Need a BDEPEND on unzip for the distfile, right?

2021-12-12 06:16 UTC, ajakk commented on dev-util/android-sdk-update-manager/android-sdk-update-manager-26.1.1.ebuild
> +	enewgroup android
Please instead use the new acct-group package.

2021-12-12 06:16 UTC, ajakk commented on dev-util/android-sdk-update-manager/android-sdk-update-manager-26.1.1.ebuild
> +cp -pPR "${S}/*" "${ED}${ANDROID_SDK_DIR}/tools" || die "failed to install tools"
Just the `${S}` should be in quotes, else it will try to copy from a literal "${S}/*" directory.

2021-12-12 06:16 UTC, ajakk commented on dev-util/android-sdk-update-manager/android-sdk-update-manager-26.1.1.ebuild
> +rm -rf "${ED}${ANDROID_SDK_DIR}/tools/lib64"
Needs a `|| die`.

2021-12-21 20:30 UTC, y0rune commented
Okey @ajakk you can try now ;) I tried to change it ;) Can you review it again?

2022-08-31 06:21 UTC, ajakk commented
Please also add the Signed-off-by line that you put in the PR description in your commit messages.

2022-08-31 07:24 UTC, y0rune commented
All right I will update that package today and I will update the commit ;)

2022-11-19 19:55 UTC, scardracs commented
Did you take a look on https://bugs.gentoo.org/buglist.cgi?quicksearch=ndroid-sdk-update-manager&list_id=6602049 ? Bumping that could potentially close one or more of these bugs? As I can see you can at least add `Closes: https://bugs.gentoo.org/704198` in your commit so gentoo-bot know it will be closed when PR will be merged

2022-11-19 20:07 UTC, scardracs commented
You may also want to update your version as the latest one is https://dl.google.com/android/repository/commandlinetools-linux-9123335_latest.zip

2022-11-21 23:32 UTC, y0rune commented
Hello!
Sorry for my response. I changed the tittle. 
The package @scardracs `commandline` is not the same as `android-sdk`.

I will check the bugs in that week and I will come back with the output.

2022-11-21 23:45 UTC, y0rune commented
Hello!
I have to recommit my changes. 
Firstly, I am so sorry for my delay about the answers.
Secondly, @scardracs the `commandlinetools` and `android-sdk` is not the same tools.

I will see the bugs in that week and I will come back ;)

2022-11-22 00:45 UTC, scardracs commented
> Hello!
> 
> I have to recommit my changes. 
> 
> Firstly, I am so sorry for my delay about the answers.
> 
> Secondly, @scardracs the `commandlinetools` and `android-sdk` is not the same tools.
> 
> 
> 
> I will see the bugs in that week and I will come back ;) 

Ups, my bad

2022-11-26 20:45 UTC, y0rune commented
All right I will close the specific bugs ;) I will commit it and you please check it @scardracs ;) 
Thank you!

2022-11-26 21:02 UTC, closed without merging

2022-11-26 21:02 UTC, y0rune commented
I will do it on the another branch if it is not so old like this.