dev-python/ebuildtester: Adding sys-fs/fuse dep
gentoo/gentoo pull request #15514
Opened 2020-04-25 11:52 UTC by alarig

Closes: https://bugs.gentoo.org/719388
Package-Manager: Portage-2.3.89, Repoman-2.3.20
Signed-off-by: Alarig Le Lay <alarig@swordarmor.fr>

2020-12-15 17:45 UTC, SoapGentoo requested changes

2020-12-15 17:45 UTC, SoapGentoo commented on dev-python/ebuildtester/ebuildtester-0.1.16.ebuild
> +	sys-fs/fuse
all of these needs revbumps (why?)

2020-12-15 21:38 UTC, alarig commented on dev-python/ebuildtester/ebuildtester-0.1.16.ebuild
> +	sys-fs/fuse
I moved my modification to -r1

2020-12-15 22:13 UTC, nicolasbock approved these changes
Thanks @alarig ! I think this looks great!

2020-12-16 17:57 UTC, nicolasbock commented
Merged as 94e254d76d2212d0afd3876659cb4a3058e9918c

2020-12-16 17:57 UTC, closed without merging