sci-astronomy/xephem: EAPI7, use HTTPS, add missing eclass, fix SRC_URI
gentoo/gentoo pull request #16560
Opened 2020-07-03 08:36 UTC by mm1ke

Hi,

This updates the ebuild to use https and adds the missing `desktop` eclass.
Since the SRC_URI wasn't working anymore I've also added a EAPI7 version (with some cleanup) and updated the SRC_URI. I haven't updated the orginial ebuild since the new source differ by 2 byte's but other than that it's the same source. (and even is provided by the original homepage)

```diff
4c4
< EAPI=6
---
> EAPI=7
6c6
< inherit desktop eutils toolchain-funcs
---
> inherit desktop toolchain-funcs
10c10
< SRC_URI="http://97.74.56.125/free/${P}.tar.gz"
---
> SRC_URI="https://www.clearskyinstitute.com/xephem/${P}.tgz"
14,15c14
< KEYWORDS="amd64 ppc ppc64 x86 ~amd64-linux ~x86-linux"
< IUSE=""
---
> KEYWORDS="~amd64 ~ppc ~ppc64 ~x86 ~amd64-linux ~x86-linux"
31,32c30,31
<       echo > "${T}"/XEphem "XEphem.ShareDir: /usr/share/${PN}"
<       echo > "${T}"/99xephem "XEHELPURL=/usr/share/doc/${PF}/html/xephem.html"
---
>       echo > "${T}"/XEphem "XEphem.ShareDir: /usr/share/${PN}" || die
>       echo > "${T}"/99xephem "XEHELPURL=/usr/share/doc/${PF}/html/xephem.html" || die
42d40
<       has_version '<x11-base/xorg-x11-7.0' && insinto /etc/X11/app-defaults
```

2020-09-18 18:47 UTC, SoapGentoo requested changes

2020-09-18 18:47 UTC, SoapGentoo commented on sci-astronomy/xephem/xephem-3.7.7-r1.ebuild
> +	virtual/jpeg:0=
`:0` only (this is a virtual)

2020-09-18 18:47 UTC, SoapGentoo commented on sci-astronomy/xephem/xephem-3.7.7-r1.ebuild
> +	sys-apps/groff"
`groff` needs to go into `BDEPEND`

2020-09-18 18:47 UTC, SoapGentoo commented on sci-astronomy/xephem/xephem-3.7.7-r1.ebuild
> +	doenvd "${T}"/99xephem
consider ditching both these and doing the `newins -` `newenvd -` trick without resorting to temporaries

2020-09-18 18:47 UTC, SoapGentoo commented on sci-astronomy/xephem/xephem-3.7.7-r1.ebuild
> +	cd GUI/xephem
missing `|| die`

2020-09-19 16:08 UTC, mm1ke commented
@SoapGentoo 
Updated with all your suggestions/fixes included :)

2020-12-12 08:46 UTC, mm1ke commented
ping
any chance we can merge this? :)

2021-02-12 22:44 UTC, ConiKost commented
Could you update to solve merge conflict?

2021-02-13 08:56 UTC, mm1ke commented
@ConiKost done, should be fine now to merge :)

2021-02-13 13:09 UTC, ConiKost approved these changes

2021-02-13 13:11 UTC, closed without merging