app-eselect/eselect-clang: New package
gentoo/gentoo pull request #16673
Opened 2020-07-12 01:11 UTC by Infrasonics

Simple eselect module to manage multiple installed versions of clang and
clang++.

Closes: https://bugs.gentoo.org/732304
Signed-off-by: Fabian Dreer <infrasonics@gmx.de>
Package-Manager: Portage-2.3.99, Repoman-2.3.23

2020-07-12 06:13 UTC, Dessa commented
line 7 does not appear to be expanded.
line 116 seems to have an incorrect error message

2020-07-12 12:35 UTC, Infrasonics commented
@mgorny  Thank you for pointing that out. I do need another pointer though; how can I manipulate the `PATH` of the parent shell from inside the module (without the use of evil `eval`). Sourcing doesn't work and I couldn't find a [utility function](https://wiki.gentoo.org/wiki/Project:Eselect/Developer_guide#Utility_functions) to do that.

From [this proposal](https://wiki.gentoo.org/wiki/User:MGorny/New_eselect-opengl_design) I learned that `env.d` might be the proper way to go; then my question is: What prefix am I allowed to use in `XXclang`? Did I miss another possibility?

@Dessa Will be fixed in the next commit, thx.

2020-07-12 12:44 UTC, mgorny commented
You can't. Generally you run env-update and it tells the user how to source new profile env.

You need to use a prefix higher than the one installed by llvm. I don't think there are any limitations beyond that but maybe leave 99 to the user.

2020-07-12 16:47 UTC, Infrasonics commented
@mgorny It ended up being an `eselect-llvm` instead of an `eselect-clang`, so I guess I should close this here and open a new merge request? What creates the least overhead for you developers?

2020-07-12 16:51 UTC, mgorny commented
No difference, really. You can just force-push and rename.

2022-02-06 01:27 UTC, l29ah commented
Any reason not to merge it?

2022-02-06 08:31 UTC, mgorny requested changes
I'm sorry, I haven't time to look at it yet. I'm going to leave some comments on eselect code as well later today but you can update the ebuild nevertheless.

2022-02-06 08:31 UTC, mgorny commented on app-eselect/eselect-llvm/eselect-llvm-20200712.ebuild
> +IUSE=""
Please keep the variable order consistent with other ebuilds, i.e. LICENSE/SLOT/KEYWORDS in one block, in order. Remove empty IUSE.

2022-02-06 08:31 UTC, mgorny commented on app-eselect/eselect-llvm/eselect-llvm-20200712.ebuild
> +KEYWORDS="~alpha ~amd64 ~arm ~arm64 ~hppa ~ia64 ~m68k ~mips ~ppc ~ppc64 ~riscv ~s390 ~sparc ~x86 ~ppc-aix ~x64-cygwin ~amd64-linux ~x86-linux ~ppc-macos ~x64-macos ~x86-macos ~m68k-mint ~sparc-solari
Start with just `~amd64` (presuming that's what you're using). Leave adding other arches to arch teams.

2022-02-06 08:31 UTC, mgorny commented on app-eselect/eselect-llvm/eselect-llvm-20200712.ebuild
> +HOMEPAGE="https://wiki.gentoo.org/wiki/Project:LLVM"
There's nothing on the wiki about this, put your gh page here.

2022-02-06 08:31 UTC, mgorny commented on app-eselect/eselect-llvm/eselect-llvm-20200712.ebuild
> +# Copyright 1999-2020 Gentoo Authors
Update your calendar.

2022-02-06 08:31 UTC, mgorny commented on app-eselect/eselect-llvm/eselect-llvm-20200712.ebuild
> +S="${WORKDIR}"
`S` goes below `SRC_URI` these days.

2022-02-06 21:54 UTC, Infrasonics commented
@mgorny Thank you for the help and suggestions, I hope things are decent now.

2022-09-01 06:52 UTC, mgorny commented on app-eselect/eselect-llvm/eselect-llvm-20220206.ebuild
> +EAPI=7
EAPI 8, please.

2022-09-01 06:52 UTC, mgorny commented on app-eselect/eselect-llvm/eselect-llvm-20220206.ebuild
> +
Remove the empty line.

2022-11-22 19:12 UTC, scardracs commented
Is this still a thing @Infrasonics?

2025-03-24 07:14 UTC, zyxhere commented
The account has been inactive since 2022 @mgorny any interest in finishing the work here? This would a very useful package to have

2025-03-24 10:24 UTC, closed without merging

2025-03-24 10:24 UTC, mgorny commented
No interest.