Fuse emulator updates
gentoo/gentoo pull request #17615
Opened 2020-09-20 13:54 UTC by atomsymbol

Please merge. Thanks.

Closes: https://bugs.gentoo.org/743394

2020-09-20 13:58 UTC, SoapGentoo requested changes

2020-09-20 13:58 UTC, SoapGentoo commented on app-emulation/fuse/fuse-1.5.7.ebuild
> +	if use joystick; then
`use joystick && myconf+=( $(use_enable backend-sdl ui-joystick) )`

2020-09-20 14:11 UTC, atomsymbol commented on app-emulation/fuse/fuse-1.5.7.ebuild
> +	if use joystick; then
Thanks.

2020-10-10 06:33 UTC, juippis approved these changes
Thanks, please note that we like to include package name and version where the patch was included in, in the patch name. This way it's easier for people outside Gentoo find and use the patch if needed.

2020-10-10 07:23 UTC, closed without merging