dev-java/openjdk-bin: Latest jdk release jdk15
gentoo/gentoo pull request #17655
Opened 2020-09-24 23:36 UTC by dblaber

Adding ebuild for the latest non-lts jdk release, jdk15.

Signed-off-by: Darren Blaber dmbtech@gmail.com

2020-10-12 03:03 UTC, gyakovlev requested changes
minor nits.
otherwise works =) but I'll test it more a bit later.

2020-10-12 03:03 UTC, gyakovlev commented on dev-java/openjdk-bin/openjdk-bin-15_p36.ebuild
> +
check for `::gentoo` version

I have a stable symlink here

```
# provide stable symlink
    dosym "${P}" "/opt/${PN}-${SLOT}"
```

2020-10-12 03:03 UTC, gyakovlev commented on dev-java/openjdk-bin/openjdk-bin-15_p36.ebuild
> +IUSE="alsa cups -gentoo-vm headless-awt source"
replace the `-` with `+` , it will be masked, but enabled.

2021-11-23 21:07 UTC, ConiKost commented
Since we have now jdk17, I would close this, as version 12-16 are non lts, so I don't think we need them anymore.

2021-11-23 21:07 UTC, closed without merging