dev-libs/igraph: version bump to 0.8.3
gentoo/gentoo pull request #17749
Opened 2020-10-02 13:30 UTC by epsilon-0

Package-Manager: Portage-3.0.8, Repoman-3.0.1
Signed-off-by: Aisha Tammy <gentoo@aisha.cc>

2020-10-31 17:48 UTC, SoapGentoo requested changes

2020-10-31 17:48 UTC, SoapGentoo commented on dev-libs/igraph/igraph-0.8.3.ebuild
> +	dev-libs/gmp:0
`:0=`

2020-10-31 17:48 UTC, SoapGentoo commented on dev-libs/igraph/igraph-0.8.3.ebuild
> +	sci-mathematics/glpk
`:=`

2020-10-31 17:59 UTC, epsilon-0 commented on dev-libs/igraph/igraph-0.8.3.ebuild
> +	dev-libs/gmp:0
done

2020-10-31 17:59 UTC, epsilon-0 commented on dev-libs/igraph/igraph-0.8.3.ebuild
> +	sci-mathematics/glpk
done

2020-11-14 22:25 UTC, SoapGentoo approved these changes

2020-11-14 22:47 UTC, closed without merging