games-emulation/vbam: don't override CMAKE_AR
gentoo/gentoo pull request #18064
Opened 2020-10-29 01:42 UTC by DarthGandalf

Closes: https://bugs.gentoo.org/733938
Package-Manager: Portage-3.0.8, Repoman-3.0.1
Signed-off-by: Alexey Sokolov <alexey+gentoo@asokolov.org>

2020-11-01 22:17 UTC, chewi requested changes
Sorry but a patch isn't needed here because you can just pass `-DENABLE_LTO=OFF` instead. The extra logic the project has around LTO doesn't seem necessary so there's no harm in doing this.

2020-11-01 22:40 UTC, DarthGandalf commented
Doesn't `set()` make it to ignore `-D`? `set(ENABLE_LTO ON CACHE ...)` would work like you describe.

2020-11-07 22:22 UTC, chewi commented
You did have me thinking I'd got confused but actually I was right. :stuck_out_tongue: `LTO_DEFAULT` is defined with `set` but `ENABLE_LTO` is already an `option`.

```
option(ENABLE_LTO "Compile with Link Time Optimization (gcc and clang only)" ${LTO_DEFAULT})
```

2020-11-07 22:35 UTC, DarthGandalf commented
Indeed. I haven't noticed that there are 2 variables, not one.
Fixed.

2020-11-07 22:48 UTC, closed without merging