app-misc/editor-wrapper: Avoid infinite recursion
gentoo/gentoo pull request #18089
Opened 2020-10-31 11:00 UTC by cmplstofB

If `$EDITOR`/`$PAGER` variables are identical to 'editor'/'pager' respectively, the script recurs infinitely.

e.g.:
```console
$ EDITOR=editor
$ editor # recurs infinitely
```

The users who set these variables to such names probably not intend to cause this behavior, so it would be better to detect infinite recursion and exit with an error.

2020-10-31 12:27 UTC, ulm requested changes
Some general comments:

- Don't change the script in place, but make a new version 5, plus a new ebuild (straight to stable is fine, the change looks simple enough)
- Keep lines below 80 characters please
- Don't forget to update the copyright years in line 2

2020-10-31 12:30 UTC, cmplstofB commented
@ulm Ok, i see.
Sorry for making you tell me about it.

2020-12-15 07:25 UTC, thesamesam commented
Fix within this PR please (then force push), thanks!

2020-12-15 09:34 UTC, ulm commented
> ## Missing GCO sign-off
> 
> Please read the terms of [Gentoo Certificate of Origin](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin) and acknowledge them by adding a sign-off to _all_ your commits.

This needs to be addressed too, otherwise we cannot merge these commits.

2024-06-20 16:45 UTC, ulm commented
Looking at this again, I think it is unlikely for this problem to occur in practice:
- `editor` isn't one of the values offered by editor.eselect;
- `/usr/libexec` is not meant to be in users' path;
- This leaves `EDITOR` set to `/usr/libexec/editor` as a possibility, which the proposed change won't catch however.

So I suggest to keep things as they are, i.e. I am closing this PR.

2024-06-20 16:45 UTC, closed without merging