dev-lang/go: introduce slots
gentoo/gentoo pull request #18546
Opened 2020-12-07 00:01 UTC by Whissi

While we still don't support installing multiple dev-lang/go
versions simultaneously, we need slots to support proper targeting in
GLSAs.

2020-12-07 00:01 UTC, Whissi commented
Note: I ignored live ebuild, you probably have to find another solution for it.

2020-12-07 00:04 UTC, Whissi commented
@williamh please review

2021-01-09 04:25 UTC, thesamesam approved these changes

2021-01-12 19:40 UTC, floppym requested changes
Overall, this is an abuse of slots to compensate for limitations in the GLSA tooling.

I suggest enhancing the version matching syntax used by the GLSA tools to allow for version ranges with lower and upper bounds that will be applied together.

2021-01-12 19:40 UTC, floppym commented on dev-lang/go/go-1.14.12-r1.ebuild
> +	!dev-lang/go:1.15"
You would also need to block slot 0 to force portage to unmerge currently installed versions.

2023-11-19 09:59 UTC, thesamesam commented
If we're going to do this, we should really just slot Go properly (which is not a bad idea).

2023-11-19 09:59 UTC, closed without merging