games-emulation/openmsx: resurrect after python2 purge (with 16.0)
gentoo/gentoo pull request #18673
Opened 2020-12-15 23:25 UTC by ajakk

Package-Manager: Portage-3.0.12, Repoman-3.0.2
Signed-off-by: John Helmert III <jchelmert3@posteo.net>

2020-12-16 00:44 UTC, DarthGandalf commented on games-emulation/openmsx/openmsx-16.0.ebuild
> +IUSE="test"
This is not necessary. You're not using this USE flag. And if you remove it, RESTRICT won't be needed either

2020-12-16 00:44 UTC, DarthGandalf commented on games-emulation/openmsx/openmsx-16.0.ebuild
> +		INSTALL_SHARE_DIR="/usr/share/${PN}" \
`${EPREFIX}`?

2020-12-19 19:34 UTC, chewi commented
This is broken in several ways but I don't think I'll have time to go round and round in a review so I may just handle it myself.

2020-12-20 21:49 UTC, chewi requested changes
Much better! Just a couple of minor things now.

2020-12-20 21:49 UTC, chewi commented on games-emulation/openmsx/openmsx-16.0.ebuild
> +	append-cxxflags '-std=c++17'
Now you have `src_configure`, I feel like this could go there instead.

2020-12-20 21:49 UTC, chewi commented on games-emulation/openmsx/openmsx-16.0.ebuild
> +	xdg_icon_cache_update
I'd rather call `xdg_pkg_postinst` so that we don't have to worry about the details of what that eclass is doing, especially as it could change.

2020-12-21 09:27 UTC, chewi requested changes

2020-12-21 09:27 UTC, chewi commented on games-emulation/openmsx/openmsx-16.0.ebuild
> +	virtual/opengl"
Sorry, I was doing one more final check and noticed through `readelf -d` that the dependencies are outdated.

* libxml2 was dropped in 2014.
* SDL_image was dropped in 2010!!
* It should now depend on zlib.

2020-12-21 22:24 UTC, closed without merging

2020-12-21 22:26 UTC, chewi commented
Merged now, thanks! I took the liberty of removing the subslot operator from zlib. The package does have a subslot but this was added in error and it makes Portage work a fair bit harder so you should just leave out the operator in this case.