sci-geosciences/grass: version bump 7.8.5
gentoo/gentoo pull request #18753
Opened 2020-12-21 20:16 UTC by hamarituc

version bump

2020-12-26 21:17 UTC, a17r requested changes
Maybe you want to drop oldest version in a second commit?

2020-12-26 21:17 UTC, a17r commented on sci-geosciences/grass/grass-7.8.5.ebuild
> +	eapply_user
This is redundant after you already called `default`.

2020-12-29 13:56 UTC, hamarituc commented
> Maybe you want to drop oldest version in a second commit?

I dropped version 7.8.3, but kept 7.8.4 and requested stabilization for the latter version instead. I hope it's OK.

2021-01-20 13:24 UTC, juippis approved these changes
With this amount of seds I'm surprised it isn't broken.

2021-05-23 10:07 UTC, a17r commented
Bump apparently happened in commit 8f11c6038f858cc6ae60df12ee37f0bc0b462fb5. Thanks!

2021-05-23 10:07 UTC, closed without merging