eclass/toolchain-funcs: new function tc-ld-disable-lld()
gentoo/gentoo pull request #19116
Opened 2021-01-18 23:59 UTC by telans

`sys-libs/db` uses `tc-ld-disable-gold` in order to use `-Wl,--default-symver`. `ld.lld` also requires disabling in order to use that flag. This function will be used for that purpose.

Package-Manager: Portage-3.0.13, Repoman-3.0.2
Signed-off-by: Theo Anderson <telans@posteo.de>

2021-01-19 00:18 UTC, telans commented
> New issues caused by PR:

Pretty sure this is wrong

2021-01-19 17:04 UTC, floppym commented
> Although I wonder if these two functions should be migrated to something like tc-ld-enable-bfd?

Yes, this seems like a much nicer solution. I would probably call it `tc-ld-force-bfd` instead.

We could also retain `tc-ld-disable-gold` and just have it call `tc-ld-force-bfd` until all ebuilds are migrated to the new function.

2021-01-20 10:40 UTC, telans commented
> I would probably call it `tc-ld-force-bfd` instead.

Done, this is definitely better.

2021-01-20 17:30 UTC, floppym requested changes
I think you should replace the body of tc-ld-disable-gold with a call to tc-ld-force-bfd. It should also be marked as deprecated.

Please remove "eclass/" from the summary line in the commit message.

This patch should then be sent to the gentoo-dev mailing list for official review.

2021-01-21 21:37 UTC, trofi approved these changes

2021-01-23 09:01 UTC, closed without merging

2021-01-23 09:01 UTC, trofi commented
Pulled as is. Thank you!