games-misc/wtf: bump package
gentoo/gentoo pull request #19268
Opened 2021-01-31 10:08 UTC by waebbl

Package-Manager: Portage-3.0.14, Repoman-3.0.2
Signed-off-by: Bernd Waibel <waebbl@gmail.com>

2021-01-31 20:45 UTC, ConiKost requested changes
Please split your commit into two. One adds the new version, a second one drops the old version. Don't do that in one commit.

2021-02-01 08:20 UTC, ConiKost requested changes
Just a few small nit picks :-)

Could you also say in your commit for bumping version, to which version you are bumping?
Thanks!

2021-02-01 08:20 UTC, ConiKost commented on games-misc/wtf/wtf-20210130.ebuild
> +IUSE=""
If you don't have any use flags, you can drop ```IUSE```.

2021-02-01 08:20 UTC, ConiKost commented on games-misc/wtf/wtf-20210130.ebuild
> +HOMEPAGE="http://netbsd.org/"
Could check, if ```HOMEPAGE``` is also reachable via ```https``` and update, if so?

2021-02-01 19:49 UTC, waebbl commented
> Just a few small nit picks :-)
> 
> Could you also say in your commit for bumping version, to which version you are bumping?
> Thanks!

Ah yes, of course. Usually I do this, don't why not here...
I also fix the other two issues.

2021-02-02 21:19 UTC, ConiKost approved these changes

2021-02-02 21:29 UTC, ConiKost commented
Commited.
https://github.com/gentoo/gentoo/commit/4474b12134a18bdad61f88f68de85b0343668d16

2021-02-02 21:29 UTC, closed without merging

2021-02-02 21:36 UTC, waebbl commented
Thank you @ConiKost