sci-physics/lhapdf: Bump to 6.3.0
gentoo/gentoo pull request #19263
Opened 2021-01-30 10:45 UTC by jsmolic

2021-01-30 14:36 UTC, SoapGentoo requested changes

2021-01-30 14:36 UTC, SoapGentoo commented on sci-libs/udunits/udunits-2.2.28.ebuild
> +	for i in udunits2 udunits2-{accepted,base,common,derived,prefixes}; do
declare `local i` before

2021-01-30 14:36 UTC, SoapGentoo commented on sci-physics/lhapdf/lhapdf-6.3.0.ebuild
> +		cd "${S}/wrappers/python" && distutils-r1_src_prepare
separate this into 2 statements

2021-01-30 14:36 UTC, SoapGentoo commented on sci-physics/lhapdf/lhapdf-6.3.0.ebuild
> +	use doc && dodoc -r doc/doxygen/*
`use doc && dodoc -r doc/doxygen/.` (avoid globs)

2021-01-30 14:36 UTC, SoapGentoo commented on sci-physics/yoda/yoda-1.8.5.ebuild
> +	newbashcomp "${ED}"/usr/share/YODA/yoda-completion ${PN}
inline `${PN}` here

2021-01-30 21:25 UTC, jsmolic commented on sci-libs/udunits/udunits-2.2.28.ebuild
> +	for i in udunits2 udunits2-{accepted,base,common,derived,prefixes}; do
done

2021-01-30 21:25 UTC, jsmolic commented on sci-physics/lhapdf/lhapdf-6.3.0.ebuild
> +		cd "${S}/wrappers/python" && distutils-r1_src_prepare
done

2021-01-30 21:25 UTC, jsmolic commented on sci-physics/lhapdf/lhapdf-6.3.0.ebuild
> +	use doc && dodoc -r doc/doxygen/*
done

2021-01-30 21:25 UTC, jsmolic commented on sci-physics/yoda/yoda-1.8.5.ebuild
> +	newbashcomp "${ED}"/usr/share/YODA/yoda-completion ${PN}
done

2021-01-30 21:32 UTC, SoapGentoo requested changes

2021-01-30 21:32 UTC, SoapGentoo commented on sci-physics/lhapdf/lhapdf-6.3.0.ebuild
> +		cd "${S}/wrappers/python" || die
quoting?

2021-01-30 21:32 UTC, SoapGentoo commented on sci-physics/lhapdf/lhapdf-6.3.0.ebuild
> +	   distutils-r1_src_compile
wrogn indentation

2021-01-30 21:32 UTC, SoapGentoo commented on sci-physics/lhapdf/lhapdf-6.3.0.ebuild
> +		cd "${S}/wrappers/python" || die
ditto

2021-01-30 21:32 UTC, SoapGentoo commented on sci-physics/pythia/pythia-6.4.28-r2.ebuild
>  	cat > configure.ac <<-EOF
missing `|| die`

2021-01-30 21:32 UTC, SoapGentoo commented on sci-physics/pythia/pythia-6.4.28-r2.ebuild
>  	echo  >> Makefile.am "  tpythia6_called_from_cc.F pythia6_common_address.c"
all the echo's are missing `|| die`s

2021-01-30 21:32 UTC, SoapGentoo commented on sci-physics/pythia/pythia-8.2.26.ebuild
> +	default
prefer to patch before you `sed`

2021-01-31 08:30 UTC, jsmolic commented on sci-physics/lhapdf/lhapdf-6.3.0.ebuild
> +		cd "${S}/wrappers/python" || die
sure, fixed ;)

2021-01-31 08:30 UTC, jsmolic commented on sci-physics/lhapdf/lhapdf-6.3.0.ebuild
> +	   distutils-r1_src_compile
done

2021-01-31 08:30 UTC, jsmolic commented on sci-physics/lhapdf/lhapdf-6.3.0.ebuild
> +		cd "${S}/wrappers/python" || die
done

2021-01-31 08:31 UTC, jsmolic commented on sci-physics/pythia/pythia-6.4.28-r2.ebuild
>  	cat > configure.ac <<-EOF
done

2021-01-31 08:31 UTC, jsmolic commented on sci-physics/pythia/pythia-6.4.28-r2.ebuild
>  	echo  >> Makefile.am "  tpythia6_called_from_cc.F pythia6_common_address.c"
done

2021-01-31 08:31 UTC, jsmolic commented on sci-physics/pythia/pythia-8.2.26.ebuild
> +	default
done

2021-02-13 10:19 UTC, SoapGentoo requested changes

2021-02-13 10:19 UTC, SoapGentoo commented on sci-physics/pythia/pythia-6.4.28-r2.ebuild
>  		doins -r "${WORKDIR}"/examples
changes these 2 lines:
```
dodoc -r "${WORKDIR}"/examples
docompress -x /usr/share/doc/${PF}/examples
```

2021-02-13 10:19 UTC, SoapGentoo commented on sci-physics/pythia/pythia-8.2.26-r1.ebuild
>  	doenvd 99pythia8
Replace these two lines by
```
newenvd - 99pythia8 <<- _EOF_
	PYTHIA8DATA=${EPYTHIADIR}/xmldoc
_EOF_
```

2021-02-13 10:46 UTC, jsmolic commented on sci-physics/pythia/pythia-6.4.28-r2.ebuild
>  		doins -r "${WORKDIR}"/examples
Done

2021-02-13 10:46 UTC, jsmolic commented on sci-physics/pythia/pythia-8.2.26-r1.ebuild
>  	doenvd 99pythia8
Thanks, done

2021-02-13 22:52 UTC, closed without merging