x11-misc/rss-glx: Rescue from last rites and fix building with clang
gentoo/gentoo pull request #19511
Opened 2021-02-17 23:54 UTC by miller-alex

2021-02-21 16:06 UTC, SoapGentoo requested changes

2021-02-21 16:06 UTC, SoapGentoo commented on x11-misc/rss-glx/rss-glx-0.9.1-r2.ebuild
> +	default
```
libtool: link: x86_64-pc-linux-gnu-g++ -O2 -pipe -march=native -fdiagnostics-color=always -frecord-gcc-switches -Wall -Wl,-O1 -Wl,--hash-style=gnu -Wl,--sort-common -Wl,--defsym=__gentoo_check_ldflags__=1 -o fieldlines driver.o fieldlines.o  -lGLEW -Wl,--as-needed -lXext -lGLU -lGL -lSM -lICE -lX11 -lm
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/x11-misc/rss-glx-0.9.1-r2/work/rss-glx_0.9.1/src/PixelCity/.libs/libPixelCity.a(Deco.o): undefined reference to symbol '_ZTVN10__cxxabiv121__vmi_class_type_infoE@@CXXABI_1.3'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

2021-02-21 16:09 UTC, SoapGentoo commented on x11-misc/rss-glx/rss-glx-0.9.1-r2.ebuild
> +	default
you're linking a C and C++ code using the C compiler, this can't possibly work.

2021-02-21 16:29 UTC, SoapGentoo approved these changes

2021-02-21 16:32 UTC, closed without merging

2021-02-21 20:11 UTC, miller-alex commented
@SoapGentoo did you intentionally drop the stable ebuild?

2021-02-22 18:08 UTC, SoapGentoo commented
I have indeed, that was not a mistake. The idea is: we're unmasking it, so we're effectively starting from scratch again. This is also the procedure defined in the manual. We can shorten the time to calling stabilizations to 14 days.