net-analyzer/nethogs: added capabilities
gentoo/gentoo pull request #19587
Opened 2021-02-22 01:11 UTC by Alessandro-Barbieri

Package-Manager: Portage-3.0.14, Repoman-3.0.2
Signed-off-by: Alessandro Barbieri <lssndrbarbieri@gmail.com>

2021-02-22 08:15 UTC, thesamesam commented on net-analyzer/nethogs/nethogs-0.8.6-r1.ebuild
> +	virtual/pkgconfig
BDEPEND

2021-02-22 08:15 UTC, thesamesam commented on net-analyzer/nethogs/nethogs-0.8.6-r1.ebuild
> +DOCS=( DESIGN README.decpcap.txt README.md )
New line?

2021-03-05 16:53 UTC, thesamesam requested changes
We need an option for suid still given people can't always use caps, like we discussed

2021-03-15 01:50 UTC, Alessandro-Barbieri commented
Isn't suid a security hazard? The ebuild didn't had it in the first place. Also I have no sympathy for people stuck in the past.

2021-03-15 01:55 UTC, thesamesam commented
I meant in general with your PRs to remove it. And it's not about "stuck in the past" -- some filesystems can't support it, and so on. I just meant to make accepting your PRs for these easier. I agree with supporting caps where we can.

2021-03-15 23:30 UTC, thesamesam commented on net-analyzer/nethogs/nethogs-0.8.6-r1.ebuild
> +	ecaps cap_net_admin,cap_net_raw "${EROOT}/usr/bin/nethogs"
- ecaps doesn't exist?
- Isn't it at /usr/sbin/nethogs, not /usr/bin/nethogs?
- We haven't actually used the eclass here

2021-03-15 23:31 UTC, closed without merging

2021-03-15 23:31 UTC, thesamesam commented on net-analyzer/nethogs/nethogs-0.8.6-r1.ebuild
> +	ecaps cap_net_admin,cap_net_raw "${EROOT}/usr/bin/nethogs"
Fixed in https://github.com/gentoo/gentoo/commit/6db0315d786c499a9526ce7ee71d3229fea8fd26