dev-util/bazel: enable statically linked libstdc++ for gentoo prefix
gentoo/gentoo pull request #19736
Opened 2021-03-02 14:59 UTC by littlewu2508

Bug: https://bugs.gentoo.org/773982
Package-Manager: Portage-3.0.16, Repoman-3.0.2
Signed-off-by: Yiyang Wu <xgreenlandforwyy@gmail.com>

2021-03-02 15:19 UTC, littlewu2508 commented
In this pull request I added two USE flags -- 'prefix' and 'static-libs'. I want to prefer and force static-libs when prefix is used, and '-static-libs' as the default value when prefix is not spcefied. The current syntax using REQUIRED_USE only guarantees static-libs must come with prefix. Is there a better syntax?

2021-03-02 23:57 UTC, zmedico commented
> In this pull request I added two USE flags -- 'prefix' and 'static-libs'. I want to prefer and force static-libs when prefix is used, and '-static-libs' as the default value when prefix is not spcefied. The current syntax using REQUIRED_USE only guarantees static-libs must come with prefix. Is there a better syntax?

REQUIRED_USE is for requirements, not preferences. You can set a preference in the corresponding prefix profile's package.use. For automatic solving of REQUIRED_USE, we have https://www.gentoo.org/glep/glep-0073.html.

2021-03-03 00:04 UTC, zmedico requested changes
The `REQUIRED_USE="prefix? ( static-libs )"` setting only makes sense if that's the only workable solution for prefix. You can use package.use.force in the relevant profile if it needs to be forced for a particular profile.

2021-03-03 02:37 UTC, littlewu2508 commented
> 
> 
> The `REQUIRED_USE="prefix? ( static-libs )"` setting only makes sense if that's the only workable solution for prefix. You can use package.use.force in the relevant profile if it needs to be forced for a particular profile.

Currently it is the only workable solutions for prefix, so I think REQUIRED_USE is necessary. I updated profiles/features/prefix/package.use, which can enable static-libs by default. I suppose this is a resonable solution.

2021-03-05 11:29 UTC, littlewu2508 commented
@zmedico Any updates on reviewing?

2021-03-06 08:56 UTC, closed without merging

2021-03-06 08:56 UTC, zmedico commented
Thanks!