www-apps/netbox: Version bump 2.10.6
gentoo/gentoo pull request #19948
Opened 2021-03-16 00:47 UTC by anthonyryan1

We are no longer patching upgrade.sh to remove pip.

Because upgrade.sh runs everything inside of a virtualenv, it fails
to find many of the system dependencies that aren't installed in pip.

Going forward, people can run upgrade.sh which will duplicate the
dependencies in a virtualenv, or run the commands from inside
upgrade.sh oneby one to use the system versions.

Closes: https://bugs.gentoo.org/750836
Closes: https://bugs.gentoo.org/709330
Closes: https://bugs.gentoo.org/709448
Package-Manager: Portage-3.0.13, Repoman-3.0.2
Signed-off-by: Anthony Ryan <anthonyryan1@gmail.com>

2021-04-18 05:38 UTC, scardracs commented
@anthonyryan1 do you mind bump directly into 2.11.0?

2021-04-18 05:39 UTC, scardracs commented
You may want to add https://github.com/gentoo/gentoo/pull/18011 as closed when your PR will be merged

2021-04-18 14:53 UTC, anthonyryan1 commented
I've got 2.11.0 in my overlay, but there's a couple blockers to getting it in the tree.

* We need dev-python/tablib as a new package
* dev-python/django-tables2 needs to be updated to depend on tablib (unsure if we should make this default or a [tablib] use flag).

Then we can bump 2.11.0. I can get the other pull requests done in later today.

2021-04-18 14:55 UTC, scardracs commented
> I've got 2.11.0 in my overlay, but there's a couple blockers to getting it in the tree.
> 
>     * We need dev-python/tablib as a new package
> 
>     * dev-python/django-tables2 needs to be updated to depend on tablib (unsure if we should make this default or a [tablib] use flag).
> 
> 
> Then we can bump 2.11.0. I can get the other pull requests done in later today.

You also need to update py-gfm https://github.com/gentoo/gentoo/pull/20435

2021-04-18 15:37 UTC, scardracs commented
List of packages required for 2.11.0: #20435 #20442

2021-04-22 09:31 UTC, scardracs commented
@anthonyryan1 tablib is merged! You can move to 2.11 now :)

2021-04-23 01:33 UTC, anthonyryan1 commented
@scardracs can you confirm how py-gfm fits into netbox here? I installed it in a virtualenv (since that seems to be their recommended approach) and it didn't pull in gfm anywhere I could see.

Is it somehow a drop-in alternative for the dev-python/markdown used here?

2021-04-23 05:11 UTC, scardracs commented
> @scardracs can you confirm how py-gfm fits into netbox here? I installed it in a virtualenv (since that seems to be their recommended approach) and it didn't pull in gfm anywhere I could see.
> 
> Is it somehow a drop-in alternative for the dev-python/markdown used here?

Personally I don't know because I haven't checked more than list of deps

2021-04-23 05:59 UTC, scardracs commented
> @scardracs can you confirm how py-gfm fits into netbox here? I installed it in a virtualenv (since that seems to be their recommended approach) and it didn't pull in gfm anywhere I could see.
> 
> Is it somehow a drop-in alternative for the dev-python/markdown used here?

I thought it still required on 2.10/11 like 2.7 did

2021-04-23 07:54 UTC, SoapGentoo requested changes

2021-04-23 07:54 UTC, SoapGentoo commented on www-apps/netbox/netbox-2.10.8.ebuild
> +	cp -a ../${P} "${ED}"/opt
missing `|| die`

2021-04-23 07:54 UTC, SoapGentoo commented on www-apps/netbox/netbox-2.10.8.ebuild
> +dosym ../../etc/netbox/gunicorn_config.py /opt/netbox/gunicorn_config.py
indentation

2021-04-23 07:54 UTC, SoapGentoo commented on www-apps/netbox/netbox-2.10.8.ebuild
> +	/opt/netbox/netbox/netbox/configuration.py
indentation here too

2021-04-23 07:54 UTC, SoapGentoo commented on www-apps/netbox/netbox-2.10.8.ebuild
> +	dodir /etc/netbox
redundant with the following statement

2021-04-23 07:54 UTC, SoapGentoo commented on www-apps/netbox/netbox-2.10.8.ebuild
> +		if [[ $r = "2.5.10" ]]; then
```suggestion
		if [[ ${r} == "2.5.10" ]]; then
```

2021-04-25 19:35 UTC, scardracs commented on www-apps/netbox/netbox-2.11.1.ebuild
> +		>=dev-python/django-3.1[${PYTHON_MULTI_USEDEP}]
2.11.1 requires django 3.2 https://github.com/netbox-community/netbox/blob/develop/requirements.txt

2021-04-25 19:37 UTC, scardracs commented on www-apps/netbox/netbox-2.11.1.ebuild
> +		dev-python/django-debug-toolbar[${PYTHON_MULTI_USEDEP}]
I suggest to use `dev-python/django-debug-toolbar-3.2.1` as per requirement

2021-04-25 19:37 UTC, scardracs commented on www-apps/netbox/netbox-2.11.1.ebuild
> +		dev-python/django-debug-toolbar[${PYTHON_MULTI_USEDEP}]
I have github. There is a mayor=

2021-04-25 19:38 UTC, scardracs commented on www-apps/netbox/netbox-2.11.1.ebuild
> +		dev-python/django-mptt[${PYTHON_MULTI_USEDEP}]
We need to update our package to 0.12.0

2021-04-25 19:39 UTC, scardracs commented on www-apps/netbox/netbox-2.11.1.ebuild
> +		>=dev-python/django-rq-2.4.0[${PYTHON_MULTI_USEDEP}]
2.4.1

2021-04-25 19:42 UTC, scardracs commented on www-apps/netbox/netbox-2.11.1.ebuild
> +		>=dev-python/django-taggit-1.3.0[${PYTHON_MULTI_USEDEP}]
Need to be updated to 1.4.0

2021-04-25 19:44 UTC, scardracs commented on www-apps/netbox/netbox-2.11.1.ebuild
> +		>=dev-python/djangorestframework-3.12[${PYTHON_MULTI_USEDEP}]
3.12.4

2021-04-25 19:46 UTC, scardracs commented on www-apps/netbox/netbox-2.11.1.ebuild
> +		www-servers/gunicorn[${PYTHON_MULTI_USEDEP}]
20.1.0

2021-04-25 19:46 UTC, scardracs commented
Sorry for comments: I was signing which packages should I have to made a PR

2021-04-25 19:48 UTC, scardracs commented on www-apps/netbox/netbox-2.11.1.ebuild
> +		>=dev-python/pillow-8.1[${PYTHON_MULTI_USEDEP}]
8.2

2021-04-25 19:49 UTC, scardracs commented on www-apps/netbox/netbox-2.11.1.ebuild
> +		dev-python/pycryptodome[${PYTHON_MULTI_USEDEP}]
3.10.1

2021-04-25 19:49 UTC, scardracs commented on www-apps/netbox/netbox-2.11.1.ebuild
> +		>=dev-python/pyyaml-5.4[${PYTHON_MULTI_USEDEP}]
5.4.1

2021-04-25 19:50 UTC, scardracs commented on www-apps/netbox/netbox-2.11.1.ebuild
> +		>=dev-python/redis-py-3.3.11[${PYTHON_MULTI_USEDEP}]
I don't see this package as requirement

2021-04-25 19:50 UTC, scardracs commented on www-apps/netbox/netbox-2.11.1.ebuild
> +		dev-python/svgwrite[${PYTHON_MULTI_USEDEP}]
1.4.1

2021-04-28 15:14 UTC, SoapGentoo approved these changes

2021-04-28 15:42 UTC, SoapGentoo commented
@anthonyryan1 please also fix the comments from @scardracs, this is a last-rites candidate

2021-04-29 09:30 UTC, scardracs commented
I'm sorry @anthonyryan1 but I have closed my PR for porting packages needed for upgrade. If you want to take a look on it you could take ebuilds I have already done and try to finish all the ebuilds I have not done yet

2021-05-31 20:33 UTC, SoapGentoo commented
Removed from tree

2021-05-31 20:33 UTC, closed without merging