app-emulation/libvirt-glib: Version updated to 4.0.0
gentoo/gentoo pull request #20099
Opened 2021-03-24 12:44 UTC by jpds

Tested on `amd64`

2021-03-24 16:00 UTC, mattst88 requested changes

2021-03-24 16:00 UTC, mattst88 commented on app-emulation/libvirt-glib/libvirt-glib-4.0.0.ebuild
> +        dev-util/glib-utils
Use tabs for indentation, and only one per level.

2021-03-24 16:00 UTC, mattst88 commented on app-emulation/libvirt-glib/libvirt-glib-4.0.0.ebuild
> +        vala? ( $(vala_depend) )"
I like to put the trailing `"` on its own line. It helps minimize the diff if a dependency is added in the future.

2021-03-24 16:00 UTC, mattst88 commented on app-emulation/libvirt-glib/libvirt-glib-4.0.0.ebuild
> +        >=dev-libs/glib-2.38.0:2
`meson.build` says the minimum required is 2.48.

2021-03-24 16:00 UTC, mattst88 commented on app-emulation/libvirt-glib/libvirt-glib-4.0.0.ebuild
> +        >=app-emulation/libvirt-1.2.6:=
`meson.build` says the minimum required is 1.2.8.

2021-03-24 16:00 UTC, mattst88 commented on app-emulation/libvirt-glib/libvirt-glib-4.0.0.ebuild
> +        introspection? ( >=dev-libs/gobject-introspection-1.36.0:= )"
`meson.build` says the gobject-intospection minimum required is the same as the glib version (2.48).

2021-03-24 16:00 UTC, mattst88 commented on app-emulation/libvirt-glib/libvirt-glib-4.0.0.ebuild
> +        default
Single tab for indentation.

2021-03-24 16:00 UTC, mattst88 commented on app-emulation/libvirt-glib/libvirt-glib-4.0.0.ebuild
> +        dev-libs/libxml2:2
`meson.build` says the minimum required is 2.9.1.

2021-03-24 16:00 UTC, mattst88 commented on app-emulation/libvirt-glib/libvirt-glib-4.0.0.ebuild
> +                $(meson_feature vala vapi)
`meson_options.txt` has two other configuration options that I think we should have:
````
option('docs', type: 'feature', value: 'auto', description: 'whether to generate documentation')
option('tests', type: 'feature', value: 'auto', description: 'whether to build tests')
````

`docs` should be controlled by an `IUSE=gtk_doc` flag and should depend on `dev-util/gtk-doc`.

`tests` should be controlled by an `IUSE=test` flag that is implicitly enabled when building with `FEATURES=test`.

2021-03-24 16:47 UTC, jpds commented
@mattst88 Thanks for the review - I've fixed everything (my editor oddly added a space to my tabs), but the gobject-intospection dependency as 2.48 for it doesn't exist.

2021-03-24 17:01 UTC, mattst88 commented
> @mattst88 Thanks for the review - I've fixed everything (my editor oddly added a space to my tabs), but the gobject-intospection dependency as 2.48 for it doesn't exist.

Thanks! I meant *1*.48. Sorry about the confusion. Looks like you figured out my mistake :)

2021-03-25 02:34 UTC, closed without merging

2021-03-25 02:35 UTC, mattst88 commented
Thanks!

There are tons of needed GNOME version bumps (https://packages.gentoo.org/maintainer/gnome@gentoo.org/outdated). If you're interested in handling any others, please keep them coming :)