app-editors/juffed: bump snapshot version
gentoo/gentoo pull request #20751
Opened 2021-05-10 10:27 UTC by arthurzam

- added the github repo to `metadata.xml`
- moved `S=` closer to `SRC_URI=` (as stated in `skel.ebuild`).
- Take latest (2020-01-03) snapshot of code. This snapshot incorporates most patches that were used with old version.
- One patch, which fixed `qscintilla` library name, was removed to be set from configure step (using `-DQSCINTILLA_NAMES`). Works better that way.
- Removed versioned dependency of `qscintilla`, as we don't have such old version in tree.
- Removed the `[qt5(+)]` USE dependency as all those libraries don't have such USE flag.
- added `dev-qt/linguist-tools:5` dependency, as the bug report states (it is used during build).

After bump, removed old version (unstable only) and unused patches.

2021-05-28 14:52 UTC, arthurzam commented
bump

2021-07-29 05:55 UTC, mgorny requested changes

2021-07-29 05:55 UTC, mgorny commented on app-editors/juffed/juffed-0.10_p20200103.ebuild
> +S="${WORKDIR}/Mezomish-${PN}-74ab723"
How about replacing the inline short commit id with cutting it out of `${COMMIT}`?

2021-07-29 05:55 UTC, mgorny commented on app-editors/juffed/juffed-0.10_p20200103.ebuild
> +SRC_URI="https://github.com/Mezomish/${PN}/archive/${COMMIT}.tar.gz -> ${P}.tar.gz"
Please inline the PN here.

2021-07-29 05:55 UTC, mgorny commented on app-editors/juffed/juffed-0.10_p20200103.ebuild
> +HOMEPAGE="http://juffed.com/en/"
Probably worth including the github repo URL for convenience.

2021-07-29 05:55 UTC, mgorny commented on app-editors/juffed/juffed-0.10_p20200103.ebuild
> +IUSE="debug"
Where is it being used?

2021-08-01 21:22 UTC, mgorny commented
GitHub doesn't seem to like you:

```
!!! Fetched file: juffed-0.10_p20200103.tar.gz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      1628731
!!! Expected: 1628670
```

2021-08-02 04:24 UTC, arthurzam commented
> GitHub doesn't seem to like you:
> 
> ```
> !!! Fetched file: juffed-0.10_p20200103.tar.gz VERIFY FAILED!
> !!! Reason: Filesize does not match recorded size
> !!! Got:      1628731
> !!! Expected: 1628670
> ```

I refetched the archive, and hope it would be the same at your side. Else, we have a problem.
Thanks for noting it.

2021-08-02 05:49 UTC, mgorny commented
```
 * ERROR: app-editors/juffed-0.10_p20200103::gentoo failed (prepare phase):
 *   The source directory '/tmp/portage/app-editors/juffed-0.10_p20200103/work/Mezomish-juffed-74ab723' doesn't exist
```

Told you that commit id stripping looks suspicious to me. Didn't you have local snapshot or sth?

2021-08-02 06:40 UTC, closed without merging