gtk2removal
gentoo/gentoo pull request #20817
Opened 2021-05-15 13:37 UTC by a17r

2021-05-15 13:55 UTC, SoapGentoo commented on x11-misc/macopix/files/macopix-3.4.0-openssl-1.1.0.patch
> ++++ b/src/http-client.c	2021-05-15 14:41:27.703133114 +0200
remove metadata noise plox

2021-05-15 16:02 UTC, arthurzam commented on games-strategy/freeciv/freeciv-2.6.4.ebuild
> +		rm -f "${ED}"/usr/share/man/man6/freeciv-xaw*
missing `|| die`

2021-05-15 16:04 UTC, arthurzam commented on games-strategy/freeciv/freeciv-2.6.4.ebuild
> +		rm -f "${ED}"/usr/share/man/man6/freeciv-xaw*
missing `|| die`

2021-05-18 11:45 UTC, NP-Hardass requested changes
NAK from me.  I'm OK with the core change to remove the gtk3 USE flag, EAPI=7 and the change regarding the .desktop files, but there is no reason to change the ebuild style throughout.  Gentoo policy, unless it has changed, is to not change another developer's style unnecessarily when working on their ebuilds. 
Leave COMMON_DEPEND, src_unpack as is, and don't monkey with PV comparisons unnecessarily, and I'd be OK with the other changes

2021-05-18 12:22 UTC, a17r commented
> Leave COMMON_DEPEND

@NP-Hardass That makes no sense. Please look at it again, and if you don't know what `BDEPEND` is, read EAPI-7 docs.

2021-05-18 12:26 UTC, NP-Hardass commented
> > Leave COMMON_DEPEND
> 
> @NP-Hardass That makes no sense. Please look at it again, and if you don't know what `BDEPEND` is, read EAPI-7 docs.

COMMON_DEPEND is being used in DEPEND and RDEPEND, not BDEPEND.  Makes absolute sense.  Only thing BDEPEND does is split out build time runtime deps... COMMON_DEPEND, as I'm using it, is for dependencies shared between DEPEND and RDEPEND, so that I don't have to deal with figuring out if a dep is misshared between DEPEND and RDEPEND when I come across a DEPEND=${RDEPEND} or vice versa.

Makes complete sense.  Please look at it again.

2021-05-18 12:29 UTC, a17r commented
So you want me to keep a completely useless `COMMON_DEPEND`. Fine, but that's completely unusual, I just wanted that on the record.

2021-05-18 12:35 UTC, NP-Hardass commented
> So you want me to keep a completely useless `COMMON_DEPEND`. Fine, but that's completely unusual, I just wanted that on the record.

I try, when possible, to use a similar style in all my ebuilds.  Just makes it easier to deal with.  So, if it means that occasionally a COMMON_DEPEND is superfluous, I'm OK with that as long as it makes the dependencies easier to think about across the board.

Make sense?

2021-05-30 19:55 UTC, a17r commented
Keeping a useless COMMON_DEPEND is on the same level as MY_P etc. - it is just adding clutter when it serves no purpose (as it is 90% of the time).

But I do as you please.

2021-05-30 21:11 UTC, merged