dev-libs/libcec: Fix udev rule and support python 3.9
gentoo/gentoo pull request #20851
Opened 2021-05-17 11:24 UTC by alanswanson

Also change udev rule to set group ownership to "video" instead of "uucp" as matches common usage and group membership, typically Kodi or other media player.

Closes: https://bugs.gentoo.org/765358
Closes: https://bugs.gentoo.org/788742
Signed-off-by: Alan Swanson <reiver@improbability.net>

2023-04-02 16:31 UTC, ceamac commented
Hi!

This package became maintainer-needed a long time ago, but was still assigned to the previous maintainer.

If you are still interested in this, please update it to EAPI 8 and python 3.11 and append `[please reassign]` to the PR title so it will get assigned to @proxy-maint.

Thank you!

2023-04-26 13:07 UTC, ceamac commented
`[please reassign]` should be appended at the end of the title; I think the Gentoo bot ignores it at the beginning.

2023-04-29 07:45 UTC, ceamac commented
Thanks, I'll review it this evening

2023-04-29 18:03 UTC, ceamac requested changes
Looks good, with only a few minor issues.

With `USE="cubox exynos kernel-cec python tools udev"`

```
 * VDB: detected possibly incorrect RDEPEND (dev-libs/libcec-6.0.2-r1)
 * sys-libs/ncurses:= < 
 *                    > x11-libs/libX11
```

Please check if `sys-libs/ncurses` really is needed (it might be), and please add `x11-libs/libX11` to `RDEPEND` (and check if it is needed with certain USE flags or always)

Thank you!

2023-05-01 15:36 UTC, alanswanson commented
Updated ebuild per suggested changes.

> ```
>  * VDB: detected possibly incorrect RDEPEND (dev-libs/libcec-6.0.2-r1)
>  * sys-libs/ncurses:= < 
>  *                    > x11-libs/libX11
> ```

That's inherited from the current ebuild which has implicit dependency for x11-libs/libX11 via x11-libs/libXrandr. Added x11-libs/libX11 to RDEPEND.

> Please check if `sys-libs/ncurses` really is needed (it might be), and please add `x11-libs/libX11` to `RDEPEND` (and check if it is needed with certain USE flags or always)

Actually, no. It supports "curses" not "ncurses" and fails on checking for libcurses per bug https://bugs.gentoo.org/51901. Just removed the dependency.

2023-05-01 16:02 UTC, alanswanson commented on dev-libs/libcec/libcec-6.0.2-r1.ebuild
> +	use python && python_optimize "${D}$(python_get_sitedir)"
Had to revert this suggestion as caused QA failure; _DoublePrefixInPath ${ED}$(python_get_sitedir): concatenates two paths containing EPREFIX on line: 113_

2023-05-02 08:22 UTC, ceamac approved these changes
Great!

Thank you!

2023-05-02 08:24 UTC, closed without merging