dev-games/aseprite: fix #680060
gentoo/gentoo pull request #20917
Opened 2021-05-21 22:32 UTC by winterheart

Shared libloadpng comes with shared allegro[png]. USE=bundled-libs will
disable allegro dependency, which leads to building error.

Closes: https://bugs.gentoo.org/680060
Package-Manager: Portage-3.0.18, Repoman-3.0.2
Signed-off-by: Azamat H. Hackimov <azamat.hackimov@gmail.com>

2021-05-22 20:30 UTC, a17r requested changes
What about "Fix unused CMake var" instead of just #bugno in git summary.

2021-05-22 22:42 UTC, winterheart commented
Because "unused CMake var" is not cause of error.

2021-05-22 22:56 UTC, ionenwks commented
Set something appropriate then, the point was that the summary should shortly describe what it's fixing while the bugref be left in the message's body.

2021-05-23 00:13 UTC, winterheart commented
I got super-descriptive summary in commit.

2021-05-23 07:41 UTC, a17r commented
That's very good, but doesn't let you get away with just a number for the summary. `git log` does not look that way either, we're humans communicating in words not numbers.

2021-05-23 14:21 UTC, winterheart commented
Done.

2021-05-23 16:27 UTC, a17r reviewed
Thanks for fixing, this is ready for merge now. Unfortunately building with USE=bundled-libs got us a new error: https://bugs.gentoo.org/791682

2021-05-23 16:53 UTC, closed without merging