media-gfx/gimp: Make X11 optionnal
gentoo/gentoo pull request #20920
Opened 2021-05-22 02:59 UTC by lanodan

Sadly it looks like aqua/quartz/Cocoa detection is automagic on GTK+ target.

    echo `pkg-config --variable=targets gtk+-3.0` | grep quartz

Signed-off-by: Haelwenn (lanodan) Monnier <contact@hacktivis.me>

2021-05-24 12:30 UTC, band-a-prend commented
I certainly require to fully review 2.99.x and 9999 again because the `configure.ac` has no `--with-x` or `--with_x` option and in `configure` file (that should be regenerated) such option is mentioned as "obsolete". and add some X include/libraries.

The `--with_xmc` seems only add Xorg cursor support. And `aqua` USE maybe even could be drop if use `X` will be added.

Sorry, I need some additional time for this before I could review pull request.

2021-06-15 06:38 UTC, juippis commented
@band-a-prend what's the status on this one?

2021-06-15 21:36 UTC, band-a-prend commented
I cant' understand if `--with-x` option is affects something as I build gimp-2.99.6 without it and gimp launched in my xorg-server KDE session. I never tried to run wayland session.
But anyway after proposed update (after some small request fixes including 9999.ebuild) it possible to allow user to disable `libXcursor` dependency installation that only add additional X11 Mouse Cursor support.

2021-06-15 22:04 UTC, band-a-prend requested changes

2021-06-15 22:04 UTC, band-a-prend commented on media-gfx/gimp/gimp-9999.ebuild
> +		$(use_with X xmc)
As well please add to the end of `src_install()` section like in `gimp-2.99.6.ebuild`:
```
	if use doc; then
		mkdir "${ED}/usr/share/gtk-doc/html/gimp3_g-ir-docs" || die
		cp -r "${S}/devel-docs/g-ir-docs/html/"{gjs,python} "${ED}/usr/share/gtk-doc/html/gimp3_g-ir-docs/" || die
	fi
```

2024-07-04 18:54 UTC, eli-schwartz commented
In commit 1bcaafc79ff6b55d1b3c1e9f290cf6d309e91045 (from 2022).

> The USE="X" adds conditional support of x11-libs/libXcursor.

This PR is no longer needed. Sorry it didn't get handled earlier than it did, though. ;)

2024-07-04 18:54 UTC, closed without merging