app-crypt/nwipe, media-gfx/chafa & sys-devel/bmake version bumps
gentoo/gentoo pull request #21625
Opened 2021-07-13 13:51 UTC by jsmolic

2021-07-13 19:18 UTC, SoapGentoo requested changes

2021-07-13 19:18 UTC, SoapGentoo commented on media-gfx/chafa/chafa-1.6.1.ebuild
> +		--disable-static \
remove (EAPI 8)

2021-07-13 21:34 UTC, jsmolic commented on media-gfx/chafa/chafa-1.6.1.ebuild
> +		--disable-static \
done

2021-07-18 09:34 UTC, SoapGentoo approved these changes

2021-07-18 11:06 UTC, closed without merging