mail-filter/bogofilter: removed wrong license
gentoo/gentoo pull request #21622
Opened 2021-07-13 06:17 UTC by scardracs

Package-Manager: Portage-3.0.20, Repoman-3.0.3
Signed-off-by: Marco Scardovi <marco@scardovi.com>

2021-07-13 06:28 UTC, thesamesam requested changes

2021-07-13 06:28 UTC, thesamesam commented on mail-filter/bogofilter/bogofilter-1.2.5-r1.ebuild
> +LICENSE="GPL-3+ CC-BY-ND-3.0"
This still has the wrong licence? Anyway, I’d just git mv the bad ebuild and fix it in one commit?

2021-07-15 11:24 UTC, juippis reviewed
I don't think a revbump is required for this change...

2021-07-15 11:34 UTC, scardracs commented
> I don't think a revbump is required for this change...

Done

2021-07-15 11:35 UTC, juippis approved these changes
Thanks!

2021-07-15 11:36 UTC, closed without merging