dev-util/hip: bump version to 4.2.0
gentoo/gentoo pull request #21655
Opened 2021-07-15 15:20 UTC by littlewu2508

Update hip-3.5.1-config-cmake-in.patch to 4.2.0
lpl_ca removed, so hip-3.9.0-lpl_ca-add-include.patch not used

Package-Manager: Portage-3.0.20, Repoman-3.0.3
Signed-off-by: Yiyang Wu <xgreenlandforwyy@gmail.com>

2021-07-15 15:45 UTC, heroxbd commented
Thanks for the pull request!

A new hip-4.2.0-config-cmake-in.patch is added.  Please add some
explanations in it referring to

  https://wiki.gentoo.org/wiki/User:Veremit/Patch_format

Benda

2021-08-12 08:53 UTC, littlewu2508 commented
@heroxbd  hip-4.2.0 ebuild is ready. Sandbox violation issue fixed, and some cleaning work in hip-4.1.0 and hip-4.1.0-r1 is inherited as well. Please review the changes, thanks.

2021-08-12 15:02 UTC, heroxbd requested changes

2021-08-12 15:02 UTC, heroxbd commented on dev-util/hip/files/hip-4.2.0-config-cmake-in.patch
> +diff --color -uprN orig/hip-config.cmake.in HIP-rocm-4.2.0/hip-config.cmake.in
I know this is adopted from hip-3.5.1-config-cmake-in.patch, but please also add a patch header to explain the logic behind it.

2021-08-13 05:08 UTC, closed without merging

2021-08-13 05:29 UTC, thesamesam commented
Note that the CI is red on the PR so the issue with dev-util/roctracer is now in the tree too. Could you have a look at it please? Thanks!

2021-08-13 05:56 UTC, littlewu2508 commented
> Note that the CI is red on the PR so the issue with dev-util/roctracer is now in the tree too. Could you have a look at it please? Thanks!

There is a circular dependency in hip and roctracer: roctracer depend on hip, while hip[profile] depend on roctracer. In my local development branch I've upgraded both versions and pass the QA check. So should I push roctracer-4.2 together in this PR?

2021-08-13 07:05 UTC, heroxbd commented
> Note that the CI is red on the PR so the issue with dev-util/roctracer is now in the tree too. Could you have a look at it please? Thanks!

Sorry I have missed the CI report.  Will roll out a solution ASAP