*/*: install {bash, fish, zsh}-completion files unconditionally
gentoo/gentoo pull request #21696
Opened 2021-07-18 03:46 UTC by thesamesam

QA policy [0] says that we don't conditionalise installation of
small files. It's a wasteful rebuild and inconsistent across packages
for when users desire completions to be available.

[0] https://projects.gentoo.org/qa/policy-guide/installed-files.html#pg0301
Signed-off-by: Sam James <sam@gentoo.org>

2021-07-30 23:47 UTC, SoapGentoo requested changes

2021-07-30 23:47 UTC, SoapGentoo commented on gui-wm/sway/sway-9999.ebuild
>  		"-Dwerror=false"
remove this pointless and ugly quotes?

2021-07-30 23:47 UTC, SoapGentoo commented on app-misc/tmux-xpanes/tmux-xpanes-4.1.2-r1.ebuild
> +	doins completion/zsh/*
```suggestion
	doins -r completion/zsh/.
```

2021-07-30 23:47 UTC, SoapGentoo commented on app-misc/khard/khard-0.17.0-r1.ebuild
> +}
`distutils_enable_tests setup.py` after `*DEPEND`?

2021-07-30 23:47 UTC, SoapGentoo commented on app-misc/khard/khard-0.13.0-r1.ebuild
> +}
`distutils_enable_tests setup.py` after `*DEPEND`?

2021-07-31 00:08 UTC, SoapGentoo approved these changes

2021-07-31 00:47 UTC, thesamesam commented
All done!

2021-07-31 00:47 UTC, closed without merging