dev-games/recastnavigation: version bump
gentoo/gentoo pull request #21930
Opened 2021-08-09 17:30 UTC by DarthGandalf

2021-08-12 08:32 UTC, SoapGentoo requested changes

2021-08-12 08:32 UTC, SoapGentoo commented on dev-games/recastnavigation/recastnavigation-1.5.1_p20210305.ebuild
> +	append-cppflags "-I${ESYSROOT}/usr/include/catch2"
do this in `src_configure`

2021-08-12 09:48 UTC, DarthGandalf commented on dev-games/recastnavigation/recastnavigation-1.5.1_p20210305.ebuild
> +	append-cppflags "-I${ESYSROOT}/usr/include/catch2"
Done

2021-08-16 08:27 UTC, juippis approved these changes

2021-08-16 08:27 UTC, juippis commented on dev-games/recastnavigation/recastnavigation-1.5.1_p20210305.ebuild
> +	append-cppflags "-I${ESYSROOT}/usr/include/catch2"
Wonder if `use test && ...` is more correct here. Well doesn't seem to break anything regardless. Thanks!

2021-08-16 08:30 UTC, closed without merging