metadata/install-qa-check.d: add 60libtool-la (check for unnecessary …
gentoo/gentoo pull request #22737
Opened 2021-10-28 09:06 UTC by thesamesam

….la files)

Signed-off-by: Sam James <sam@gentoo.org>

2021-11-02 18:37 UTC, mgorny commented
Well, to be honest I think it'd be better if you check for files with matching names, i.e. complain for every `.la` that doesn't come with matching `.a`.

2021-11-06 07:44 UTC, mgorny requested changes

2021-11-06 07:44 UTC, mgorny commented on metadata/install-qa-check.d/60libtool-la
> +		base=$(basename ${file})
Don't call external tools when you can do it via variable substitution.

2021-11-06 07:44 UTC, mgorny commented on metadata/install-qa-check.d/60libtool-la
> +		base=${base/.la/}
```suggestion
		base=${base%.la}
```

You don't expect `.la` in middle of the name, do you?

2022-05-13 19:18 UTC, thesamesam commented
Merged a little while ago.

2022-05-13 19:18 UTC, closed without merging