WIP: allow systemd-networkd to set hostname without polkit
gentoo/gentoo pull request #22792
Opened 2021-11-01 23:40 UTC by gyakovlev

@floppym as discussed on irc.

still WIP, not tested, just opening for visibility and initial feedback.
ofc it'll require a bit of keywording on dbus-broker, new GID assignement and flag masking and better comments, but later with that.
just drafting systemd change here.

not sure if it's ok to use `systemd_get_systemunitdir` here.

2021-11-02 21:09 UTC, floppym requested changes
This looks reasonable.

You'll need to add a USE flag description to metadata.xml.

2021-11-02 21:09 UTC, floppym commented on sys-apps/systemd/systemd-9999.ebuild
> +		insinto "$(systemd_get_systemunitdir)"/systemd-hostnamed.service.d/
Use `${rootprefix}/lib/systemd/system` in place of `$(systemd_get_systemunitdir)`

2021-11-02 23:27 UTC, gyakovlev commented
Ok I seems to have covered all formalities around, including `GID` so I remove WIP status.
Testing, still not ready to merge until I test more.

2021-11-07 00:02 UTC, gyakovlev commented
tested

as expected networkd can now set hostname.

from system without workaround:
```
 systemctl status systemd-networkd
● systemd-networkd.service - Network Configuration
     Loaded: loaded (/lib/systemd/system/systemd-networkd.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2021-07-23 07:58:46 PDT; 3 months 15 days ago
TriggeredBy: ● systemd-networkd.socket
       Docs: man:systemd-networkd.service(8)
   Main PID: 1638 (systemd-network)
     Status: "Processing requests..."
      Tasks: 1 (limit: 37644)
     Memory: 1.7M
        CPU: 38.382s
     CGroup: /system.slice/systemd-networkd.service
             └─1638 /lib/systemd/systemd-networkd

Jul 23 07:58:45 honeycomb systemd[1]: Starting Network Configuration...
Jul 23 07:58:46 honeycomb systemd-networkd[1638]: Enumeration completed
Jul 23 07:58:46 honeycomb systemd[1]: Started Network Configuration.
Jul 23 07:58:46 honeycomb systemd-networkd[1638]: eth0: Link UP
Sep 30 17:51:30 honeycomb systemd-networkd[1638]: eth0: Gained carrier
Sep 30 17:51:31 honeycomb systemd-networkd[1638]: eth0: DHCPv4 address 192.168.1.231/24 via 192.168.1.1
Sep 30 17:51:32 honeycomb systemd-networkd[1638]: Could not set hostname: Access denied
Oct 14 10:07:02 honeycomb systemd-networkd[1638]: docker0: Link UP
```


from system with workaround:

```
● systemd-networkd.service - Network Configuration
     Loaded: loaded (/lib/systemd/system/systemd-networkd.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2021-11-06 16:53:50 PDT; 4min 31s ago
TriggeredBy: ● systemd-networkd.socket
       Docs: man:systemd-networkd.service(8)
   Main PID: 16249 (systemd-network)
     Status: "Processing requests..."
      Tasks: 1 (limit: 154477)
     Memory: 1.1M
     CGroup: /system.slice/systemd-networkd.service
             └─16249 /lib/systemd/systemd-networkd

Nov 06 16:53:53 node systemd-networkd[16249]: eno1: Lost carrier
Nov 06 16:53:53 node systemd-networkd[16249]: bond0: Lost carrier
Nov 06 16:53:54 node systemd-networkd[16249]: eno2: Link UP
Nov 06 16:53:54 node systemd-networkd[16249]: eno1: Link UP
Nov 06 16:53:54 node systemd-networkd[16249]: bridge0: Lost carrier
Nov 06 16:53:59 node systemd-networkd[16249]: eno2: Gained carrier
Nov 06 16:53:59 node systemd-networkd[16249]: bond0: Gained carrier
Nov 06 16:53:59 node systemd-networkd[16249]: eno1: Gained carrier
Nov 06 16:54:20 node systemd-networkd[16249]: bridge0: Gained carrier
Nov 06 16:54:20 node systemd-networkd[16249]: bridge0: DHCPv4 address 192.168.1.206/24 via 192.168.1.1
```

rebased just now.
anything else @floppym ?

2021-11-07 01:25 UTC, floppym approved these changes
Looks good to me.

2021-11-07 05:27 UTC, closed without merging

2021-11-07 05:28 UTC, gyakovlev commented
thanks for checking, merged.

2021-11-13 15:04 UTC, ulm commented
Is there any special reason for using a GID below 100 (other than none other being available)?

2021-11-13 16:32 UTC, floppym commented
No special reason.

2022-03-12 16:55 UTC, Karlson2k commented
It doesn't work unless dbus-broker.service is enabled. By default it is disabled, which results in cryptic errors like:
``` log
Mar 12 14:00:28 dbus-daemon[257]: [system] Failed to activate service 'org.freedesktop.hostname1': timed out (service_start_timeout=25000ms)
Mar 12 14:00:28 systemd-networkd[212]: Could not set hostname: Method call timed out
Mar 12 14:00:33 systemd-hostnamed[273]: Failed to run event loop: Transport endpoint is not connected
Mar 12 14:00:33 systemd[1]: systemd-hostnamed.service: Main process exited, code=exited, status=1/FAILURE
Mar 12 14:00:33 systemd[1]: systemd-hostnamed.service: Failed with result 'exit-code'.
Mar 12 14:00:33 systemd[1]: Failed to start Hostname Service.
```