sci-libs/hipFFT: ROCm FFT marshalling library
gentoo/gentoo pull request #22804
Opened 2021-11-03 13:31 UTC by littlewu2508

hipFFT is the front end of rocFFT, and is dependency of ROCm
supported math/DL frameworks like pytorch.

Package-Manager: Portage-3.0.20, Repoman-3.0.3
Signed-off-by: Yiyang Wu <xgreenlandforwyy@gmail.com>

2021-11-06 04:56 UTC, heroxbd commented
This is new package, have you asked @candrews and @justxi for permissions to put their names into the `metadata.xml`.  Do you want to be the maintainer of this new package?

2021-11-06 10:59 UTC, justxi commented
You can add my name to the metadata.xml.

2021-11-06 11:12 UTC, littlewu2508 commented
> 
> 
> This is a new package, have you asked @candrews and @justxi for permissions to put their names into the `metadata.xml`. Do you want to be the maintainer of this new package?

I should've ask their permissions, especially for hipFFT which seems not in https://github.com/justxi/rocm, So I should put myself into the maintainer list.

2021-11-06 16:56 UTC, heroxbd commented on sci-libs/hipFFT/hipFFT-4.3.0.ebuild
> +	[ -n "${AMDGPU_TARGETS}" ] && mycmakeargs+=( -DAMDGPU_TARGETS="${AMDGPU_TARGETS}" )
New trick please.

2021-11-07 09:59 UTC, heroxbd requested changes
From README.md, 

### Client build dependencies

* The clients (samples, tests etc) included with the hipFFT source
  depend on FFTW, gtest, and boost program-options.

So fftw and boost need to be in BDEPEND when USE=test.

2021-11-07 09:59 UTC, heroxbd commented on sci-libs/hipFFT/hipFFT-4.3.0.ebuild
> +	use test && rmdir rocFFT && ln -s ../rocFFT-rocm-${PV} rocFFT
Should call `|| die` here.

```
if use test; then
    rmdir rocFFT || die
    ln -s ../rocFFT-rocm-${PV} rocFFT || die
fi

2021-11-10 08:27 UTC, heroxbd commented
@littlewu2508 let's remove @candrews 's name from `metadata.xml` for the moment to get this package included.

@candrews feel free to add yourself to the maintainers list in the future.  Thanks!

2021-11-27 10:24 UTC, littlewu2508 commented
> @littlewu2508 let's remove @candrews 's name from `metadata.xml` for the moment to get this package included.
 
Done. I also added my name in the maintainer list.

2021-11-30 06:35 UTC, closed without merging