dev-libs/ntl: update bundled config.guess automatically
gentoo/gentoo pull request #22822
Opened 2021-11-05 11:00 UTC by alexfanqi

upstream version of config.guess and config.sub is a bit outdated. This makes it so that both files get updated to latest in src_unpack.
Signed-off-by: Alex Fan <alexfanqi@yahoo.com>

2021-11-08 08:13 UTC, dlan17 commented
this looks good to me.. @orlitzky can you review this?

2021-11-08 12:06 UTC, AndrewAmmerlaan commented on dev-libs/ntl/ntl-11.4.4.ebuild
> +	gnuconfig_update "$S/libtool-origin/"
```suggestion
	gnuconfig_update "${S}/libtool-origin/"
```

2021-11-08 12:07 UTC, AndrewAmmerlaan commented on dev-libs/ntl/ntl-11.4.4.ebuild
>  DOCS=( "${WORKDIR}/${P}"/README )
This is probably unnecessary because `einstalldocs` automatically installs README

2021-11-08 12:09 UTC, AndrewAmmerlaan commented on dev-libs/ntl/ntl-11.4.4.ebuild
>  DOCS=( "${WORKDIR}/${P}"/README )
Aaah no it isn't, never mind

2021-11-08 12:23 UTC, orlitzky requested changes
This ebuild is marked stable... can you do these changes in an -r1? Otherwise LGTM.

2021-11-09 01:06 UTC, alexfanqi commented
Thanks for taking time to review this. Should I mark all arches as ~ testing in the -r1 ebuild?

2021-11-09 03:37 UTC, closed without merging

2021-11-09 03:39 UTC, orlitzky commented
Merged, thanks!