dev-libs/protobuf: add new version 3.19.1
gentoo/gentoo pull request #22865
Opened 2021-11-08 12:35 UTC by Miezhiko

- dev-libs/protobuf: add new version 3.19.1
 - dev-python/protobuf-python: add 3.19.1

used portage 3.0.28 for testing

2021-11-08 15:39 UTC, arthurzam commented on dev-python/protobuf-python/protobuf-python-3.19.1.ebuild
> +}
We have a more compact way for those, put this one line in global scope before `python_prepare_all`:
`distutils_enable_tests setup.py`

And now you can remove `python_test`

2021-11-08 15:55 UTC, arthurzam requested changes
Thank your contribution.
I'm sorry if the changes list looks long, but let us improve the ebuilds :smile:

Also, please split the commits into 2: one for each package

2021-11-08 15:55 UTC, arthurzam commented on dev-python/protobuf-python/protobuf-python-3.19.1.ebuild
> +KEYWORDS="~alpha amd64 arm ~arm64 ~hppa ~ia64 ~mips ppc ppc64 ~riscv ~sparc x86 ~amd64-linux ~x86-linux ~x64-macos"
Please don't do straight to stable keywords
All arches should be prefixed with `~`

2021-11-08 16:06 UTC, Miezhiko commented
@arthurzam thank you a lot for your feedback, I appreciate your time, attention and fast response.
I will do changes tomorrow.

2021-11-09 10:34 UTC, arthurzam requested changes
Looks much better - excellent work!

Some small last changes.

Also, please sign-off you commits. You can use this command to do it in batch:
`git rebase --exec 'git commit --amend --no-edit -n -s' -i HEAD~2`

2021-11-09 10:34 UTC, arthurzam commented on dev-libs/protobuf/protobuf-3.19.1.ebuild
> +	SRC_URI=""
We can remove this line `SRC_URI`

2021-11-09 10:34 UTC, arthurzam commented on dev-python/protobuf-python/protobuf-python-3.19.1.ebuild
> +	SRC_URI=""
We can remove this line `SRC_URI`

2021-11-09 10:34 UTC, arthurzam commented on dev-python/protobuf-python/protobuf-python-3.19.1.ebuild
> +EAPI=7
Empty line after EAPI

```suggestion
EAPI=7

```

2021-11-09 11:39 UTC, arthurzam requested changes
Uh, about the name in the sign-off:

By [glep-76](https://www.gentoo.org/glep/glep-0076.html), we must use only our real names in the sign-off. I'm not sure, but I think you aren't using it. In case you prefer not to use the real one, we need your confirmation for it.

For easier read, [this one](https://devmanual.gentoo.org/general-concepts/copyright-policy/index.html) might be useful.

In case you decide to use real name, this command will help to edit the commit message:
`git rebase --exec 'git commit --amend' -i HEAD~3`
In any other case, just a reply with explanation/decision will suffice.

---

Ebuilds are good, and tests passed on my testing container. Excellent job!

2021-11-09 11:46 UTC, Miezhiko commented
@arthurzam I don't want to share full name with privacy reason, agree to co-author or fully author-transfer to any developer with granting full authorship but at least mention me in commit message, thought I've got few commits in tree already, would agree to anything to avoid drama.

2021-11-09 11:48 UTC, arthurzam approved these changes
Ok, thank you very much , will merge now :)

2021-11-09 11:52 UTC, closed without merging

2021-11-09 11:56 UTC, Miezhiko commented
@arthurzam please help to move this https://github.com/gentoo/gentoo/pull/22875 PR to be in tree too, I've found that existing OpenCV versions will fail to build with this version of protobuf

2021-11-09 11:58 UTC, arthurzam commented
@Miezhiko 
I can't merge opencv changes as this isn't my package. But I will cap the version for protobuf in current versions in tree. So the breakage won't hit anybody.

2021-11-09 12:11 UTC, Miezhiko commented
Okay, I've rebased my PR.