app-admin/{ansible-cmdb,clustershell}: bump
gentoo/gentoo pull request #22993
Opened 2021-11-18 21:58 UTC by monsieurp

* PYTHON_COMPAT bump (3.9)
* EAPI 8 bump

2021-11-18 21:59 UTC, monsieurp commented
@arthurzam

2021-11-19 05:53 UTC, arthurzam requested changes
Tested in my system and it looks like it builds. I have put some changes that improve quality of ebuild, hope it's OK :smile:

2021-11-19 05:53 UTC, arthurzam commented on app-admin/ansible-cmdb/ansible-cmdb-1.30-r1.ebuild
> +PYTHON_COMPAT=( python3_9 )
Please don't remove python3.8 support if it works
``` suggestion
PYTHON_COMPAT=( python3_{8..9} )
```

2021-11-19 05:53 UTC, arthurzam commented on app-admin/ansible-cmdb/ansible-cmdb-1.30-r1.ebuild
> +	dev-python/setuptools[${PYTHON_USEDEP}]"
setuptools can be removed from DEPEND, it is maintained correctly by the `distfiles-r1.eclass`
```suggestion
```

2021-11-19 05:53 UTC, arthurzam commented on app-admin/clustershell/clustershell-1.8.3-r1.ebuild
> +CDEPEND="dev-python/setuptools[${PYTHON_USEDEP}]"
setuptools can be removed from DEPEND, it is maintained correctly by the `distfiles-r1.eclass`
Then We can remove the `${CDEPEND}`

2021-11-19 05:53 UTC, arthurzam commented on app-admin/clustershell/clustershell-1.8.3-r1.ebuild
> +	test? ( dev-python/nose[${PYTHON_USEDEP}] )"
Please put test dependencies for python world under `BDEPEND` as we support testing only on CHOST.

2021-11-19 17:28 UTC, arthurzam approved these changes
Looks great :smile:
Thank you

2021-11-19 18:25 UTC, closed without merging