net-fstahoe-lafs: Added version 1.17.0 and dependencies
gentoo/gentoo pull request #23204
Opened 2021-12-06 21:53 UTC by jpds

Tested on `amd64`.

2021-12-06 21:57 UTC, thesamesam requested changes

2021-12-06 21:57 UTC, thesamesam commented on dev-python/python-hkdf/python-hkdf-0.3.0.ebuild
> +DEPEND="${RDEPEND}"
- there's a tests.py we can run maybe, and I'd drop blank RDEPEND + DEPEND.
- I'd also consider setting a MY_COMMIT variable for use in SRC_URI + S.
- add BDEPEND="app-arch/unzip" for SRC_URI

2021-12-06 21:57 UTC, thesamesam commented on dev-python/python-spake2/python-spake2-0.8.ebuild
> +RDEPEND="dev-python/python-hkdf"
[${PYTHON_USEDEP}]

2021-12-06 21:57 UTC, thesamesam commented on dev-python/python-spake2/python-spake2-0.8.ebuild
> +RDEPEND="dev-python/python-hkdf"
What about tests? They seem to exist

2021-12-06 21:57 UTC, thesamesam commented on dev-python/python-spake2/python-spake2-0.8.ebuild
> +SRC_URI="https://github.com/warner/${PN}/archive/refs/tags/v${PV}.tar.gz"
-> ${P}.tar.gz (pkgcheck should warn on this, maybe)

2021-12-06 21:57 UTC, thesamesam commented on dev-python/pyutil/pyutil-3.3.0.ebuild
> +DEPEND="dev-python/setuptools[${PYTHON_USEDEP}]"
BDEPEND

2021-12-06 21:57 UTC, thesamesam commented on dev-python/pyutil/pyutil-3.3.0.ebuild
> +IUSE=""
drop

2021-12-06 21:57 UTC, thesamesam commented on dev-python/pyutil/pyutil-3.3.0.ebuild
> +PYTHON_COMPAT=( python3_{7,8,9} )
py3.7 doesn't do anything in Gentoo anymore, eclass drops it

2021-12-06 21:57 UTC, thesamesam commented on dev-python/pyutil/pyutil-3.3.0.ebuild
> +SRC_URI="mirror://pypi/p/pyutil/pyutil-${PV}.tar.gz"
could use the fancy ${P} stuff that other ebuilds use, but this is fine too

2021-12-06 21:57 UTC, thesamesam commented on dev-python/pyutil/pyutil-3.3.0.ebuild
> +	rm -rf "${ED%/}"/usr/share/doc/${PN}
|| die on external commands which may fail, also just do "${ED}". it's not an issue in newer EAPIs

2021-12-06 21:57 UTC, thesamesam commented on dev-python/txtorcon/Manifest
> +EBUILD txtorcon-21.1.0.ebuild 1796 BLAKE2B badcf2e059b121f9e18502623f6c047db2039527824a025363957c6688212d92ff7aef9063a1af82168b93f21e962c734664218aa48bb14c76287b88a4f6a8b1 SHA512 dfcaf70ac9ffb3a274e7
need to fix manifests / use thin-manifests in your overlay (it's not necessary with git really)

2021-12-06 21:57 UTC, thesamesam commented on dev-python/zfec/zfec-1.5.5.ebuild
> +"
bdepend for setuptools, but just use the eclass variable instead of putting it in RDEPEND + *DEPEND?

2021-12-06 21:57 UTC, thesamesam commented on dev-python/zfec/zfec-1.5.5.ebuild
> +	rm -rf "${ED%/}"/usr/share/doc/${PN}
die, "${ED}"

2021-12-06 21:57 UTC, thesamesam commented on net-fs/tahoe-lafs/tahoe-lafs-1.17.0.ebuild
> +DEPEND="dev-python/setuptools[${PYTHON_USEDEP}]"
BDEPEND but see other eclass comments

2021-12-06 21:57 UTC, thesamesam commented on net-fs/tahoe-lafs/tahoe-lafs-1.17.0.ebuild
> +DEPEND="dev-python/setuptools[${PYTHON_USEDEP}]"
.. oh you're already setting it. perfect!

2021-12-06 21:57 UTC, thesamesam commented on net-misc/magic-wormhole/magic-wormhole-0.12.0.ebuild
> +distutils_enable_tests setup.py
try --install.

also, if it works on later instsalls, may imply it's not testing against the new copy but the system copy

2021-12-06 21:57 UTC, thesamesam commented on net-misc/magic-wormhole/magic-wormhole-0.12.0.ebuild
> +	test? ( dev-python/mock
[${PYTHON_USEDEP}]

2021-12-06 21:57 UTC, thesamesam commented on net-misc/magic-wormhole/magic-wormhole-0.12.0.ebuild
> +	dev-python/pynacl
[${PYTHON_USEDEP}] for all of these

2021-12-06 21:57 UTC, thesamesam commented on net-misc/magic-wormhole/magic-wormhole-0.12.0.ebuild
> +PYTHON_COMPAT=( python3_{7,8,9} )
-py3.7

2021-12-06 23:09 UTC, thesamesam requested changes

2021-12-06 23:09 UTC, thesamesam commented on dev-python/eliot/eliot-1.13.0.ebuild
> +	py.test || die "Tests fail with ${EPYTHON}"
Can you do distutils_enable_tests instead and drop this + the pytest DEPEND?

(also, use BDEPEND, not DEPEND here).

2021-12-06 23:09 UTC, thesamesam commented on dev-python/eliot/eliot-1.13.0.ebuild
> +PYTHON_COMPAT=( python3_{8,9,10} )
new line after EAPI

2021-12-06 23:09 UTC, thesamesam commented on dev-python/eliot/eliot-1.13.0.ebuild
> +DISTUTILS_USE_SETUPTOOLS=rdepend
this should avoid the need to put setuptools in any *DEPEND, it does it for us

2021-12-06 23:09 UTC, thesamesam commented on dev-python/eliot/eliot-1.13.0.ebuild
> +RESTRICT="!test? ( test )"
drop this if d_e_t pytest works

2021-12-06 23:09 UTC, thesamesam commented on dev-python/eliot/eliot-1.13.0.ebuild
> +IUSE="doc test"
can drop test if d_e_t pytest works, can drop this line entirely if distutils_enable_docs or w/e works

2021-12-06 23:09 UTC, thesamesam commented on dev-python/eliot/eliot-1.13.0.ebuild
> +	py.test || die "Tests fail with ${EPYTHON}"
Oh, we should also do things in the same order as phase execution -- so python_test should be above python_install_all.

2021-12-06 23:09 UTC, thesamesam commented on dev-python/foolscap/foolscap-21.7.0.ebuild
> +DEPEND="dev-python/setuptools[${PYTHON_USEDEP}]
I don't think this part is needed, but check the default behaviour of the eclass

2021-12-06 23:09 UTC, thesamesam commented on dev-python/foolscap/foolscap-21.7.0.ebuild
> +python_test() {
you're defining this phase twice, just delete this copy

2021-12-06 23:09 UTC, thesamesam commented on dev-python/python-spake2/python-spake2-0.8.ebuild
> +BDEPEND="test? ( dev-python/pytest[${PYTHON_USEDEP}] )"
d_e_t does this for us

2021-12-06 23:09 UTC, thesamesam commented on dev-python/python-spake2/python-spake2-0.8.ebuild
> +RESTRICT="!test? ( test )"
d_e_t does this for us

2021-12-06 23:09 UTC, thesamesam commented on dev-python/python-spake2/python-spake2-0.8.ebuild
> +IUSE="test"
d_e_t does this for us

2021-12-06 23:09 UTC, thesamesam commented on dev-python/pyutil/pyutil-3.3.0.ebuild
> +BDEPEND="dev-python/setuptools[${PYTHON_USEDEP}]"
may not be needed, check eclass default / set variable if needed instead(?)

2021-12-06 23:09 UTC, thesamesam commented on dev-python/txtorcon/txtorcon-21.1.0.ebuild
> +python_test() {
new line before python_test, but put this after python_compile_all to match phase order execution.

2021-12-06 23:09 UTC, thesamesam commented on dev-python/txtorcon/txtorcon-21.1.0.ebuild
> +	/usr/bin/trial txtorcon || die "Tests failed with ${EPYTHON}"
"${BROOT}"/usr/bin/trial

2021-12-06 23:09 UTC, thesamesam commented on dev-python/zfec/zfec-1.5.5.ebuild
> +RESTRICT="!test? ( test )"
Should be able to drop these two lines.

2021-12-06 23:09 UTC, thesamesam commented on net-fs/tahoe-lafs/tahoe-lafs-1.17.0.ebuild
> +DEPEND="dev-python/setuptools[${PYTHON_USEDEP}]"
(may stll be able to drop it)

2021-12-06 23:09 UTC, thesamesam commented on net-fs/tahoe-lafs/tahoe-lafs-9999.ebuild
> +DEPEND="dev-python/setuptools[${PYTHON_USEDEP}]"
drop?

2021-12-06 23:09 UTC, thesamesam commented on net-misc/magic-wormhole/magic-wormhole-0.12.0.ebuild
> +IUSE="test"
d_e_t should do this for us

2021-12-06 23:09 UTC, thesamesam commented on net-misc/magic-wormhole/magic-wormhole-0.12.0.ebuild
> +DEPEND="
BDEPEND

2021-12-07 08:35 UTC, thesamesam commented on dev-python/txtorcon/txtorcon-21.1.0.ebuild
> +	test? ( dev-python/mock[${PYTHON_USEDEP}] )
BDEPEND

2021-12-07 08:35 UTC, thesamesam commented on dev-python/txtorcon/txtorcon-21.1.0.ebuild
> +	${RDEPEND}
FYI: we usually don't need to do DEPEND="${RDEPEND}" (or BDEPEND=...) for python stuff, it usually only needs it at runtime, but if it checks at build time, i guess it's worth just requring it

2021-12-07 08:35 UTC, thesamesam commented on dev-python/txtorcon/txtorcon-21.1.0.ebuild
> +PYTHON_COMPAT=( python3_{8,9,10} )
new line after EAPI

2021-12-07 08:35 UTC, thesamesam commented on dev-python/python-hkdf/python-hkdf-0.3.0.ebuild
> +S="${WORKDIR}/${PN}-ba0e2eee8f50cc84706f816dbc57897319e2250c"
I'd put this a line above, use a ${MY_COMMIT} variable

2021-12-07 08:35 UTC, thesamesam commented on dev-python/foolscap/foolscap-21.7.0.ebuild
> +		for i in ./*.rst
nit: I'd do: for i in ./*.rst; do

2021-12-07 08:35 UTC, thesamesam commented on dev-python/foolscap/foolscap-21.7.0.ebuild
> +			rst2html.py $i > ./build/${i/rst/html} || die
${i}

2021-12-07 08:35 UTC, thesamesam commented on dev-python/foolscap/foolscap-21.7.0.ebuild
> +		popd > /dev/null
|| die

2021-12-07 08:35 UTC, thesamesam commented on dev-python/foolscap/foolscap-21.7.0.ebuild
> +		pushd doc > /dev/null
|| die

2021-12-07 08:35 UTC, thesamesam commented on dev-python/foolscap/foolscap-21.7.0.ebuild
> +	local i;
drop ;

2021-12-07 08:35 UTC, thesamesam commented on dev-python/foolscap/foolscap-21.7.0.ebuild
> +EAPI=7
new line after EAPI

2024-07-16 03:51 UTC, eli-schwartz requested changes
Some of these are misnamed -- dev-python/* should generally be named the same as the PyPI name.

magic-wormhole was added by someone else in 2023 -- to dev-python actually.

2024-07-16 03:53 UTC, eli-schwartz commented
I think if remaining packages are desired they should be introduced in a new PR at this point.

2024-07-16 03:53 UTC, closed without merging