julia-1.7.0 ebuild
gentoo/gentoo pull request #23532
Opened 2021-12-26 22:50 UTC by dzejej

The ebuild for julia 1.7.0 with patches. Pacthes come from Arch linux
exept julia-turnoff-patchelf.patch.

2021-12-26 22:56 UTC, thesamesam commented
Please add a link to the top of each patch for where you got it from (possibly more links if there's any upstream commits / bugs to reference). Also add an explanation of why it's needed/what it does where it's not obvious.

Please also use repoman commit / pkgdev commit to get the commit message right and include [signoff](https://wiki.gentoo.org/wiki/Gentoo_git_workflow#Signoff). Thank you!

2021-12-27 05:30 UTC, anaveragehuman commented
Hi! I usually submit PRs for this package but have been busier than usual this release cycle and was stuck on some strange part of their build system. On top of Sam's suggestions please also make sure the build is successful with `FEATURES=network-sandbox`.

2021-12-27 18:00 UTC, dzejej commented
Sorry for pushing julia-1.7.0  twice.

2021-12-30 20:58 UTC, mattst88 requested changes
Please give patches appropriate names. E.g. instead of `dev-lang/julia: julia-1.7.1` it could be `dev-lang/julia: Version bump to 1.7.1`. Instead of `dev-lang/julia: ebuild for julia 1.7.0` it could be `dev-lang/julia: Document source of patches` or something like that.

2021-12-30 20:58 UTC, mattst88 commented on dev-lang/julia/files/julia-hardcoded-libs-1.7.0.patch
> +This pacth comes from:
typo: patch

2021-12-30 20:58 UTC, mattst88 commented on dev-lang/julia/files/julia-llvm13-fix_A.patch
> +but reference comes form ARCH Linux juia package
typos: from, julia

2021-12-30 20:58 UTC, mattst88 commented on dev-lang/julia/files/julia-llvm13-fix_B.patch
> +but reference comes form ARCH Linux juia package
typos: from, julia

2021-12-30 20:58 UTC, mattst88 commented on dev-lang/julia/files/julia-make-install-no-build.patch
> +This pacth comes from
typo: patch

2021-12-30 20:58 UTC, mattst88 commented on dev-lang/julia/files/julia-turnoff-patchelf.patch
> +This patch turn off patching the binary files by patchelf.
mistake: 'turn' should be 'turns'

2021-12-30 20:58 UTC, mattst88 commented on dev-lang/julia/files/julia-turnoff-patchelf.patch
> +On my system (gentoo stable and updated) with patching causes
I don't know what this is saying. Did the sentence end too early?

2021-12-30 20:58 UTC, mattst88 commented on dev-lang/julia/julia-1.7.0.ebuild
> +	# Allow use LLVM 13
I think this comment is kind of unnecessary.

2022-01-03 22:24 UTC, closed without merging