media-gfx/gif2png: bump version to 3.0.0
gentoo/gentoo pull request #23622
Opened 2022-01-01 19:36 UTC by kernlpanic

Closes: https://bugs.gentoo.org/724518
Package-Manager: Portage-3.0.28, Repoman-3.0.3
Signed-off-by: Dennis Eisele <mail@dennis-eisele.de>

2022-01-02 03:14 UTC, thesamesam requested changes

2022-01-02 03:14 UTC, thesamesam commented on media-gfx/gif2png/gif2png-3.0.0.ebuild
> +	go mod init gif2png
Always need a `|| die` on (external) commands which may fail, `cd` counts here too.

2022-01-02 03:14 UTC, thesamesam commented on media-gfx/gif2png/gif2png-3.0.0.ebuild
> +# EOL; Upstream has rewritten gif2png in Go
This comment at least isn't relevant anymore. Do tests pass now?

2022-01-02 03:14 UTC, thesamesam commented on media-gfx/gif2png/gif2png-3.0.0.ebuild
> +	>=dev-lang/go-1.17.5"
Put go in BDEPEND.

2022-01-02 13:35 UTC, kernlpanic commented
@thesamesam I updated the ebuild accordingly

2022-01-03 00:05 UTC, thesamesam commented
Do you not have ```FEATURES="network-sandbox"``` enabled?

```
>>> Unpacking gif2png-3.0.0.tar.gz to /var/tmp/portage/media-gfx/gif2png-3.0.0/work
>>> Source unpacked in /var/tmp/portage/media-gfx/gif2png-3.0.0/work
/var/tmp/portage/media-gfx/gif2png-3.0.0/work/gif2png-3.0.0 /var/tmp/portage/media-gfx/gif2png-3.0.0/work
/var/tmp/portage/media-gfx/gif2png-3.0.0/work
>>> Preparing source in /var/tmp/portage/media-gfx/gif2png-3.0.0/work/gif2png-3.0.0 ...
go: creating new go.mod: module gif2png
go: to add module requirements and sums:
	go mod tidy
go get: module golang.org/x/crypto/ssh/terminal: Get "https://proxy.golang.org/golang.org/x/crypto/ssh/terminal/@v/list": dial tcp [2a00:1450:400b:c01::8d]:443: connect: network is unreachable
 * ERROR: media-gfx/gif2png-3.0.0::gentoo failed (prepare phase):
 *   failed to get terminal package
 *
 * Call stack:
 *     ebuild.sh, line 127:  Called src_prepare
 *   environment, line 1256:  Called die
 * The specific snippet of code:
 *       go get golang.org/x/crypto/ssh/terminal || die "failed to get terminal package";
```

2022-02-01 07:36 UTC, juippis commented
So that ^ error looks like upstream doesn't package required go modules, but instead depend on getting them via network while building. Please see other go-module ebuilds how it's handled, also, you can package / ask upstream to package the modules. Some upstreams do that.

Although I haven't checked the upstream build system for this one, all the above is just guesswork. 

Let us know if you need more help and we'll dig into it!

2022-02-18 02:57 UTC, thesamesam commented
Let's close for now (as per discussion on IRC) pending resolution of the upstream bug: https://gitlab.com/esr/gif2png/-/issues/14

2022-02-18 02:57 UTC, closed without merging