dev-python/jupyter_server: enable doc generation
gentoo/gentoo pull request #23915
Opened 2022-01-22 18:13 UTC by arthurzam

2022-01-22 21:08 UTC, mgorny requested changes
Plz PEP517 all the new packages.

2022-01-22 21:08 UTC, mgorny commented on dev-python/black/black-21.12_beta0-r1.ebuild
> +# Copyright 2020-2022 Gentoo Authors
Plz do PEP517 here while you're revbumping it.

2022-01-22 21:08 UTC, mgorny commented on dev-python/sphinxemoji/sphinxemoji-0.2.0.ebuild
> +PYTHON_COMPAT=( python3_{8..10} )
Any reason not to use PEP517 here?

2022-01-23 18:50 UTC, arthurzam commented
Thanks, done and merged!

2022-01-23 18:50 UTC, closed without merging