x11-terms/cool-retro-term: Bump to 1.2.0 and 9999 version Ebuild
gentoo/gentoo pull request #24550
Opened 2022-03-14 07:43 UTC by ThamognyaKodi

Changes:
- added 1.2.0 version ebuild
- added 9999 version ebuild
- Added Manifest updates
- Requesting to be a proxy-maint or proxy-maintainer or maintainer for this package `x11-terms/cool-retro-term`

Signed-off-by: Thamognya Kodi <contact@thamognya.com>

2022-03-14 08:44 UTC, ConiKost requested changes

2022-03-14 08:44 UTC, ConiKost commented on x11-terms/cool-retro-term/cool-retro-term-1.2.0-r2.ebuild
> +# Copyright 2022 Gentoo Authors
What about existing copyright, which is present in old ebuild?

2022-03-14 08:44 UTC, ConiKost commented on x11-terms/cool-retro-term/cool-retro-term-1.2.0-r2.ebuild
> +IUSE=""
If empty, drop it.

2022-03-14 08:44 UTC, ConiKost commented on x11-terms/cool-retro-term/cool-retro-term-1.2.0-r2.ebuild
> +	rmdir ${WORKDIR}/${P}/${QTW_PN}
Missing ```|| die```.

2022-03-14 08:44 UTC, ConiKost commented on x11-terms/cool-retro-term/cool-retro-term-1.2.0-r2.ebuild
> +	mv "${WORKDIR}/${QTW_P}" ${WORKDIR}/${P}/${QTW_PN}
Missing ```|| die```.

2022-03-14 08:44 UTC, ConiKost commented on x11-terms/cool-retro-term/cool-retro-term-1.2.0-r2.ebuild
> +	eapply "${FILESDIR}"/qmltermwidget-0.2.0-gcc-10.patch
Can't be this done through regular ```PATCHES=()``` variable?

2022-03-14 08:44 UTC, ConiKost commented on x11-terms/cool-retro-term/cool-retro-term-1.2.0-r2.ebuild
> +	eqmake5 PREFIX="/usr/bin"
Prefix shouldn't be hardcoded, use ```${EPREFIX}```.

2022-03-14 08:44 UTC, ConiKost commented on x11-terms/cool-retro-term/cool-retro-term-1.2.0-r2.ebuild
> +	mv "${WORKDIR}/${P}/${PN}" /usr/bin/${PN}
Missing ```|| die```.

2022-03-14 08:44 UTC, ConiKost commented on x11-terms/cool-retro-term/cool-retro-term-1.2.0-r2.ebuild
> +	rm -rf "/usr/bin/${PN}"
He? Why? (And also Missing ```|| die```.)

2022-03-14 09:42 UTC, closed without merging

2022-03-14 09:45 UTC, ThamognyaKodi commented
Thank you for the feedback. I will try to fix it and the. Make another PR.

2022-03-16 14:26 UTC, juippis commented
In future you can just squash your commits and force-push. I see you're already working in a git branch so it should be rather easy.