app-admin/yadm: add 3.2.1
gentoo/gentoo pull request #24678
Opened 2022-03-20 04:56 UTC by ixti

Package-Manager: Portage-3.0.30, Repoman-3.0.3
Signed-off-by: Alexey Zapparov <alexey@zapparov.com>

2022-03-20 04:59 UTC, ixti commented
@gyakovlev please review when you have a time. I've added `DOCS` since last bump:

``` patch
36a37,38
> DOCS=(CHANGES README.md ${PN}.md)
> 
```

2022-03-20 18:53 UTC, arthurzam requested changes
Some small changes :)

2022-03-20 18:53 UTC, arthurzam commented on app-admin/yadm/yadm-3.2.1.ebuild
> +	has_version -b "dev-python/pytest[${PYTHON_USEDEP}]"
Please use the new python way :)
```suggestion
	python_has_version -b "dev-python/pytest[${PYTHON_USEDEP}]"
```

2022-03-20 18:53 UTC, arthurzam commented on app-admin/yadm/yadm-3.2.1.ebuild
> +	sed -i "s@^cache_dir = /tmp@cache_dir = ${TMPDIR}@" pytest.ini || die
We can improve a little the `sed`:
```suggestion
	sed -e "/^cache_dir/s@/tmp@${T}@" -i pytest.ini || die
```

About the tmpdir change. Based on [pms](https://projects.gentoo.org/pms/8/pms.html#x1-10900011.1), it is preferable to use `${T}` over `${TEMPDIR}`

2022-03-20 18:54 UTC, arthurzam commented on app-admin/yadm/yadm-3.2.1.ebuild
> +DOCS=(CHANGES README.md ${PN}.md)
Please with spaces after & before braces

```suggestion
DOCS=( CHANGES README.md ${PN}.md )
```

2022-03-21 03:24 UTC, ixti commented
@arthurzam thank you for the review. Applied your proposals.

2022-03-21 19:55 UTC, closed without merging

2022-03-25 05:55 UTC, gyakovlev commented
@arthurzam thanks for working on it ( and couple other PRs too)
@ixti and thanks for bump. I was away, usually I react faster.

2022-03-25 12:55 UTC, ixti commented
> I was away, usually I react faster.

There was no rush. :D