dev-util/hip: add missing BDEPEND providing GL/glx.h
gentoo/gentoo pull request #24755
Opened 2022-03-26 08:12 UTC by littlewu2508

Previously this is the (build-time) dependency of rocclr, which has
DEPEND="virtual/opengl" to make sure GL/glx.h is present. Now hip-5
bundles rocclr and this BDEPEND shuold be added. Turned out headers
are provided by media-libs/libglvnd

Closes: https://bugs.gentoo.org/836136
Package-Manager: Portage-3.0.30, Repoman-3.0.3
Signed-off-by: Yiyang Wu <xgreenlandforwyy@gmail.com>

2022-03-26 08:19 UTC, heroxbd requested changes

2022-03-26 08:19 UTC, heroxbd commented on dev-util/hip/hip-5.0.2.ebuild
> +BDEPEND="media-libs/libglvnd"
use `virtual/opengl` to align with rocclr.

2022-03-26 08:19 UTC, heroxbd commented
> ... this BDEPEND shuold be added. 

typo

2022-03-27 03:19 UTC, closed without merging

2022-03-27 03:23 UTC, thesamesam commented
Headers should be in DEPEND, not BDEPEND.

2022-03-27 03:24 UTC, heroxbd commented
> 

Good point.  Will do a quick fix.

2022-03-27 03:28 UTC, thesamesam commented
Thank you! (For both that & all the merges of PRs)

2022-03-27 08:29 UTC, littlewu2508 commented
> Headers should be in DEPEND, not BDEPEND, because they must be available:
> 
>     1. in the right location for cross (in (E)SYSROOT)
> 
>     2. may even vary per-architecture

Got it. Thanks for pointing out!