net-misc/electrum: ebuild improvements
gentoo/gentoo pull request #24887
Opened 2022-04-03 22:26 UTC by CyberTailor

2022-04-04 07:09 UTC, mgorny requested changes

2022-04-04 07:09 UTC, mgorny commented on net-misc/electrum/electrum-4.2.1.ebuild
> -inherit desktop distutils-r1 xdg-utils
Nope, xdg hate here.

2022-04-04 07:09 UTC, mgorny commented on net-misc/electrum/electrum-4.2.1.ebuild
> +	distutils-r1_python_prepare_all
Leave it as `src_prepare`, it does the same and it's shorter to type.

2022-04-04 07:09 UTC, mgorny commented on net-misc/electrum/electrum-4.2.1.ebuild
> +	# avoid installing icons and desktop item to wrong location
`the` is still needed.

2022-04-10 03:53 UTC, CyberTailor commented
Addressed all mentioned issues.

2022-05-14 13:31 UTC, blueness commented
Sorry this one fell of my desk.  electrum has now been bumped to 4.2.1-r1.  If you want to update your PR I can apply it.

2022-05-19 02:14 UTC, thesamesam commented
@CyberTailor please rebase when you get a chance, thanks

2023-01-07 12:38 UTC, closed without merging