app-misc/cadubi: version bump (1.3.3)
gentoo/gentoo pull request #24934
Opened 2022-04-06 18:25 UTC by mm1ke

Hi,

Simple version bump for `app-misc/cadubi`.
This fixes the `HOMEPAGE` to use github, uses `sed` to fix the `help.txt` file and also installs the man page of the application.

Package-Manager: Portage-3.0.30, Repoman-3.0.3
Signed-off-by: Michael Mair-Keimberger <mmk@levelnine.at>

2022-04-11 19:11 UTC, ConiKost requested changes
Could you also bumped directly to ```1.3.4```? Seems via tags available: https://github.com/statico/cadubi/tags

2022-04-11 19:11 UTC, ConiKost commented on app-misc/cadubi/cadubi-1.3.3.ebuild
> +DEPEND="dev-lang/perl
Shouldn't be this ```RDEPEND```? Based on upstreams repo, this seems only normal perl scripts without any compilation involved?

2022-04-16 14:08 UTC, mm1ke commented
> Could you also bumped directly to `1.3.4`? Seems via tags available: https://github.com/statico/cadubi/tags

Updated the ebuild to use `1.3.4`. Also changed it to `RDEPEND`, seems to be a simple perl script for me too.

2022-04-18 21:01 UTC, ConiKost approved these changes

2022-04-18 21:04 UTC, closed without merging