Vim eclasses
gentoo/gentoo pull request #24941
Opened 2022-04-07 11:59 UTC by CyberTailor

2022-04-12 09:01 UTC, thesamesam commented
Please verify any fixable bugs from https://bugs.gentoo.org/buglist.cgi?quicksearch=vim%20eclass&list_id=6106436 are sorted too.

2022-04-12 09:21 UTC, CyberTailor commented
https://bugs.gentoo.org/597304 has been already fixed

2022-04-12 13:38 UTC, floppym requested changes
Most of this looks good.

I can't comment on the actual behavior of the src_prepare function in vim-plugin.eclass since I'm unfamiliar how vim plugin tarballs are typically arranged.

2022-04-13 00:03 UTC, CyberTailor commented on eclass/vim-plugin.eclass
> +if ${_DEFINE_VIM_PLUGIN_SRC_PREPARE}; then
The same check is used in `xdg.eclass`, so I think this is permitted

2022-04-13 00:06 UTC, CyberTailor commented on eclass/vim-plugin.eclass
> +if ${_DEFINE_VIM_PLUGIN_SRC_PREPARE}; then
I noticed that I forgot to `_DEFINE_VIM_PLUGIN_SRC_PREPARE=false`. Fixed in this PR

2022-04-14 02:51 UTC, thesamesam commented on eclass/vim-plugin.eclass
> +if ${_DEFINE_VIM_PLUGIN_SRC_PREPARE}; then
Being used elsewhere doesn't mean it's a good pattern. I'd go with what floppym suggested.

2022-04-14 03:07 UTC, CyberTailor commented on eclass/vim-plugin.eclass
> +if ${_DEFINE_VIM_PLUGIN_SRC_PREPARE}; then
ok, fixed

2022-04-23 19:56 UTC, laumann commented
\o/

2022-05-30 12:57 UTC, closed without merging