Bump dev-util/conan
gentoo/gentoo pull request #25061
Opened 2022-04-17 11:59 UTC by Kangie

Add 1.47; drop 1.36

2022-04-17 17:49 UTC, winterheart requested changes

2022-04-17 17:49 UTC, winterheart commented on dev-util/conan/conan-1.47.0.ebuild
>  	>=dev-python/jinja-2.10.1[${PYTHON_USEDEP}]
jinja need to be updated to >=dev-python/jinja-3.0

2022-04-18 09:22 UTC, winterheart commented
Looks good for me.

2022-04-23 06:11 UTC, juippis approved these changes

2022-04-23 06:25 UTC, closed without merging