sci-mathematics/octave: revision update and version bump to 7.1.0
gentoo/gentoo pull request #25143
Opened 2022-04-21 12:36 UTC by ThamognyaKodi

- uses bug: 839285 patch
- uses bug: 839285 revision update for 6.4.0-r2
- Bumps version 7.1.0

Signed-off-by: Thamognya Kodi <contact@thamognya.com>

2022-04-23 01:25 UTC, thesamesam requested changes

2022-04-23 01:25 UTC, thesamesam commented on sci-mathematics/octave/octave-7.1.0.ebuild
> +	virtual/pkgconfig
BDEPEND

2022-04-23 01:25 UTC, thesamesam commented on sci-mathematics/octave/octave-7.1.0.ebuild
> +	dev-util/gperf
I think BDEPEND

2022-04-23 01:25 UTC, thesamesam commented on sci-mathematics/octave/octave-7.1.0.ebuild
> +	doc? (
doc => BDEPEND

2022-04-23 01:25 UTC, thesamesam commented on sci-mathematics/octave/octave-7.1.0.ebuild
> +	gui? ( dev-qt/linguist-tools:5 )
BDEPEND

2022-04-23 01:25 UTC, thesamesam commented on sci-mathematics/octave/octave-7.1.0.ebuild
> +	|| ( media-gfx/imagemagick media-gfx/graphicsmagick[imagemagick] )"
BDEPEND

2022-04-23 01:25 UTC, thesamesam commented on sci-mathematics/octave/octave-7.1.0.ebuild
> +pkg_postinst() {
Oh, xdg.eclass instead, maybe?

2022-04-27 23:53 UTC, thesamesam commented on sci-mathematics/octave/files/octave-6.4.0-omit-qtchooser-qtver.patch
> +diff -urNp octave-6.4.0-orig/configure octave-6.4.0-dwok/configure
This is still only patching configure, not configure.ac, which is fragile -- and we're already calling eautoreconf anyway.

Also, given this patch is applied before eautoreconf (which is right), the changes are likely to get blown away, so this does not do anything right now, I think.

Just change it to only patch configure.ac then test it.

2022-04-27 23:53 UTC, thesamesam commented on sci-mathematics/octave/octave-7.1.0.ebuild
> +pkg_postinst() {
...?

2022-04-29 07:09 UTC, vaukai commented on sci-mathematics/octave/octave-7.1.0.ebuild
> +	java? ( >=virtual/jre-1.6.0:* )
java? ( >=virtual/jre-1.8:* )

Same for 6.4.0-r2
See https://wiki.gentoo.org/wiki/Java_Developer_Guide#Dependencies

2022-04-29 07:09 UTC, vaukai commented on sci-mathematics/octave/octave-7.1.0.ebuild
> +	java? ( >=virtual/jdk-1.6.0 )
java? ( >=virtual/jdk-1.8:* )

Same for 6.4.0-r2
See https://wiki.gentoo.org/wiki/Java_Developer_Guide#Dependencies

2022-05-04 23:39 UTC, thesamesam commented
ping

2022-05-05 00:11 UTC, closed without merging