dev-util/radare2: verbump to 5.6.8
gentoo/gentoo pull request #25155
Opened 2022-04-22 10:48 UTC by stkw0

2022-04-22 21:31 UTC, ajakk requested changes

2022-04-22 21:31 UTC, ajakk commented on dev-util/radare2/radare2-5.6.8.ebuild
>  HOMEPAGE="http://www.radare.org"
Looks like it supports HTTPS?

2022-04-22 21:31 UTC, ajakk commented on dev-util/radare2/radare2-5.6.8.ebuild
> +		test? ( https://github.com/radareorg/radare2-testbins/archive/${BINS_COMMIT}.tar.gz -> radare2-testbins-${BINS_COMMIT}.tar.gz )
I think this will still be mirrored despite the `RESTRICT="test"`. In EAPI=8, we can `RESTRICT=fetch` and mark the mirrorable URLs as mirrorable.

2022-04-22 21:35 UTC, ajakk commented on dev-util/radare2/radare2-5.6.8.ebuild
> +		test? ( https://github.com/radareorg/radare2-testbins/archive/${BINS_COMMIT}.tar.gz -> radare2-testbins-${BINS_COMMIT}.tar.gz )
[This](https://github.com/gentoo/gentoo/blob/master/dev-util/rizin/rizin-0.3.4.ebuild#L16) is done in rizin, too.

2022-04-22 21:37 UTC, ajakk commented
Can you throw on the patch for [CVE-2022-1437](https://bugs.gentoo.org/show_bug.cgi?id=831057#c10), too, while at it?

2022-04-22 21:49 UTC, ajakk commented
Oh, also getting this on install:

```
 * QA Notice: Symbolic link /usr/lib64/radare2/last points to /usr/lib64/radare2/5.6.8 which does not exist.
 ```

2022-04-25 06:36 UTC, juippis approved these changes

2022-04-25 06:57 UTC, closed without merging