net-im/profanity: version bump to 0.12.1
gentoo/gentoo pull request #25279
Opened 2022-05-01 18:53 UTC by mrusme

2022-05-01 19:28 UTC, Flowdalic requested changes
Thanks for your contribution. Please fix the missing signoff. Then I'll have a closer look at it.

2022-05-01 19:28 UTC, Flowdalic commented on net-im/profanity/profanity-0.12.1-r1.ebuild
> +EAPI=7
EAPI 8?

2022-05-01 19:28 UTC, Flowdalic commented on net-im/profanity/Manifest
> -DIST profanity-0.9.5.tar.gz 830966 BLAKE2B fc1b755b1a92dbde62aacb31cb5d9190cea951e98501a5b48495dbd31266f343cf436de1fa0f69caec34324cd1f781d0bd4f5f7ebdd984324c5d1d6edb91452a SHA512 79305ee488d3a9b87bb4
Unnecessary change of ordering

2022-05-01 19:44 UTC, mrusme commented
@Flowdalic thank you for the feedback, kindly re-check!

2022-05-02 06:39 UTC, Flowdalic commented
> @Flowdalic thank you for the feedback, kindly re-check!

The 'Signed-off-by:' is on the same line as the commit subject. See https://github.com/gentoo/gentoo/commit/f3ac9ad393dd879ff89174a1ab4bad34596a401f.patch

Please fix this.

2022-05-02 14:54 UTC, closed without merging