dev-db/unixODBC: use confcache
gentoo/gentoo pull request #25736
Opened 2022-06-03 04:31 UTC by thesamesam

Saves about 10s in configure for me.

Signed-off-by: Sam James <sam@gentoo.org>

2022-06-10 07:26 UTC, SoapGentoo requested changes

2022-06-10 07:26 UTC, SoapGentoo commented on media-gfx/graphviz/graphviz-4.0.0.ebuild
> +	java-pkg-opt-2_pkg_setup
get rid of java, don't care anymore

2022-06-10 07:26 UTC, SoapGentoo commented on media-gfx/graphviz/graphviz-4.0.0.ebuild
> +	fi
this whole block is upstreamed, remove

2022-06-10 07:26 UTC, SoapGentoo commented on media-gfx/graphviz/graphviz-4.0.0.ebuild
> +	sed -i -e '/$(pkgluadir)/d' tclpkg/gv/Makefile.am || die
remove

2022-06-10 07:26 UTC, SoapGentoo commented on media-gfx/graphviz/graphviz-4.0.0.ebuild
> +	use java && append-cppflags $(java-pkg_get-jni-cflags)
remove, don't care about java anymore

2022-06-10 07:26 UTC, SoapGentoo commented on media-gfx/graphviz/graphviz-4.0.0.ebuild
> +	eautoreconf
shouldn't be necessary anymore, not patching Makefile.am anymore

2022-06-10 07:26 UTC, SoapGentoo commented on media-gfx/graphviz/graphviz-4.0.0.ebuild
> +		$(use_with examples demos)
append the standard examples dir as the third argument here in here
https://gitlab.com/graphviz/graphviz/-/merge_requests/2668
```suggestion
		$(use_with examples demos '$(docdir)/examples')
```

2022-06-10 07:26 UTC, SoapGentoo commented on media-gfx/graphviz/graphviz-4.0.0.ebuild
> +	einstalldocs
shouldn't be necessary?

2022-06-10 07:26 UTC, SoapGentoo commented on media-gfx/graphviz/graphviz-4.0.0.ebuild
> +	dot -c || die
nix the comment and replace it with
`# we need to register all plugins before they become usable`

2022-06-10 08:06 UTC, thesamesam commented on media-gfx/graphviz/graphviz-4.0.0.ebuild
> +	fi
I thought I'd done those!

2022-06-15 16:06 UTC, SoapGentoo requested changes

2022-06-15 16:06 UTC, SoapGentoo commented on media-gfx/graphviz/graphviz-4.0.0.ebuild
> +IUSE="+cairo devil doc examples gtk2 gts guile lasi lefty nls pdf perl postscript python qt5 ruby svg tcl webp X"
```suggestion
IUSE="+cairo devil doc examples gtk2 gts guile lasi nls pdf perl postscript python qt5 ruby svg tcl webp X"
```
and remove everything dependent on it

2022-06-15 16:11 UTC, SoapGentoo commented on media-gfx/graphviz/graphviz-4.0.0.ebuild
> +	virtual/jpeg:0
needs updating

2022-06-18 08:28 UTC, SoapGentoo approved these changes

2022-06-18 08:58 UTC, closed without merging