dev-games/aseprite: add 1.2.35, drop 1.1.9
gentoo/gentoo pull request #26171
Opened 2022-06-30 19:50 UTC by brausepulver

Closes: https://bugs.gentoo.org/696186
Signed-off-by: Johannes Kindermann <binaryjockey@gmail.com>

2022-07-01 07:08 UTC, winterheart requested changes

2022-07-01 07:08 UTC, winterheart commented on dev-games/aseprite/aseprite-1.2.35.ebuild
> +	use debug && append-cppflags -DDEBUGMODE -D_DEBU
Typo in -D_DEBU

2022-07-01 07:26 UTC, winterheart commented
@brausepulver, we cannot drop 1.1.9 before 1.2.35 stabilization. Please change commit as only adding 1.2.35.

2022-07-01 07:28 UTC, winterheart requested changes

2022-07-01 07:28 UTC, winterheart commented on dev-games/aseprite/aseprite-1.2.35.ebuild
> +KEYWORDS="~amd64 ~x86"
Since there precompiled binaries, we need now `KEYWORDS="-* ~amd64 ~x86"` here

2022-07-01 08:40 UTC, brausepulver commented
The latest version is reported to be 1.2.35.1 rather than 1.2.35 on https://packages.gentoo.org/packages/dev-games/aseprite. Where is this coming from?

2022-07-01 09:46 UTC, winterheart commented
packages.gentoo.org takes info from Repology (https://repology.org/project/aseprite/versions), there wrongly assigned 1.2.35.1 from AUR repository.

2022-07-11 07:51 UTC, winterheart commented
Hello.
I made another PR #26335 for aseprite 1.2.35, this can be closed.

2022-07-23 09:13 UTC, closed without merging