media-video/streamdeck-ui: Add 2.0.4, enable py3.10
gentoo/gentoo pull request #26381
Opened 2022-07-13 11:09 UTC by Olti

streamdeck-ui supports python 3.10 since version 1.1.3 (released: 2 Feb 2022)

Bug: https://bugs.gentoo.org/809833
Signed-off-by: Christian Oltenburger <christian@oltenburger.eu>

2022-07-13 12:58 UTC, SoapGentoo requested changes

2022-07-14 07:53 UTC, Olti commented on media-video/streamdeck-ui/streamdeck-ui-2.0.4.ebuild
> +	sed -i "s#os.path.dirname(os.path.abspath(__file__))#'/usr/share/streamdeck-ui'#" streamdeck_ui/config.py
Sure. Will be updated shortly.

2022-07-14 07:54 UTC, Olti commented on media-video/streamdeck-ui/streamdeck-ui-2.0.4.ebuild
> +PYTHON_COMPAT=( python3_{7..10} )
No, since this package supports only version 3.8 to 3.10. Need to check minimum version to 3.8, missed that

2023-11-29 14:09 UTC, AndrewAmmerlaan commented
Closing due to removal of the target package.

2023-11-29 14:09 UTC, closed without merging