dev-lang/ghc: keyword 9.0.2 for ~amd64, ~ppc64, ~x86
gentoo/gentoo pull request #26392
Opened 2022-07-13 18:59 UTC by matoro

This brings up much of the Haskell ecosystem to 9.0.x, AND introduces a port for ppc64le.  More ports to follow.

Unfortunately I was not able to bootstrap any of the existing keyworded ghc versions.  9.0.2 was the earliest version that I was able to bootstrap using Debian's binaries (also at 9.0.2).

To make sure that the ecosystem functioned reasonably with ghc 9, and on ppc64le, I keyworded the dep trees for app-text/pandoc and dev-util/shellcheck.  This covers a good chunk of dev-haskell/*.  **All unit tests (where present) passed for all packages included here.**

Unfortunately due to the tendency for Haskell packages to impose tight upper bound checks, along with a major ghc version bump, this required upgrades for probably most of the dep trees.  However, rest assured that I **did not create any of the new ebuilds added here, neither by hand nor with hackport.  ALL of the new ebuilds are taken verbatim from https://github.com/gentoo-haskell/gentoo-haskell.  Where ::haskell had the same version but with patches or adjusted dependency checks, I revbumped the version in ::gentoo even though not strictly required, and linked the associated ::haskell commit in the commit message.**

There is one exception to the sentence above:  I tweaked =app-text/pandoc-2.18 from a local `lua53` USE flag to use `lua-single.eclass`.

Let me know if there's anything I can do to make this easier to review.

2022-07-13 21:58 UTC, matoro commented
Put this as draft temporarily to shut up the bot, but it should be ready.

2022-07-14 10:17 UTC, mgorny commented
@matoro, I think I've found the problem — we didn't protect against running the script multiple times simultaneously, and due to connectivity issues multiple instances ended up running in parallel — then they tried to process the same PR simultaneously.

2022-07-14 10:17 UTC, mgorny commented
The next assignment run should clean up the duplicate comments. That is, when it finally manages to connect ;-).

2022-07-14 11:15 UTC, thesamesam commented
CC @ceamac, @hololeap, @solpeth as FYI (I don't expect comment necessarily)

2022-07-14 20:11 UTC, solpeth requested changes
We also need `haskeline-0.8.2.0` and `terminfo-0.4.1.5` brought over from `::haskell` with the appropriate `CABAL_CORE_LIB_GHC_PV=PM:9.0.2` line, and we need to add `PM:9.0.2` to xhtml if it is not already there.

2022-07-14 20:11 UTC, solpeth commented on dev-haskell/cabal/cabal-3.6.3.0.ebuild
> +CABAL_CORE_LIB_GHC_PV="PM:8.10.3 PM:8.10.4 PM:8.10.4-r1 PM:9999"
This version of `cabal` is not bundled with ghc-9.0.2, so this won't work. We need to keep bundled libraries versioned exactly the same as what they are in ghc. For an idea of this, do `git grep 'CABAL_CORE_LIB_GHC_PV'` in the gentoo-haskell repo and it'll show you which packages are bundled with ghc-9.0.2. Happy to help with this over the next few days if need be.

2022-07-14 20:11 UTC, solpeth commented on dev-haskell/binary/binary-0.8.7.0.ebuild
>  # keep in sync with ghc-8.8
We need version 0.8.8.0 to be compatible with ghc-9.0.2. All in `::haskell` ready to go, so you should be able to pull it over to here with only minor changes if any.

2022-07-14 20:11 UTC, solpeth commented on dev-haskell/text/text-1.2.4.1_rc1.ebuild
>  # keep in sync with ghc-8.10.3
We need `text-1.2.5.0` brought over from `::haskell` with the correct `CABAL_CORE_LIB_GHC_PV` line.

2022-07-14 20:15 UTC, solpeth commented
I don't know if you wanted to tackle this now or later, but it would be good to bring in the latest `hackport` from `::haskell` as well (if you haven't already - I can't see it here).

We also have eclass changes in `::haskell` that should probably be brought in here if they haven't already. But @hololeap has more of a handle on that.

2022-07-22 00:38 UTC, solpeth approved these changes
I've looked at most of the changes directly - they all look fine. Bundled libs changes should be fine. In isolation, each change seems good to go.

I have not tested this batch of changes collectively on a live system or container with only the ::gentoo repo, but assuming the PR author has done this then no problems should arise.

N.B.: there are a number of major version bumps in here. This is why we need to ensure there are no dependency conflicts between packages, which is why testing on a container or live system is important to not break ::gentoo's haskell packages.

2022-07-22 22:16 UTC, closed without merging