sci-physics/fastjet-contrib: Fix tc ar and ranlib
gentoo/gentoo pull request #26621
Opened 2022-07-27 12:32 UTC by APN-Pucky

Closes: https://bugs.gentoo.org/860222
Signed-off-by: Alexander Puck Neuwirth <alexander@neuwirth-informatik.de>

2022-08-01 11:15 UTC, amadio commented
Isn't this the same as #26554, and #26620? The change seems fine, but I don't get why there are several PRs with the same change being opened. You can rebase and push to the same PR if you update/rebase it.

2022-08-01 11:19 UTC, APN-Pucky commented
Sorry for the mess. 
I thought adding my self to the proxy maintainers would already add the label, but I guess it only gets added once the current metadata.xml has the proxy-maintainer.
In the other one I forgot to add the Bug to be closed.

2022-08-01 11:29 UTC, amadio commented
No problem, I'm just trying to understand why. Adding yourself as proxy-maintainer should be a separate commit, though. Do you mind splitting it and force-pushing here?

2022-08-02 07:56 UTC, SoapGentoo requested changes
please make patches as lean and "git alike" as possible, the metadata is just noise

2022-08-02 07:56 UTC, SoapGentoo commented on sci-physics/fastjet-contrib/files/fastjet-contrib-1.049-ar.patch
> +diff -Naru fjcontrib-1.049.orig/Centauro/Makefile fjcontrib-1.049/Centauro/Makefile
```suggestion
```

2022-08-02 07:56 UTC, SoapGentoo commented on sci-physics/fastjet-contrib/files/fastjet-contrib-1.049-ar.patch
> +--- fjcontrib-1.049.orig/Centauro/Makefile	2022-07-24 00:55:40.912538473 +0200
```suggestion
--- a/Centauro/Makefile
```

2022-08-02 07:56 UTC, SoapGentoo commented on sci-physics/fastjet-contrib/files/fastjet-contrib-1.049-ar.patch
> ++++ fjcontrib-1.049/Centauro/Makefile	2022-07-24 01:20:00.488103968 +0200
```suggestion
+++ b/Centauro/Makefile
```

2022-08-07 08:37 UTC, AndrewAmmerlaan approved these changes

2022-08-07 08:37 UTC, AndrewAmmerlaan commented on sci-physics/fastjet-contrib/metadata.xml
> +	<maintainer type="project" proxied="proxy">
CC @gentoo/proxy-maint for new proxy maintainer

2022-08-26 09:47 UTC, AndrewAmmerlaan commented on sci-physics/fastjet-contrib/fastjet-contrib-1.049.ebuild
> +	./configure --prefix=/usr --fastjet-config=/usr/bin/fastjet-config RANLIB="${RANLIB}" AR="${AR}" CXX="${CXX}" CFLAGS="${CFLAGS}" CXXFLAGS="${CXXFLAGS}" FFLAGS="${FFLAGS}" LDFLAGS="${LDFLAGS}" || die
I think it is a good idea to revision bump the ebuild to -r1. I'll do this while merging.

2022-08-26 09:50 UTC, closed without merging

2022-08-26 09:53 UTC, AndrewAmmerlaan commented
Thanks :+1: