app-text/mandoc: Add app-text/manpager to RDEPEND
gentoo/gentoo pull request #26658
Opened 2022-07-29 20:49 UTC by orbea

When using `USE=system-man` man(1) fails to run if `app-text/manpager` is not installed.

2022-07-31 17:01 UTC, floppym requested changes
Please remove the old ebuild in the same commit; there's no reason to keep it around for an RDEPEND change.

2022-07-31 18:44 UTC, orbea commented
Thanks for the tip! I removed it.

2022-07-31 20:04 UTC, closed without merging

2022-08-01 11:28 UTC, wylfen commented
I'm curious about this change, I'm using mandoc with `system-man` and do not see this behaviour. For me `MANPAGER` is unset, and `PAGER` points to `/usr/bin/less`. Just like `man(1)` says, mandoc falls back to `less(1)` if `MANPAGER` and `PAGER` are unset. Am I missing something?

2022-08-01 14:06 UTC, orbea commented
@wylfen It seems `MANPAGER` is set by default in Gentoo to `manpager` and if someone switches to mandoc it will unsuspectingly fail when man-db and its dependencies are dropped. However maybe its better to copy man-db which sets `app-text/manpager` conditionally with the `manpager` USE?

https://github.com/gentoo/gentoo/blob/973d366c66abbbec251e10bfd418125783c786e6/sys-apps/man-db/man-db-9999.ebuild#L42

2022-08-01 14:29 UTC, wylfen commented
I've been trying to find out where Gentoo sets `MANPAGER=manpager` and the only place I could find is in the ebuild for `app-text/manpager` itself. Unless this does indeed happen somewhere else also, I think the behaviour before this change was perfect. If a user has `app-text/manpager` installed, `MANPAGER` will be set and the program used with `man(1)` invocations. If not, no file in `/etc/env.d` exists, and `MANPAGER` is unset, having `man(1)` use `less(1)`.

Perhaps this problem was caused by having removed `app-text/manpager` with old shells still open that did not have their environments updated?

2022-08-01 14:54 UTC, orbea commented
> Perhaps this problem was caused by having removed `app-text/manpager` with old shells still open that did not have their environments updated?

You're right, this was the problem and I feel silly for not realizing it on my own. However `app-text/manpager` does add color output where `less(1)` doesn't so perhaps copying `app-text/man-db` by adding a USE flag that defaults to on would still be better? If you feel strongly about it we could alternatively revert my commit?

2022-08-01 15:10 UTC, floppym commented
The "manpager" USE flag on man-db violates our [policy](https://projects.gentoo.org/qa/policy-guide/dependencies.html#pg0001) on optional runtime dependencies.

I think the correct action here would be to revert this PR, and additionally remove the "manpager" USE flag from man-db.

2022-08-01 15:16 UTC, orbea commented
I'll defer to your experience, do you want to make the PR?

2022-08-01 15:16 UTC, wylfen commented
I don't feel strongly about this at all. I would only prefer if `manpager` wasn't pulled in automatically.

This is because I'm not sure `manpager` is needed at all. What it does is [wrap around](https://gitweb.gentoo.org/repo/gentoo.git/tree/app-text/manpager/files/manpager.c) `less(1)` (or whatever `PAGER` is set to) and setting the `LESS_TERMCAP_*` environment variables that control how `less(1)` styles certain escapes. Sadly `LESS_TERMCAP_*` is not documented in `less(1)` or `lesskey(1)`, so this might be hard to find.

For the currently stable version of `less(1)` in the repos, it is enough to set these environment variables in the `~/.lesskey` file. Below is a setup that replicates the default in `manpager`:

```
#env
LESS_TERMCAP_mb = \e[5;31m 
LESS_TERMCAP_md = \e[1;34m
LESS_TERMCAP_me = \e[0;0m
LESS_TERMCAP_us = \e[4;36m
LESS_TERMCAP_ue = \e[0;0m 
```

2022-08-01 15:23 UTC, floppym commented
The change to mandoc has been reverted in 47e4b5b7090c7da5308dd08ee6179c335178d469.

2022-08-01 15:26 UTC, orbea commented
@wylfen Thanks for the suggestion, that is very useful to know! It should be important to note that changing the `#env` comment will break it.

2022-08-01 15:27 UTC, wylfen commented
Yes, `lesskey(1)` is very particular about this. It seems to be a comment, but it is not - see the `FILE FORMAT` section in its manual.

Thanks for the quick resolution to this!

2022-08-01 15:38 UTC, orbea commented
> Thanks for the quick resolution to this!

I greatly appreciate being clearly told how I am wrong as I may have not realized on my own. :)