www-app/gitea: Version bump to 1.17.0
gentoo/gentoo pull request #26683
Opened 2022-07-31 11:59 UTC by eeyrjmr

Signed-off-by: Jonathan Roadley-Battin <jon.roadleybattin@gmail.com>

2022-08-04 10:22 UTC, stintel requested changes
Aside from the keyword, gitea 1.17.0 built from this ebuild seems to run fine. Thanks!

2022-08-05 19:39 UTC, ajakk requested changes
Please squash your commits and fix the summary prefix (`www-app` -> `www-apps`). Probably should use pkgdev for that, so it's always done correctly.

2022-08-05 19:39 UTC, ajakk commented on www-apps/gitea/gitea-1.17.0.ebuild
> +RESTRICT="test"
Why? It seems like tests depend on nodejs, and with that installed the vast majority of tests seem to work for me.

2022-08-05 19:41 UTC, ajakk commented
cc @thamognya

2022-08-05 22:26 UTC, closed without merging

2022-08-17 12:24 UTC, stintel commented
@eeyrjmr why did you close this?