app-shells/starship: add 1.10.0
gentoo/gentoo pull request #26871
Opened 2022-08-15 13:54 UTC by ixti

* Starship replaced libgit2 based git2 crate with [git-repository](https://github.com/gentoo/gentoo/pull/25931), thus I've removed DEPEND (and RDEPEND) and relaxed down rust version requirement to `>= 1.59`
* Added MPL-2.0 to the LICENSE list (required by uluru - new dependency)

Signed-off-by: Alexey Zapparov <alexey@zapparov.com>

2022-08-15 13:55 UTC, ixti commented
cc: @bowlofeggs

2022-08-15 13:55 UTC, ixti commented
cc: @Flowdalic

2022-08-16 01:19 UTC, thesamesam commented
Looks like gitoxide bundles zlib-ng. Not your fault, just unfortunate.

Also, could you rebase to 1.10.1?

2022-08-16 02:23 UTC, ixti commented
> Looks like gitoxide bundles zlib-ng. Not your fault, just unfortunate.

:((

> Also, could you rebase to 1.10.1?

Sure!

2022-08-16 02:28 UTC, ixti commented
@thesamesam done

2022-08-19 00:23 UTC, bowlofeggs requested changes
This seems to work. The only change I think we need to make is the `~amd64` keyword.

I noticed that the git interactions seem slower than they were before, but I suppose that's an upstream concern ☺

2022-08-19 14:00 UTC, ixti commented on app-shells/starship/starship-1.10.1.ebuild
> +KEYWORDS="amd64"
Oh. Thank you for catching this. Totally forgot about that.

2022-08-19 14:01 UTC, ixti commented on app-shells/starship/starship-1.10.1.ebuild
> +# Copyright 2022 Gentoo Authors
Good catch. Thank you.

2022-08-19 14:03 UTC, ixti commented on app-shells/starship/starship-1.10.1.ebuild
> +BDEPEND=">=virtual/rust-1.59"
Yes. Previous rust min version bump was due to git2 crate, that was replaced with gitoxide: https://github.com/starship/starship/pull/3883

2022-08-19 14:03 UTC, ixti commented on app-shells/starship/starship-1.10.1.ebuild
> +# Copyright 2022 Gentoo Authors
Fixed.

2022-08-19 14:04 UTC, ixti commented on app-shells/starship/starship-1.10.1.ebuild
> +KEYWORDS="amd64"
Fixed.

2022-08-19 14:07 UTC, ixti commented
> I noticed that the git interactions seem slower than they were before, but I suppose that's an upstream concern

Funny enough, [gitoxide](https://github.com/Byron/gitoxide)'s promise is: _perform as good or better than the canonical implementation_. :shrug:

2022-08-19 17:21 UTC, bowlofeggs commented
I see that there is now also a 1.10.2 that upgrades gitoxide. There may be some performance benefits:

https://github.com/starship/starship/issues/4277

I think it's fine to merge this PR as is, and I also think it's fine to bump it up to 1.10.2. Up to you.

2022-08-20 03:12 UTC, ixti commented
Oh. I think it's better to bump then. Will do that tomorrow.

2022-08-21 15:16 UTC, ixti commented
@bowlofeggs Updated.

2022-08-22 04:20 UTC, bowlofeggs approved these changes

2022-08-22 16:11 UTC, bowlofeggs commented
I don't have commit privileges, so we'll need someone to merge this for us.

2022-08-23 05:11 UTC, closed without merging

2022-09-24 02:20 UTC, bowlofeggs commented
https://bugs.gentoo.org/872584