app-editor/vscodium: disable update server on install
gentoo/gentoo pull request #26897
Opened 2022-08-17 10:40 UTC by joecool1029

This is also applicable to vscode. As portage manages
the updates for these packages it is undesirable to receive
notifications about updates that may not apply.

This removes the reference to the update server.

Signed-off-by: Joe Kappus <joe@wt.gd>

2022-08-17 10:46 UTC, arthurzam commented on app-editors/vscodium/vscodium-1.70.1.ebuild
> +        sed -i "/updateUrl/d" ${S}/resources/app/product.json || die
looks like indentation broke :)

2022-08-17 10:46 UTC, arthurzam requested changes
Can you also do the same to `vscode` in same PR?
Also, this needs a revision bump, as it affects installed files.

2022-08-17 10:53 UTC, joecool1029 commented
> Can you also do the same to `vscode` in same PR? Also, this needs a revision bump, as it affects installed files.

Is it ok to remove the old revisions? Or do I leave those in?

2022-08-17 20:10 UTC, arthurzam requested changes
Please fix indentation of you changes!
It should be a single TAB in all of them 😃

2022-08-17 23:15 UTC, joecool1029 commented
> Please fix indentation of you changes!
> It should be a single TAB in all of them 😃 

Sorry about that, I will fix the editor situation and try to get more sleep!

2022-08-18 01:00 UTC, joecool1029 commented
https://github.com/VSCodium/vscodium/discussions/1189 Some discussion with upstream on the update check situation.

2022-08-18 16:30 UTC, arthurzam approved these changes

2022-08-18 16:33 UTC, closed without merging