dev-util/codespell: add 2.2.0
gentoo/gentoo pull request #26909
Opened 2022-08-18 08:53 UTC by waebbl

Closes: https://bugs.gentoo.org/865671
Signed-off-by: Bernd Waibel <waebbl-gentoo@posteo.net>

2022-08-18 14:45 UTC, waebbl commented
bump to 2.2.1

2022-08-20 15:47 UTC, arthurzam requested changes

2022-08-20 15:47 UTC, arthurzam commented on dev-util/codespell/codespell-2.2.1.ebuild
> +PYTHON_COMPAT=( python3_{8..11} pypy3 )
Please move to `PEP517` mode - [docs](https://projects.gentoo.org/python/guide/distutils.html#basic-use-pep-517-mode)

2022-08-20 15:47 UTC, arthurzam commented on dev-util/codespell/codespell-2.2.1.ebuild
> +distutils_enable_tests --install pytest
When moving to PEP517 mode, you will want to change it into (in this mode it always does install):
```suggestion
distutils_enable_tests pytest
```

2022-08-21 18:41 UTC, closed without merging