app-arch/lz4: enable tests (switch to custom Makefiles)
gentoo/gentoo pull request #27082
Opened 2022-08-30 22:49 UTC by thesamesam

Bit sad given it has a CMake build system (but it's kind of
unofficial, and then the Meson build system is even more
unofficial, as it's in "contrib", and there's a PR pending
to bump it to 1.9.4).

But in any case, this is really the same as app-arch/zstd
(same upstream) and anything but Makefiles aren't properly
supported and don't have all the needed functionality.

So, we switch to the Makefiles for tests.

Also has a benefit of not having weird symbol
leakage.

Closes: https://bugs.gentoo.org/866097
Signed-off-by: Sam James <sam@gentoo.org>

2022-08-31 06:22 UTC, mgorny requested changes

2022-08-31 06:22 UTC, mgorny commented on app-arch/lz4/lz4-1.9.4-r1.ebuild
> +	multilib_copy_sources
```suggestion
	default
	multilib_copy_sources
```

2022-08-31 06:22 UTC, mgorny commented on app-arch/lz4/lz4-1.9.4-r1.ebuild
> +	emake \
Please no back(s)lashes.

2024-01-27 07:26 UTC, amadio commented
@thesamesam Do you plan to eventually merge this?

2024-01-27 07:38 UTC, thesamesam commented
Good question. I think I'd rather switch to the Meson build in `build/meson`, like we did for zstd (which was basically in the same situation as lz4). IIRC a lot of fixes landed since the last release, so let's revisit when the next one is out.

2024-01-27 07:38 UTC, closed without merging