eclass/*: fixes UnquotedVariable and some extras
gentoo/gentoo pull request #27123
Opened 2022-09-03 11:54 UTC by arthurzam

- fix `UnquotedVariable` results from live pkgcheck (note that the current CI reports some more cases, they were false positives I fixed in live pkgcheck, but still not released)
- Dropped `EAPI<7` support from `kodi-addon.eclass` and `myspell-r2.eclass`, because there were no consumers, and if we already invalidate cache, then to go with it.
- Did some refactor on `kodi-addon.eclass`, because it looked easy enough?

I will post this to ML later, and then start the timer. Currently I just want some basic first reviews, as this is my first cross eclasses changes.

2022-09-03 12:54 UTC, SoapGentoo requested changes

2022-09-03 12:54 UTC, SoapGentoo commented on eclass/kodi-addon.eclass
>  case "${EAPI:-0}" in
```suggestion
case ${EAPI} in
```

2022-09-03 12:54 UTC, SoapGentoo commented on eclass/kodi-addon.eclass
>  	*) die "EAPI=${EAPI} is not supported" ;;
```suggestion
	*) die "${ECLASS}: EAPI ${EAPI:-0} not supported"
```

2022-09-03 12:54 UTC, SoapGentoo commented on eclass/myspell-r2.eclass
>  case ${EAPI:-0} in
```suggestion
case ${EAPI} in
```

2022-09-03 12:54 UTC, SoapGentoo commented on eclass/myspell-r2.eclass
> +	[7-8])
```suggestion
	7|8)
```

2022-09-04 19:38 UTC, ConiKost approved these changes
Ack for ```myspell-r2``` eclass.

2022-09-12 19:14 UTC, closed without merging