gnome-base/nautilus: Version bump to 43.0
gentoo/gentoo pull request #27324
Opened 2022-09-18 12:13 UTC by Schievel1

Signed-off-by: Pascal Jäger <pascal.jaeger@leimstift.de>

This is missing the following:
- [ ] gtk4-4.7.2 (I just assumed this is going to be in slot 4, so probably needs change)
- [ ] gnome-desktop-43 (I assumed slot 4?)

2022-09-18 14:52 UTC, Schievel1 commented
PR for gnome desktop here: #27326

2022-09-19 01:46 UTC, mattst88 requested changes

2022-09-19 01:46 UTC, mattst88 commented on net-libs/libcloudproviders/libcloudproviders-0.3.1.ebuild
> +VALA_USE_DEPEND=vapigen
Drop this.

2022-09-19 01:46 UTC, mattst88 commented on net-libs/libcloudproviders/libcloudproviders-0.3.1.ebuild
> +KEYWORDS="~alpha ~amd64 ~arm ~arm64 ~ia64 ~ppc ~ppc64 ~riscv ~sparc ~x86 ~amd64-linux ~x86-linux"
We have to ask architecture teams to test on platforms we can't test on. Change this to just `KEYWORDS="~amd64"`.

2022-09-19 01:46 UTC, mattst88 commented on gnome-base/nautilus/nautilus-43.0.ebuild
> +KEYWORDS="~alpha ~amd64 ~arm ~arm64 ~ia64 ~ppc ~ppc64 ~riscv ~sparc ~x86 ~amd64-linux ~x86-linux"
Since we're depending on libcloudproviders which will have reduced `KEYWORDS` initially, we need to change this to `KEYWORDS="~amd64"`.

2022-09-19 01:46 UTC, mattst88 commented on net-libs/libcloudproviders/libcloudproviders-0.3.1.ebuild
> +	>=dev-util/meson-0.47.0
Drop this. `meson.eclass` requires a newer version.

2022-09-19 01:46 UTC, mattst88 commented on net-libs/libcloudproviders/libcloudproviders-0.3.1.ebuild
> +		-Dinstalled-tests=false
Let's keep these in the same order as `meson_options.txt`. `enable-gtk-doc` / `installed-tests` / `introspection` / `vapigen`.

2022-09-19 01:46 UTC, mattst88 commented on gnome-base/nautilus/nautilus-43.0.ebuild
> +		>=dev-util/gtk-doc-1.10
This has been replaced with `gi-docgen`, so we can drop it.

2022-09-19 01:46 UTC, mattst88 commented on gnome-base/nautilus/nautilus-43.0.ebuild
> +	>=dev-util/meson-0.57.2
Can drop this. `meson.eclass` requires a newer version.

2022-09-19 01:46 UTC, mattst88 commented on gnome-base/nautilus/nautilus-43.0.ebuild
> +	>=dev-util/gdbus-codegen-2.51.2
Not sure where you found `2.51.2`. I think you should drop this.

2022-09-19 01:47 UTC, mattst88 commented
> gtk4-4.7.2 (I just assumed this is going to be in slot 4, so probably needs change)

Yeah, this is `gui-libs/gtk:4`.

> gnome-desktop-43 (I assumed slot 4?)

Yep, `gnome-base/gnome-desktop:4=`.

> a new dependency in the meson.build is libcloudproviders, which I also could not find in gentoo

Nice work!

2022-09-21 13:56 UTC, mattst88 commented on gnome-base/nautilus/nautilus-43.0.ebuild
> +	>=dev-util/gdbus-codegen-2.51.2
Ah, sorry. You're right. I must have misread the diff.

2022-09-30 17:23 UTC, mattst88 commented
There are a bunch of changes to nautilus in the commit that adds libcloudproviders.

2022-09-30 17:30 UTC, mattst88 commented on net-libs/libcloudproviders/libcloudproviders-0.3.1.ebuild
> +	gtk-doc? ( dev-util/gi-docgen )
This actually requires `dev-util/gtk-doc`, not `dev-util/gi-docgen`.

2022-09-30 17:55 UTC, closed without merging