unpacker.eclass: tests, fixes, .gpkg.tar support
gentoo/gentoo pull request #27431
Opened 2022-09-24 15:01 UTC by mgorny

- add tests for unpacking various file formats
- fix handling broken/invalid `.zst` and `.7z` files
- use lowercase suffixes everywhere consistently
- add support for `.lz4` and `.lzo`
- add support for on-the-fly unpacking of the image archive from `.gpkg.tar`

Includes an example `.gpkg.tar` unpacking for gentoo-kernel-bin.

CC @gentoo/base-system, @gentoo/dist-kernel

2022-09-25 06:44 UTC, thesamesam approved these changes

2022-09-25 06:44 UTC, thesamesam commented on eclass/unpacker.eclass
>  	esac
Add a Closes tag for the bug to this commit

2022-09-25 07:22 UTC, mgorny commented
Also updated the tests to compare file contents and print diff on mismatch, plus test multistream compressed files.

2022-09-25 19:30 UTC, floppym approved these changes
Nice work, as usual.

2022-09-26 08:05 UTC, SoapGentoo requested changes

2022-09-26 08:05 UTC, SoapGentoo commented on eclass/tests/unpacker.sh
> +#!/bin/bash
portable shebangs?

2022-09-26 08:09 UTC, stha09 approved these changes

2022-09-26 10:01 UTC, mgorny commented on eclass/tests/unpacker.sh
> +#!/bin/bash
Done.

2022-09-26 10:01 UTC, mgorny commented
Updated shebang and fixed grammar per @SoapGentoo.

2022-09-27 20:28 UTC, closed without merging