x11-terms/gnome-terminal: bump to 3.46.1, x11-libs/vte: bump to 0.70.0 (gtk3 only)
gentoo/gentoo pull request #27443
Opened 2022-09-25 08:24 UTC by Schievel1

Gnome terminal can be build, however I still need to get the cntr-ntfy-autottl patch to work.

2022-09-25 21:47 UTC, mattst88 requested changes

2022-09-25 21:47 UTC, mattst88 commented on gui-libs/vte-common/vte-common-0.70.0.ebuild
> +SLOT="2.91" # vte_api_name in meson.build
I think you mean `vte_api_version`?

2022-09-25 21:47 UTC, mattst88 commented on gui-libs/vte/vte-0.70.0.ebuild
> +VALA_MIN_API_VERSION="0.48"
Can drop this.

2022-09-25 21:47 UTC, mattst88 commented on x11-libs/vte/vte-0.70.0.ebuild
> +VALA_MIN_API_VERSION="0.48"
Can drop this.

2022-09-25 21:47 UTC, mattst88 commented on x11-libs/vte/vte-0.70.0.ebuild
> +PYTHON_COMPAT=( python3_{8..10} )
Add Python 3.11.

2022-09-25 21:47 UTC, mattst88 commented on gui-libs/vte-common/vte-common-0.70.0.ebuild
> +PYTHON_COMPAT=( python3_{8..10} )
Add Python 3.11.

2022-09-25 21:47 UTC, mattst88 commented on gui-libs/vte/vte-0.70.0.ebuild
> +PYTHON_COMPAT=( python3_{8..10} )
Add Python 3.11.

2022-09-25 21:47 UTC, mattst88 commented on x11-terms/gnome-terminal/gnome-terminal-3.46.1.ebuild
> +	>=x11-libs/vte-0.70.0:291[!vanilla?]
`:291` should be `:2.91`.

2022-09-25 21:47 UTC, mattst88 commented on gui-libs/vte/vte-0.70.0.ebuild
> +	gtk-doc? ( dev-util/gi-docgen )
We need to add REQUIRED_USE="gtk-doc? ( introspection )"` whenever we begin using gi-docgen.

2022-09-25 21:47 UTC, mattst88 commented on x11-libs/vte/vte-0.70.0.ebuild
> +	gtk-doc? ( dev-util/gi-docgen )
We need to add REQUIRED_USE="gtk-doc? ( introspection )"` whenever we begin using gi-docgen.

2022-09-25 21:47 UTC, mattst88 commented on gui-libs/vte/vte-0.70.0.ebuild
> +	meson_install # not meson_src_install because this would include einstalldocs, which would result in file collissions with x11-libs/vte
Let's fix the typo in `collisions` while we're here.

2022-09-25 21:47 UTC, mattst88 commented on gui-libs/vte/vte-0.70.0.ebuild
> +#   # remove the files that have collissions with x11-libs/vte. The files come with gui-libs/vte-common instead
Let's fix the typo in `collisions` while we're here.

Also, let's remove the stray `#` at the beginning of the line to make the comment properly indented.

2022-09-25 21:47 UTC, mattst88 commented on x11-libs/vte/vte-0.70.0.ebuild
> +#   # remove the files that have collissions with gui-libs/vte. The files come with gui-libs/vte-common instead
Let's fix the typo in `collisions` while we're here.

Also, let's remove the stray `#` at the beginning of the line to make the comment properly indented.

2022-09-25 21:47 UTC, mattst88 commented on x11-libs/vte/vte-0.70.0.ebuild
> +	meson_install # not meson_src_install because this would include einstalldocs, which would result in file collissions with gui-libs/vte
Let's fix the typo in `collisions` while we're here.

2022-09-25 21:47 UTC, mattst88 commented on gui-libs/vte-common/vte-common-0.70.0.ebuild
> +	exeinto "/usr/libexec/"
I'd drop the quotes where they aren't needed (like here).

2022-09-25 21:47 UTC, mattst88 commented on gui-libs/vte-common/vte-common-0.70.0.ebuild
> +	insinto "/etc/profile.d/"
and here.

2022-09-25 21:47 UTC, mattst88 commented on gui-libs/vte-common/vte-common-0.70.0.ebuild
> +	  insinto "/usr/lib/systemd/user/vte-spawn-.scode.d/"
and here, etc.

2022-09-26 13:50 UTC, mattst88 approved these changes
Looks good. Thank you. I'd separate the `vte-common` stuff out of the commit that adds `gui-libs/vte` (I'll do that). It's best to have one commit per package.

2022-09-26 14:19 UTC, Schievel1 commented on gui-libs/vte/vte-0.70.0.ebuild
> +	=gui-libs/vte-common-${PV}[systemd?]
noted, thanks for your input

2022-09-26 14:49 UTC, closed without merging