games-emulation/pcsxr: add 1.9.95, drop 1.9.94_p20190306 + patch
gentoo/gentoo pull request #27805
Opened 2022-10-16 14:45 UTC by immolo

Version bump to 1.95.5 plus this also applies the patch to fix the harfbuzz dependency issue.

Closes: https://bugs.gentoo.org/791034
Thanks-to: Agostino Sarubbo
Signed-off-by: Ian Jordan <immoloism@gmail.com>

2022-10-17 19:04 UTC, thesamesam commented on games-emulation/pcsxr/pcsxr-1.9.95.ebuild
>  EAPI=7
Please cleanup old in a separate commit.

2022-10-17 19:06 UTC, thesamesam commented on games-emulation/pcsxr/pcsxr-1.9.95.ebuild
>  EAPI=7
Also, you didn't change EGIT_COMMIT and the Manifest didn't change, so I bet this is actually the same version ;)

We should change the ebuild to do something like:
if [[ ${PV} == *_p* ]] ; then
	EGIT_COMMIT=""
	SRC_URI="https://github.com/iCatButler/pcsxr/archive/${EGIT_COMMIT}.tar.gz -> ${MY_P}.tar.gz"
else
	SRC_URI="" # (fill this in)
fi

2022-10-18 12:31 UTC, mgorny requested changes
Also, where did you get this version from? There's no such tag in the repo, and still no new commits since 2019.

2022-10-18 12:31 UTC, mgorny commented on games-emulation/pcsxr/files/pcsxr-1.9.95-harfbuzz-dep-fix.patch
> +--- /dev/null
Can we get something shorter for Gentoo? It's fine if you literally just had to pass paths via CMake.

2022-10-19 01:57 UTC, closed without merging