mail-client/claws-mail-4.1.1: add oauth flag
gentoo/gentoo pull request #27950
Opened 2022-10-25 18:52 UTC by kuraga

Claws Mail 4.1.1 made OAuth2 support optional: https://git.claws-mail.org/?p=claws.git;a=commit;h=d1d9ffd6c37e25c6e25bfb59571591824122b91e

Closes: https://bugs.gentoo.org/878305

2022-10-26 09:39 UTC, voyageur requested changes
Thanks again for the PR and bug! Aside from placing the new USE flag in sorted order, we will also need an addition to metadata.xml
oauth is a [local USE flag](https://devmanual.gentoo.org/ebuild-writing/misc-files/metadata/index.html#local-use-flag-descriptions) so it needs an entry there, I think something like the one used for gnome-extra/evolution-data-server will be fine: "Enable internal OAuth2 authentication support"

You can spot this issue (and similar) running "pkgcheck scan" from dev-util/pkgcheck

2022-10-26 09:39 UTC, voyageur commented on mail-client/claws-mail/claws-mail-4.1.1-r1.ebuild
> +IUSE="archive bogofilter calendar clamav dbus debug dillo doc gdata +gnutls +oauth +imap ldap +libcanberra +libnotify litehtml networkmanager nls nntp +notification pdf perl +pgp rss session sieve sm
Let's keep the USE flags sorted (especially here with all the possible ones) - "+oauth" should be added just before "pdf"

2022-10-26 09:39 UTC, voyageur commented on mail-client/claws-mail/claws-mail-4.1.1-r1.ebuild
> +	oauth? ( gnutls )
Less important than in USE flags but keeping this list sorted is helpful in maintenance

2022-10-26 09:39 UTC, voyageur commented on mail-client/claws-mail/claws-mail-4.1.1-r1.ebuild
> +		$(use_enable oauth oauth2)
And same in configure flags :)

2022-10-26 11:16 UTC, kuraga commented
> we will also need an addition to metadata.xml oauth is a [local USE flag](https://devmanual.gentoo.org/ebuild-writing/misc-files/metadata/index.html#local-use-flag-descriptions) so it needs an entry there

Done.

P.S. Hm... I didn't see `local` [here](https://packages.gentoo.org/useflags/oauth). Is it strange to take description from the first package used this USE flag? :)

2022-10-27 07:03 UTC, voyageur commented
Indeed, you have to hope the first alphabetical package has a "generic" description - but having a better system would probably require some magic to parse all strings etc :)

2022-10-27 07:07 UTC, closed without merging