dev-libs/libstrophe: drop old versions, backport fix for /bin/sh -> dash issue
gentoo/gentoo pull request #28148
Opened 2022-11-05 19:56 UTC by NexAdn

This PR first drops two old versions and backports a fix for build issues when dash is set as `/bin/sh` symlink target.

2022-11-05 21:40 UTC, Flowdalic commented on dev-libs/libstrophe/libstrophe-0.12.2.ebuild
> +	https://github.com/strophe/libstrophe/commit/7352bd5cdbacf98771fdc0d32a606c4b6718077c.patch
```suggestion
	https://github.com/strophe/libstrophe/commit/7352bd5cdbacf98771fdc0d32a606c4b6718077c.patch -> libstrophe-fix-configure-bashisms.patch # https://github.com/strophe/libstrophe/pull/218
```

2022-11-05 21:41 UTC, Flowdalic requested changes

2022-11-05 21:41 UTC, Flowdalic commented on dev-libs/libstrophe/libstrophe-0.12.2.ebuild
> +	"${DISTDIR}/7352bd5cdbacf98771fdc0d32a606c4b6718077c.patch"
```suggestion
	"${DISTDIR}/libstrophe-fix-configure-bashisms.patch"  # https://github.com/strophe/libstrophe/pull/218
```

2022-11-06 09:33 UTC, NexAdn commented on dev-libs/libstrophe/libstrophe-0.12.2.ebuild
> +	https://github.com/strophe/libstrophe/commit/7352bd5cdbacf98771fdc0d32a606c4b6718077c.patch
applied

2022-11-06 09:33 UTC, NexAdn commented on dev-libs/libstrophe/libstrophe-0.12.2.ebuild
> +	"${DISTDIR}/7352bd5cdbacf98771fdc0d32a606c4b6718077c.patch"
applied

2022-11-06 11:07 UTC, closed without merging