ROCm LLVM-15
gentoo/gentoo pull request #28144
Opened 2022-11-05 07:27 UTC by jdkleuver

Backports ROCm-Developer-Tools/hipamd@28009bc68faf2b4dd8fda91c99b0725e1b063a18 to enable compiling with LLVM 15, which introduced the `__noinline__` keyword to allow CUDA/HIP code to be compiled against GCC 12, see https://github.com/llvm/llvm-project/issues/57544 and https://reviews.llvm.org/D124866

This bug was preventing rocBLAS from being able to build for some users, see https://forums.gentoo.org/viewtopic-p-8756823.html

Other ROCm packages are updated to LLVM 15 to maintain compatibility with LLVM bytecode.

2022-11-05 07:34 UTC, littlewu2508 commented
Thanks! I'll review these patches.

Also, https://bugs.gentoo.org/874096 may also be solved when migrating to LLVM 15

2022-11-06 04:44 UTC, littlewu2508 commented
miopen failed to build with `FEATURES=test`:

```bash
/usr/lib/llvm/15/bin/clang++ -O2 -pipe -DNDEBUG --rocm-path=/usr --hip-device-lib-path=/usr/lib/amdgcn/bitcode -Wl,-O1 -Wl,--as-needed -fuse-ld=mold -Wl,--defsym=__gentoo_check_ldflags__=0     -pthread test/CMakeFiles/test_perfdb.dir/perfdb.cpp.o -o bin/test_perfdb  lib/libMIOpen.so.1.0  --hip-link  --offload-arch=gfx1031  /usr/lib64/libamd_comgr.so.2.4  /usr/lib64/librocblas.so.0.1  /usr/lib64/libamdhip64.so.5.1  /usr/lib/clang/15.0.4/lib/linux/libclang_rt.builtins-x86_64.a  /usr/lib64/libboost_filesystem.so.1.80.0  /usr/lib64/libboost_atomic.so.1.80.0  -L/usr/lib64  -lsqlite3  -lm  -lz  /usr/lib64/librt.a
mold: error: undefined symbol: miopen::LockFilePath[abi:cxx11](boost::filesystem::path const&)
>>> referenced by perfdb.cpp
>>>               test/CMakeFiles/test_perfdb.dir/perfdb.cpp.o:(miopen::tests::DbTest::~DbTest())
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
```

2022-11-06 05:37 UTC, littlewu2508 commented
> ```shell
> LockFilePath
> ```

Confirmed that this is a mold bug

2022-11-06 22:16 UTC, jdkleuver commented
Is this a regression from my patches or did this exist previously?

2022-11-07 02:31 UTC, littlewu2508 commented
> Is this a regression from my patches or did this exist previously?

This is not related to your patches. Your patches looks good.

2022-11-07 02:48 UTC, littlewu2508 commented
Testing results is nice.

Since LLVM SLOT is switched, I think bumping the revision would be better, since llvm/clang is also a runtime dependency, so I can then bump sci-libs/roc-* to depend on llvm-15-based ROCm toolchains and close many old issues.

2022-11-07 03:13 UTC, jdkleuver commented
What do you mean by bumping revision? Sorry I am new to this

2022-11-07 03:23 UTC, littlewu2508 commented
> What do you mean by bumping revision? Sorry I am new to this

Rename `rocm-comgr-5.1.3-r1.ebuild` -> `rocm-comgr-5.1.3-r2.ebuild`, and `rocm-device-libs-5.1.3.ebuild` -> `rocm-device-libs-5.1.3-r1.ebuild`, etc.

2022-11-07 04:24 UTC, jdkleuver commented
> > What do you mean by bumping revision? Sorry I am new to this
> 
> Rename `rocm-comgr-5.1.3-r1.ebuild` -> `rocm-comgr-5.1.3-r2.ebuild`, and `rocm-device-libs-5.1.3.ebuild` -> `rocm-device-libs-5.1.3-r1.ebuild`, etc.

I have bumped the revision numbers

2022-11-08 16:32 UTC, littlewu2508 requested changes
Please add
`Bug: https://bugs.gentoo.org/857126`
to commit message, to reference this bug.

2022-11-09 02:38 UTC, littlewu2508 commented
LGTM

2022-11-09 02:40 UTC, littlewu2508 commented
@AndrewAmmerlaan Can you please take a quick look and merge this PR? I think it is in good shape now and testing looks well.

I also added my own Signed-off-by in 
[ROCm-LLVM-15-Signed-off-by-Yiyang-Wu.patch.gz](https://github.com/gentoo/gentoo/files/9966839/ROCm-LLVM-15-Signed-off-by-Yiyang-Wu.patch.gz)

2022-11-13 04:11 UTC, littlewu2508 commented
@heroxbd Can you take a quick look and merge this? Now Gentoo is on gcc-12 llvm-15, so this is becoming urgent.

2022-11-14 02:49 UTC, littlewu2508 commented
As https://bugs.gentoo.org/879907#c11 pointed out, upstream release 5.3.x already contain these patches. And 5.3.2 just released, meaning the 5.3.x series matured. So bumping version would be also a good way, I suppose.

2022-11-14 20:43 UTC, AndrewAmmerlaan commented
> @AndrewAmmerlaan Can you please take a quick look and merge this PR? I think it is in good shape now and testing looks well.
> 
> I also added my own Signed-off-by in [ROCm-LLVM-15-Signed-off-by-Yiyang-Wu.patch.gz](https://github.com/gentoo/gentoo/files/9966839/ROCm-LLVM-15-Signed-off-by-Yiyang-Wu.patch.gz)

I'm sorry, I no longer have the hardware to run and test rocm/hip stuff. Maybe you can ask around on IRC if there is anyone with amd hardware that can test and merge this?

2022-11-15 03:13 UTC, littlewu2508 commented
> I'm sorry, I no longer have the hardware to run and test rocm/hip stuff. Maybe you can ask around on IRC if there is anyone with amd hardware that can test and merge this?

I have already tested on my hardware. It's just I'm not Gentoo dev so I can't merge this.

2022-11-19 11:50 UTC, closed without merging