sys-cluster/rdma-core: set perldir
gentoo/gentoo pull request #28222
Opened 2022-11-11 10:36 UTC by Flowdalic

Closes: https://bugs.gentoo.org/876757
Signed-off-by: Florian Schmaus <flow@gentoo.org>

CC @gentoo/perl

2022-11-11 10:40 UTC, thesamesam commented
Looks fine (I've not verified that it works though).

Could I tempt you into writing a quick install-qa-check.d file for the repository to check for /usr/share/perl installation, as a followup? (See what @akhuettel thinks first.)

2022-11-12 15:47 UTC, akhuettel requested changes

2022-11-12 15:47 UTC, akhuettel commented on sys-cluster/rdma-core/rdma-core-42.0-r1.ebuild
> +		-DCMAKE_INSTALL_PERLDIR="${SITE_LIB}"
Should be VENDOR_LIB, otherwise OK

2022-11-12 19:27 UTC, Flowdalic commented on sys-cluster/rdma-core/rdma-core-42.0-r1.ebuild
> +		-DCMAKE_INSTALL_PERLDIR="${SITE_LIB}"
:+1:

2022-11-12 19:29 UTC, closed without merging