dev-util/makeheaders: bump, add myself as a maintainer
gentoo/gentoo pull request #28424
Opened 2022-11-25 11:36 UTC by BratishkaErik

Extracted from https://github.com/gentoo/gentoo/pull/28423
Confirmed to work with Clang 16 without changes

2022-12-04 06:11 UTC, BratishkaErik commented
ping

2022-12-12 08:51 UTC, ceamac requested changes

2022-12-12 08:51 UTC, ceamac commented on dev-util/makeheaders/makeheaders-20220411.ebuild
> +	$(tc-getCC) ${CFLAGS} ${CPPFLAGS} ${LDFLAGS} -o makeheaders "${DISTDIR}"/makeheaders-${PV}.c || die
```suggestion
	$(tc-getCC) ${CFLAGS} ${CPPFLAGS} ${LDFLAGS} -o makeheaders makeheaders-${PV}.c || die
```
We don't compile stuff directly from `${DISTDIR}`.  You can write a `src_unpack` function to copy all files from `${A}` to `${S}`, then you will have them available.

2022-12-12 08:51 UTC, ceamac commented on dev-util/makeheaders/makeheaders-20220411.ebuild
> +	local HTML_DOCS=( "${DISTDIR}"/makeheaders-${PV}.html )
`HTML_DOCS` should be at global scope (and also without `${DISTDIR}`).

2022-12-13 06:40 UTC, ceamac requested changes
Also if you could consider changing the name of the ebuild (actually the version).  This is a snapshot release, if you name it *-2022mmdd* and later upstream will make an official release, say *0.1* or *1.0*, you will have the users downgrade the package.

Please read the [file naming rules](https://devmanual.gentoo.org/ebuild-writing/file-format/#file-naming-rules) and especially the part about [snapshot releases](https://devmanual.gentoo.org/ebuild-writing/file-format/#snapshots-and-live-ebuilds)

Since we already have a *-0_p4*, my suggestion would be to name it *-0_p20220411*

2022-12-13 06:40 UTC, ceamac commented on dev-util/makeheaders/makeheaders-20220411.ebuild
> +	cp "${DISTDIR}"/makeheaders-${PV}.c "${DISTDIR}"/makeheaders-${PV}.html "${S}" || die
You could copy them without the version in the name, i.e., `"${S}"/makeheaders.{c,html}` - in this case the doc will have a normal name (the version is in the directory name anyway)

2022-12-13 18:24 UTC, ceamac approved these changes
Thank you for contributing

2022-12-13 18:28 UTC, closed without merging