Eclass whitelist update
gentoo/gentoo pull request #28787
Opened 2022-12-24 17:19 UTC by SoapGentoo

2022-12-24 17:37 UTC, thesamesam commented on eclass/alternatives.eclass
> -	pref=${ROOT%/}
Comment needs removing

2022-12-24 17:37 UTC, thesamesam commented on eclass/java-osgi.eclass
>  # must get Diego to commit something like this to portability.eclass
Convert into a professional TODO

2022-12-24 17:37 UTC, thesamesam commented on eclass/postgres-multi.eclass
>  postgres-multi_src_test() {
Move above, order is wrong

2022-12-24 17:37 UTC, thesamesam commented on eclass/selinux-policy-2.eclass
> +		emake NAME=$i SHAREDIR="${EPREFIX}"/usr/share/selinux -C "${S}"/${i} || die "${i} compile failed"
Drop die

2022-12-24 17:37 UTC, thesamesam commented on eclass/selinux-policy-2.eclass
> +		emake NAME=$i SHAREDIR="${EPREFIX}"/usr/share/selinux -C "${S}"/${i} || die "${i} compile failed"
Also iirc there's a bug to tag for this if you didn't already

2022-12-24 20:43 UTC, a17r commented on eclass/dune.eclass
> +BDEPEND="dev-ml/dune dev-lang/ocaml"
one line per dep?

2022-12-24 20:43 UTC, a17r commented on eclass/aspell-dict-r1.eclass
>  EXPORT_FUNCTIONS src_configure src_install
do we move these below inherit or at end of file now?

2022-12-24 20:43 UTC, a17r commented on eclass/linux-mod.eclass
> +	[ -d "${D}/lib/modules" ] && UPDATE_MODULEDB=true || UPDATE_MODULEDB=false
double brackets?

2022-12-24 20:43 UTC, a17r commented on eclass/usr-ldscript.eclass
> +				chmod u+w "${ED}/${libdir}/${tlib}" # needed to write to it
`|| die`?

2022-12-24 21:02 UTC, a17r requested changes

2022-12-24 21:02 UTC, a17r commented on eclass/fcaps.eclass
> +	   RDEPEND="filecaps? ( sys-libs/libcap )" ;;
slightly scruffy looking whitespace alignment here

2022-12-24 21:02 UTC, a17r commented on eclass/apache-2.eclass
>  		sed -i -e "/%%LOAD_MODULE%%/d" \
this one has a missing `|| die` at the end

2022-12-24 23:26 UTC, a17r approved these changes

2022-12-25 09:57 UTC, mgorny commented on eclass/apache-2.eclass
> -# polynomial-c@gentoo.org
I'm sorry for missing that during the retirement.

2022-12-25 09:57 UTC, mgorny commented on eclass/dune.eclass
> +	dev-ml/dune:="
These days, I think it's better to do:

```suggestion
RDEPEND="
	>=dev-lang/ocaml-4:=[ocamlopt?]
	dev-ml/dune:=
"
```

2022-12-25 09:57 UTC, mgorny commented on eclass/ninja-utils.eclass
> +	local nonfatal_args=( -n )
Inline it.

2022-12-25 12:18 UTC, mgorny reviewed
No more comments from me. By the way, @arthurzam mentioned that one of the Python eclasses (single-r1?) is ready too, so maybe include that as well with the big cache regen.

2022-12-25 16:47 UTC, thesamesam approved these changes

2022-12-25 19:13 UTC, arthurzam approved these changes
I've done one scan over all changes in this PR, and all look fine to me.
Did multiple passes at python eclasses, and also look fine.
Thank you @SoapGentoo

2022-12-26 09:44 UTC, ionenwks approved these changes
Haven't had time to look all that in-depth but still went over the changes and looks fine to me.

Thanks for doing this.

2022-12-26 13:47 UTC, ConiKost approved these changes
Ack. ```aspell-dict-r1.eclass``` lgtm. Thank you for your work.

2022-12-27 16:31 UTC, closed without merging