dev-cpp/valijson: bump to 1.0
gentoo/gentoo pull request #29227
Opened 2023-01-23 11:04 UTC by hhoffstaette

This also removes the test support since upstream has removed the vendored test dependencies from the tarball in favor of git submodules.

Closes: https://bugs.gentoo.org/891683
Signed-off-by: Holger Hoffstätte <holger@applied-asynchrony.com>

2023-01-23 11:11 UTC, hhoffstaette commented
I removed the Closes: tag in order to keep the bug open until stabilization.

2023-02-01 10:24 UTC, hhoffstaette commented
@thesamesam Can I have a bump? The version change is mostly formal and has no compatibility implications, just getting in line with some fixes & comments from upstream.
The loss of tests is IMHO silly but nothing I can do about right now.

2023-02-08 10:34 UTC, ceamac requested changes
A few small changes, looks good otherwise.

Thank you!

2023-02-08 10:34 UTC, ceamac commented on dev-cpp/valijson/valijson-1.0.ebuild
> +IUSE=""
Please remove empty `IUSE`

2023-02-08 10:34 UTC, ceamac commented on dev-cpp/valijson/files/1.0-fix-macro-typos.patch
> +From f1ff3518281fe347c97b78384d6bb645dbdd4788 Mon Sep 17 00:00:00 2001
Can you also add the link where this patch originates from?  It is a github commit, but a link is better.

2023-02-08 10:34 UTC, ceamac commented on dev-cpp/valijson/valijson-1.0.ebuild
> +LICENSE="BSD-2"
There is one file licensed under `Boost-1.0`, please update

2023-02-08 11:13 UTC, hhoffstaette commented
Thank you for having a look, I had almost forgotten about it. :sweat: 
All the mentioned issues are resolved.

2023-02-08 12:16 UTC, ceamac approved these changes

2023-02-08 12:22 UTC, closed without merging

2023-02-08 12:24 UTC, ceamac commented
I added a Bug: tag instead of the Closes: you removed, so the commit can be seen in the bug.