mate-base/mate-applets: add 1.26.1
gentoo/gentoo pull request #29278
Opened 2023-01-26 12:08 UTC by oz123

Signed-off-by: Oz Tiram <oz.tiram@gmail.com>

2023-01-26 12:48 UTC, scardracs requested changes

2023-01-26 12:48 UTC, scardracs commented on mate-base/mate-applets/mate-applets-1.26.1.ebuild
> +fi
As asked for x11-wm/marco

2023-01-27 22:34 UTC, oz123 commented on mate-base/mate-applets/mate-applets-1.26.1.ebuild
> +EAPI=7
Still not possible to do this. I'd like to test eapi 8 bump in the eclass before I bump in the ebuilds.

2023-01-27 22:35 UTC, oz123 commented on mate-base/mate-applets/mate-applets-1.26.1.ebuild
> +fi
Done.

2023-05-05 04:39 UTC, closed without merging