media-sound/sndio: Add 1.9.0
gentoo/gentoo pull request #29280
Opened 2023-01-26 13:45 UTC by Marinapig

Signed-off-by: Henry Ford fordhenry2299@gmail.com

2023-01-27 17:15 UTC, scardracs commented
Please drop https://github.com/gentoo/gentoo/pull/29280/commits/b74cf98559610c2d5582037ca651f28508fd9f54 as it will be a pain in ass during merge. Prefer git rebase master instead of git merge master

2023-01-27 17:17 UTC, scardracs requested changes

2023-01-27 17:17 UTC, scardracs commented on media-sound/sndio/sndio-1.9.0.ebuild
> +# Copyright 2020-2022 Gentoo Authors
1999-2023

2023-01-27 17:17 UTC, scardracs commented on media-sound/sndio/sndio-1.9.0.ebuild
> +EAPI=7
EAPI=8

2023-01-27 17:17 UTC, scardracs commented on media-sound/sndio/sndio-1.9.0.ebuild
> +fi
As this package has live ebuild too please bump it with changes I'm listing

2023-01-27 22:06 UTC, Marinapig commented
Got rid of that merge and integrated your changes

2023-01-27 22:08 UTC, scardracs commented on media-sound/sndio/sndio-1.9.0.ebuild
> +# Copyright 1999-2022 Gentoo Authors
Sorry, I meant 2020-2023

2023-01-27 22:08 UTC, scardracs commented on media-sound/sndio/sndio-9999.ebuild
> +# Copyright 1999-2022 Gentoo Authors
Same

2023-01-28 10:03 UTC, scardracs commented
LGTM, anyway you have to wait for a dev for merge (I'm not one).

2023-02-09 13:30 UTC, juippis commented on media-sound/sndio/sndio-1.9.0.ebuild
> +	|| die "Configure failed"
You can use `econf` here. Also an array form is better.

2023-02-10 16:38 UTC, lanodan commented
>You can use `econf` here.

Nope.
It's not an autotools-style ./configure so some of the arguments econf uses do not work.

> Also an array form is better.

:shrug:

2023-02-11 11:13 UTC, juippis approved these changes

2023-02-11 11:16 UTC, closed without merging