dev-python/rstcheck: Update to release 6.1.1
gentoo/gentoo pull request #29335
Opened 2023-01-30 02:39 UTC by samuelbernardo

Apply review suggestions from PR
https://github.com/gentoo/gentoo/pull/16399

Signed-off-by: Samuel Bernardo <samuelbernardo.mail@gmail.com>

2023-02-06 00:49 UTC, jonasstein commented
if you add
`Closes: https://bugs.gentoo.org/893326`
to the git comment, we will not forget to close the ticket.

2023-02-06 00:52 UTC, samuelbernardo commented
> if you add `Closes: https://bugs.gentoo.org/893326` to the git comment, we will not forget to close the ticket.

Done

2023-03-28 15:31 UTC, mgorny requested changes

2023-03-28 15:31 UTC, mgorny commented on dev-python/rstcheck/metadata.xml
> +  <upstream>
It seems like a reasonable package, please add python@ as co-maintainer.

2023-03-28 15:31 UTC, mgorny commented on dev-python/rstcheck/rstcheck-6.1.1.ebuild
> +HOMEPAGE="https://github.com/rstcheck/rstcheck"
Add pypi too.

2023-03-28 15:31 UTC, mgorny commented on dev-python/rstcheck/rstcheck-6.1.1.ebuild
> +inherit distutils-r1
Use pypi.eclass.

2023-03-28 15:31 UTC, mgorny commented on dev-python/rstcheck/rstcheck-6.1.1.ebuild
> +RDEPEND="dev-python/docutils[${PYTHON_USEDEP}]"
Use the multi-line format for all dependencies to make diffs for future updates cleaner.

2023-03-28 15:31 UTC, mgorny commented on dev-python/rstcheck/rstcheck-6.1.1.ebuild
> +	pytest -vv --ignore=rst --override-ini="addopts=--doctest-modules" \
epytest.

2023-03-28 15:31 UTC, mgorny commented on dev-python/rstcheck/rstcheck-6.1.1.ebuild
> +		${RDEPEND}
distutils_enable_tests already does that.

2023-10-18 04:47 UTC, samuelbernardo commented
Just upgraded to 6.2.0 in guru... I need to update ebuild with suggested changes from here and create a new PR.

2023-10-18 04:47 UTC, closed without merging