dev-libs/capstone: don't install static libraries unconditionally
gentoo/gentoo pull request #29350
Opened 2023-01-30 23:04 UTC by hamarituc

Closes: https://bugs.gentoo.org/890941
Signed-off-by: Mario Haustein <mario.haustein@hrz.tu-chemnitz.de>

2023-02-15 13:20 UTC, ceamac requested changes

2023-02-15 13:20 UTC, ceamac commented on dev-libs/capstone/capstone-5.0_rc2-r3.ebuild
> +S=${WORKDIR}/${P/_rc/-rc}
Please move `S` below `SRC_URI`

2023-02-15 13:20 UTC, ceamac commented on dev-libs/capstone/capstone-5.0_rc2-r3.ebuild
> +		find "${D}" -name '*.a' -delete || die
```suggestion
		find "${ED}" -name '*.a' -delete || die
```

2023-02-15 13:21 UTC, ceamac commented
I searched reverse dependencies that may need changing to use `static-libs`, I think only `app-emulation/qemu` qualifies.

2023-02-16 18:29 UTC, hamarituc commented on dev-libs/capstone/capstone-5.0_rc2-r3.ebuild
> +		find "${D}" -name '*.a' -delete || die
fixed

2023-02-16 18:29 UTC, hamarituc commented on dev-libs/capstone/capstone-5.0_rc2-r3.ebuild
> +S=${WORKDIR}/${P/_rc/-rc}
fixed

2023-02-17 10:58 UTC, ceamac approved these changes
Will merge this later, with qemu

2023-02-17 17:27 UTC, closed without merging