net-im/dino: add 0.4.0
gentoo/gentoo pull request #29762
Opened 2023-02-24 10:08 UTC by jubalh

2023-02-25 15:24 UTC, a17r requested changes

2023-02-25 15:24 UTC, a17r commented on net-im/dino/dino-0.4.0.ebuild
> +	gui-libs/gtk:4
That looks like it needs some new sorting after the category change

2023-02-25 15:24 UTC, a17r commented on net-im/dino/dino-0.4.0.ebuild
> +	notification-sound? ( media-libs/libcanberra:0[sound] )
Line should be before omemo (per alphanumerical sorting)

2023-02-25 15:24 UTC, a17r commented on net-im/dino/dino-0.4.0.ebuild
> +	local mycmakeargs+=(
```suggestion
	local mycmakeargs=(
```

2023-02-26 11:20 UTC, a17r requested changes
Now that I'm not reviewing on my mobile:

``-- Could NOT find WebRTCAudioProcessing (missing: WebRTCAudioProcessing_LIBRARY) (Required is at least version "0.2")``

Do we have an automagic dependency here?

2023-02-26 11:20 UTC, a17r commented on net-im/dino/dino-0.4.0.ebuild
> +	>=gui-libs/libadwaita-1.2.0:1
spotted a trailing space there

2023-02-26 11:20 UTC, a17r commented on net-im/dino/dino-9999.ebuild
> +	gui-libs/gtk:4
forward 0.4.0 review here too please ;)

2023-02-26 11:20 UTC, a17r commented on net-im/dino/dino-0.4.0.ebuild
> +	dev-libs/icu
requires `:=` slot operator like every other icu revdep to trigger rebuild on ICU slot bumps.

2023-02-26 11:20 UTC, a17r commented on net-im/dino/dino-0.4.0.ebuild
> +		media-gfx/qrencode
missing `:=` slot operator on both deps here too

2023-03-03 09:38 UTC, jubalh commented
> Do we have an automagic dependency here?

I decided to disable this for now since I don't use videocalls myself and don't know much about them.
If anybody else wants this I think they need to add the webrtc useflag, enable the `rtp` build option and add the dependencies mentioned in https://github.com/dino/dino/blob/master/plugins/rtp/CMakeLists.txt

2023-03-07 10:42 UTC, jubalh commented
Is this good to go?

2023-03-07 20:19 UTC, a17r commented
Forgot to mention that it makes sense to search on bugzilla for already reported bugs, I would add this to the commit summary:

Bug: https://bugs.gentoo.org/851765
Closes: https://bugs.gentoo.org/869971

Not sure what to make of that, and why gst-plugins-base is only in DEPEND:
https://bugs.gentoo.org/893854

2023-03-07 23:31 UTC, jubalh commented
Ok mentioned the two bugs :)

2023-03-11 16:26 UTC, closed without merging