Reintroduce game-engines/renpy
gentoo/gentoo pull request #29795
Opened 2023-02-25 20:55 UTC by lanodan

RenPy 8 got released and is based on Python3 with compatibility for previous games.

This was in my overlay and been using it for some months.

- dev-python/pygame_sdl2: add 8.0.2.22081402
- profiles: Only mask old dev-python/pygame_sdl2
- games-engines/renpy: new package, add 8.0.3

2023-03-05 03:34 UTC, thesamesam requested changes

2023-03-05 03:34 UTC, thesamesam commented on dev-python/pygame_sdl2/pygame_sdl2-8.0.2.22081402.ebuild
> +EAPI=7
8, please

2023-03-05 03:34 UTC, thesamesam commented on dev-python/pygame_sdl2/pygame_sdl2-8.0.2.22081402.ebuild
> +PYTHON_COMPAT=( python3_{8,9,10} )
8 is gone and a noop. Also, no 3.11?

2023-03-05 03:34 UTC, thesamesam commented on dev-python/pygame_sdl2/pygame_sdl2-8.0.2.22081402.ebuild
> +inherit distutils-r1
No PEP517?

2023-03-05 03:34 UTC, thesamesam commented on dev-python/pygame_sdl2/pygame_sdl2-8.0.2.22081402.ebuild
> +IUSE=""
Drop

2023-03-05 03:34 UTC, thesamesam commented on games-engines/renpy/files/renpy-6.99.12.4-compat-infinite-loop.patch
> +Adapted from git HEAD:
Link to the source please.

2023-03-05 03:34 UTC, thesamesam commented on games-engines/renpy/files/renpy-6.99.12.4-compat-style.patch
> +commit 1d350d993d2b51df7880e92b48ed103e059ec385
Link to the source please.

2023-03-05 03:34 UTC, thesamesam commented on games-engines/renpy/files/renpy-8.0.3-use-system-fribidi.patch
> +--- renpy-7.3.5-source.orig/module/setup.py	2019-08-09 05:11:58.000000000 +0300
scrub-patch (iwdevtools)

2023-03-05 03:34 UTC, thesamesam commented on games-engines/renpy/files/renpy.1
> +.\" Copyright © 2015 Andrew Savchenko
This should really be sent upstream.

2023-03-05 03:34 UTC, thesamesam commented on games-engines/renpy/renpy-8.0.3.ebuild
> +EAPI=7
- EAPI 8
- Drop Python 3.8 (it does nothing now)
- Add Python 3.11? See gentoo-dev ML too.

2023-03-24 08:13 UTC, bircoph commented
Hi!

I bumped pygame_sdl2 to 8.0.3. Could you please rebase and check that renpy-8.0.3 builds/works fine with it? I had to change build tag from "-for-renpy-8.0.3" to "+renpy8.0.3" to conform to PEP 440, see Gentoo bug 892347.

2023-03-24 08:17 UTC, bircoph commented
You can also submit patches/updates through Gentoo bugzilla or e-mail to me if you don't like Github as I can see from your profile. Frankly, I missed this update as I rarely use Github for Gentoo.

Would you like to proxy-maint renpy in Gentoo? I don't have enough time to update and test it thoroughly these days, but I can try to proxy your contributions.

2023-04-14 13:17 UTC, lanodan commented
>I bumped pygame_sdl2 to 8.0.3. Could you please rebase and check that renpy-8.0.3 builds/works fine with it? I had to change build tag from "-for-renpy-8.0.3" to "+renpy8.0.3" to conform to PEP 440, see Gentoo bug 892347.

Sadly setuptools also broke the way headers are installed in the process…

``/usr/include/python3.10/pygame_sdl2/pygame_sdl2.h`` (seems correct) vs. ``/usr/lib/python3.10/site-packages/pygame_sdl2-2.1.0.data/headers/pygame_sdl2.h``

Renpy uses ``#include <pygame_sdl2/pygame_sdl2.h>``

> You can also submit patches/updates through Gentoo bugzilla or e-mail to me if you don't like Github as I can see from your profile. Frankly, I missed this update as I rarely use Github for Gentoo.
> Would you like to proxy-maint renpy in Gentoo? I don't have enough time to update and test it thoroughly these days, but I can try to proxy your contributions.

I guess I could CC you on patches to gentoo-proxy-maint@ for next versions.

2023-08-07 04:45 UTC, thesamesam commented
Could you rebase this to drop the pygame_sdl2 bit? That's fixed upstream now thanks to Eli.

Also, please update to latest renpy version. Hopefully the future dep is gone then..

2023-08-07 10:05 UTC, lanodan commented
[2023-08-07 04:45:48+0000] Sam James:
>Could you rebase this to drop the pygame_sdl2 bit? That's fixed upstream now thanks to Eli.

Nice, shouldn't pygame_sdl2 get a revbump which adds DEPEND=">=dev-python/wheel-0.41.0"?

> Hopefully the future dep is gone then..

I doubt that's going to happen, AFAIK renpy8 uses it to be compatible with prior games written with python2.

2023-12-21 12:44 UTC, closed without merging