app-vim/*: EAPI8 bumps
gentoo/gentoo pull request #30077
Opened 2023-03-12 15:54 UTC by mm1ke

Hi,

This are some simple EAPI8 bumps for app-vim plugins. Also updates `bufexplorer` to the latest version and removes the live ebuild (i guess it's not really relevant here).
Please review.

2023-03-17 16:46 UTC, SoapGentoo requested changes

2023-03-17 16:46 UTC, SoapGentoo commented on app-vim/csscomplete/csscomplete-1.0-r1.ebuild
> +S="${WORKDIR}/${PN}.vim-${PV}"
put this right after `SRC_URI`

2023-03-17 16:46 UTC, SoapGentoo commented on app-vim/csound-syntax/csound-syntax-20160804.ebuild
> +HOMEPAGE="https://github.com/luisjure/csound-vim"
```suggestion
HOMEPAGE="https://github.com/luisjure/csound-vim"

```

2023-03-17 16:46 UTC, SoapGentoo commented on app-vim/csound-syntax/csound-syntax-20160804-r1.ebuild
> +HOMEPAGE="https://github.com/luisjure/csound-vim"
```suggestion
HOMEPAGE="https://github.com/luisjure/csound-vim"

```

2023-03-17 16:46 UTC, SoapGentoo commented on app-vim/cmdalias/cmdalias-3.0-r2.ebuild
> +HOMEPAGE="https://www.vim.org/scripts/script.php?script_id=746"
```suggestion
HOMEPAGE="https://www.vim.org/scripts/script.php?script_id=746"

```

2023-03-17 16:46 UTC, SoapGentoo commented on app-vim/cctree/cctree-1.61-r2.ebuild
> +HOMEPAGE="https://sites.google.com/site/vimcctree/"
```suggestion
HOMEPAGE="https://sites.google.com/site/vimcctree/"

```

2023-03-17 16:46 UTC, SoapGentoo commented on app-vim/calendar/calendar-2.9-r2.ebuild
> +HOMEPAGE="https://www.vim.org/scripts/script.php?script_id=52"
```suggestion
HOMEPAGE="https://www.vim.org/scripts/script.php?script_id=52"

```

2023-03-17 16:46 UTC, SoapGentoo commented on app-vim/bufexplorer/bufexplorer-7.4.25.ebuild
> +SRC_URI="https://github.com/jlanzarotta/${PN}/archive/v.${PV}.tar.gz -> ${P}.tar.gz"
```suggestion
SRC_URI="https://github.com/jlanzarotta/${PN}/archive/v.${PV}.tar.gz -> ${P}.tar.gz"

```

2023-03-17 16:46 UTC, SoapGentoo commented on app-vim/bnf-syntax/bnf-syntax-1.2-r3.ebuild
> +HOMEPAGE="https://www.vim.org/scripts/script.php?script_id=250"
```suggestion
HOMEPAGE="https://www.vim.org/scripts/script.php?script_id=250"

```

2023-03-17 16:46 UTC, SoapGentoo commented on app-vim/alternate/alternate-2.18-r3.ebuild
> +
```suggestion
```

2023-03-17 16:46 UTC, SoapGentoo commented on app-vim/alternate/alternate-2.18-r3.ebuild
> +S="${WORKDIR}/a.vim-${PV}"
right after `SRC_URI`

2023-03-17 17:44 UTC, mm1ke commented
@SoapGentoo thanks for the review :) I've updated all your suggestions.

2023-03-19 17:39 UTC, mm1ke commented
I've updated most vim plugin for `EAPI8` now. Some ebuilds, which have only unstable keywords, were updated directly to `EAPI8`. I've also made a few version bumps.

2023-09-14 21:23 UTC, closed without merging