dev-util/gnome-builder: Version bump to 44_rc BETA, new dev-libs/libdex, bump dev-libs/jsonrpc-gli, gui-libs/gtksourceview, gui-libs/libpanel
gentoo/gentoo pull request #30124
Opened 2023-03-14 14:09 UTC by flint2

Work in Progress, do not merge, depend on webkitgtk

2023-03-14 18:06 UTC, mattst88 commented
libpanel's dependencies need to be updated.

2023-03-14 18:25 UTC, flint2 commented
> libpanel's dependencies need to be updated.

Done in https://github.com/gentoo/gentoo/pull/30124/commits/2cda3ab2632c2f0b9822de899611658362fa1310
Thanks!

2023-03-15 22:22 UTC, flint2 commented
gnome-builder-44.rc compiles ok with webkit-gtk-2.39.7-r600 (https://github.com/gentoo/gentoo/pull/30124/commits/c2347daca46ae9b6c87a5d1b815508de3e324b83)
- detection is ok :
WebKit ................ : true (webkitgtk-6.0)
- build is ok
- test is ok
Ok:                 21  

Works ok, used to open and compile gnome-calendar project

2023-03-18 03:52 UTC, mattst88 commented
I've got webkit-gtk 2.40.0 building locally. I expect to have it in the tree tomorrow and then I'll merge the rest of this. Thanks!

2023-03-18 03:55 UTC, flint2 commented
> to have it in the tree tomorrow and then I'll

Totally missed the release because I´m focused in Gnome https://download.gnome.org/sources/?C=M&O=D

Thanks!

2023-03-18 17:36 UTC, flint2 commented
> I've got webkit-gtk 2.40.0 building locally. I expect to have it in the tree tomorrow and then I'll merge the rest of this. Thanks!

Just submitted a PR for epiphany https://github.com/gentoo/gentoo/pull/30214
Now I´m planning to test gnome-builder

2023-03-20 14:12 UTC, mattst88 commented on dev-libs/libdex/libdex-0.2.0.ebuild
> +	>=dev-libs/glib-2.68:2
After glib, I see this:

````
if host_machine.system() == 'linux'
  liburing_req_version = '0.7'
  liburing_req = '>= @0@'.format(liburing_req_version)
  liburing_dep = dependency('liburing', version: liburing_req, required: false)

  if liburing_dep.found()
    config_h.set10('HAVE_LIBURING', true)
  endif
else
  liburing_dep = disabler()
endif
````

Let's just require `sys-libs/liburing` unconditionally.

Following that, I see

````if get_option('sysprof')
  libsysprof_capture_dep = dependency('sysprof-capture-4')
  config_h.set10('HAVE_SYSPROF', true)
endif
````

so I think we should have `IUSE=sysprof` and a dependency on `dev-util/sysprof-capture`.

2023-03-20 14:17 UTC, mattst88 commented on dev-libs/libdex/libdex-0.2.0.ebuild
> +	dev-libs/json-glib[introspection?]
I'd suggest installing and enabling `app-portage/iwdevtools`. When a package is merged, it checks dependencies and prints things like this:

````
 * VDB: detected possibly incorrect RDEPEND (dev-libs/libdex-0.2.0)
 * dev-libs/gobject-introspection:= < 
 * dev-libs/json-glib               < 
 *                                  > sys-libs/liburing:=
````

It's not 100% accurate, but it does a pretty good job.

2023-03-20 14:21 UTC, mattst88 requested changes
Looks really good. Nice work!

2023-03-20 21:45 UTC, flint2 commented on dev-libs/libdex/libdex-0.2.0.ebuild
> +	dev-libs/json-glib[introspection?]
> > Work in Progress, do not merge, not compiling
> 
> Is this the error you saw?
> 
> ```
> ../gnome-builder-44.0/src/libide/gui/ide-application-tweaks.c: In function ‘create_plugin_toggle’:
> ../gnome-builder-44.0/src/libide/gui/ide-application-tweaks.c:65:3: error: implicit declaration of function ‘adw_expander_row_add_suffix’; did you mean ‘adw_expander_row_add_prefix’? [-Werror=implicit-function-declaration]
>    65 |   adw_expander_row_add_suffix (row, GTK_WIDGET (toggle));
>       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
>       |   adw_expander_row_add_prefix
> ../gnome-builder-44.0/src/libide/gui/ide-application-tweaks.c:65:3: warning: nested extern declaration of ‘adw_expander_row_add_suffix’ [-Wnested-externs]
> cc1: some warnings being treated as errors
> ```
> 
> If so, looks like it should be fixed by https://gitlab.gnome.org/GNOME/gnome-builder/-/commit/d89a5c95e43f4a4e1a4e9d063e3962bac8e51db0

Now with 44.1 is compiling OK, Ready for review

2023-03-20 22:06 UTC, closed without merging