media-libs/aalib: revbump to fix undefined behavior
gentoo/gentoo pull request #3058
Opened 2016-12-08 12:25 UTC by tharvik

During build, gcc generate this error and using `FEATURES=stricter`, it fails to merge
```
 * QA Notice: Package triggers severe warnings which indicate that it
 *            may exhibit random runtime failures.
 * /var/tmp/portage/media-libs/aalib-1.4_rc5-r6/work/aalib-1.4.0/src/aalinuxkbd.c:171:14: warning: iteration 128u invokes undefined behavior [-Waggressive-loop-optimizations]
```

There is also this message, but `media-libs/aalib` seems pretty dead development wise (15 years without release) and there is already a patchset in the tree
```
 * Please do not file a Gentoo bug and instead report the above QA
 * issues directly to the upstream developers of this software.
 * Homepage: http://aa-project.sourceforge.net/aalib/
```

So here goes a revdump with a patch, tested with `app-misc/bb` (but might need other tests)

The patch itself is simply a memset instead of a loop (not necessary but easier to read), and the range was reduced from 256 (current value of `NR_KEYS`) to 128 (the usable and used range)

2016-12-19 10:50 UTC, aballier requested changes

2016-12-19 10:50 UTC, aballier commented on media-libs/aalib/files/aalib-1.4_rc6-key-down-OOB.patch
> ++    memset(key_down, 0, NR_KEYS & 0xFF);
Didn't you write that NR_KEYS is 256 ?
That'd reduce to '0x100 & 0xFF', which is 0, so basically making this function a no-op.

2016-12-19 11:47 UTC, tharvik commented on media-libs/aalib/files/aalib-1.4_rc6-key-down-OOB.patch
> ++    memset(key_down, 0, NR_KEYS & 0xFF);
You're correct, fixed.

2016-12-23 18:57 UTC, merged

2016-12-23 18:59 UTC, trofi commented
Good catch! Apologies for the delay. I've messed up my email filtering on github/gentoo notifications.