net-voip/murmur: Fix default config and OpenRC files
gentoo/gentoo pull request #30788
Opened 2023-04-28 12:18 UTC by DarkDefender

@0xC0ncord I've done the fixes that I pointed out in https://github.com/gentoo/gentoo/pull/29194

I was going to also update the live ebuild, but I noticed that they have revamped how they do the config files.
There is no `mkini.sh` script anymore and they moved most config things to the `auxiliary_files/` directory.
In addition to this, it seems like the systemd files are not handled by cmake.

So I didn't want to do a update for that without consulting you first.
What are your plans for murmur/mumble >=1.5.0?
On the server side, seems like they have done a lot of cleanup so now there is no trace left of "murmur" anymore and everything seem to be "mumble-server" now.

2023-04-28 12:25 UTC, DarkDefender commented
When this is merged, #29194 can be closed as well I've modified the post install message to be more clear as well.

2023-05-03 15:55 UTC, DarkDefender commented
Sounds good to me! :)

Do you want me to take a look at the live ebuild as well or should we just merge this for 1.4.x release?

2023-05-03 17:44 UTC, 0xC0ncord commented
> Do you want me to take a look at the live ebuild as well or should we just merge this for 1.4.x release?

If you would like to please go ahead! It will make the 1.5.0 upgrade smoother when it lands. The live ebuild should still be functional although I haven't tested it in a couple months.

Many thanks for your work on this! :)

2023-06-01 10:43 UTC, DarkDefender commented
The systemd install path issues seem to be related the build system itself. There is a pull request that fixes it for me:
https://github.com/mumble-voip/mumble/pull/6100

2023-11-13 12:07 UTC, DarkDefender commented
@0xC0ncord The build system update for the live ebuild still hasn't been merged yet.
Should I perhaps include that as a patch for the live ebuild or should we just drop the live ebuild update until it is merged?

We could also apply the WIP updates as is as they don't make the ebuild any worse functionality wise.

2023-11-20 11:32 UTC, DarkDefender commented
Let me explain the last three commits.

The first one is a fix for a zeroconf mistake in the initd files.

The new one updates the live ebuild to build and work correctly with openrc installs.

The last one is a commit that pulls in the WIP build system changes that will fix the systemd install files for us.
Perhaps we could include these as a patch instead?

2024-01-01 21:21 UTC, DarkDefender commented
@0xC0ncord the build system changes needed for the live ebuild has been merged into the mumble master branch.
I updated the live ebuild.

I think this is ready for merging. If you think so as well, I will clean up and squash the commits.

2024-01-04 20:12 UTC, 0xC0ncord requested changes
Overall looks good! I haven't tested this just yet, but I found a couple minor typos and missing failsafes.

Thanks for your continued work on this. :)

2024-01-04 20:12 UTC, 0xC0ncord commented on net-voip/murmur/murmur-9999.ebuild
> +The defualt 'SuperUser' password will be written into the log file
default*

2024-01-04 20:12 UTC, 0xC0ncord commented on net-voip/murmur/murmur-9999.ebuild
> +If you want to maunally set a password yourself, please execute:
manually*

2024-01-04 20:12 UTC, 0xC0ncord commented on net-voip/murmur/murmur-9999.ebuild
> +This will set the build-in 'SuperUser' password to '<pw>' when starting murmur.
built-in*

2024-01-04 20:12 UTC, 0xC0ncord commented on net-voip/murmur/murmur-9999.ebuild
> +	grep -r -l _mumble-server auxiliary_files/ | xargs sed -i 's/_mumble-server/murmur/g'
This needs to be wrapped in `|| die` in case this fails.

2024-01-04 20:12 UTC, 0xC0ncord commented on net-voip/murmur/murmur-9999.ebuild
> +	cp "${FILESDIR}"/murmur.initd-r2 "${T}"/murmur.initd
Also need a `|| die` here.

2024-01-04 20:46 UTC, 0xC0ncord commented
I want to reiterate that I plan to have the `murmur` package renamed to `mumble-server` when the next stable version of it is released. That will involve undoing a lot of these stopgap changes where we are renaming back "mumble-server" to "murmur".

2024-01-05 16:02 UTC, DarkDefender commented
> I want to reiterate that I plan to have the `murmur` package renamed to `mumble-server` when the next stable version of it is released. That will involve undoing a lot of these stopgap changes where we are renaming back "mumble-server" to "murmur".

Yepp, I know :)

That is why I didn't convert all instances of "mumble-server" to "murmur" as I think that would be more work than it is worth.
It also makes it a lot easier to convert the ebuild to be `mumble-server` with hopefully nothing more than a `s/murmur/mumble-server/g`.

2024-01-19 15:16 UTC, 0xC0ncord requested changes
Looks good after testing! Just some last minute cleanup and I think it's ready.

After addressing the review comments please squash your commits into two different commits, one which fixes up the live ebuild and one which adds version `1.4.287-r2`. Please make sure to add the package prefix to the commit summary, e.g.:

```
net-voip/murmur: update live ebuild
net-voip/murmur: add 1.4.287-r2
```

You can leave the old commit summaries in the commits' long descriptions so we know what was changed. ;)

Thanks!

2024-01-19 15:16 UTC, 0xC0ncord commented on net-voip/murmur/murmur-1.4.287-r2.ebuild
> +# Copyright 1999-2022 Gentoo Authors
Please update the copyright year to 1999-2024.

2024-01-19 15:16 UTC, 0xC0ncord commented on net-voip/murmur/murmur-1.4.287-r2.ebuild
> +	KEYWORDS="amd64 ~arm ~arm64 x86"
For the new 1.4.287-r2 version, change `KEYWORDS` to `"~amd64 ~arm ~arm64 ~x86"` so we're not committing this new version straight to stable (it needs time in testing first).

2024-01-19 17:09 UTC, DarkDefender commented
I noticed that I needed to add `3rdparty/cmake-compiler-flags` to `EGIT_SUBMODULES` to get both the live build of murmur and mumble to build.

Is this something you want to take care of or investigate yourself?

2024-01-20 00:12 UTC, 0xC0ncord commented
> I noticed that I needed to add `3rdparty/cmake-compiler-flags` to `EGIT_SUBMODULES` to get both the live ebuild of murmur and mumble to build.
> 
> Is this something you want to take care of or investigate yourself?

I just took a quick look at it and it seems fine -- it's not a library or anything, just some CMake utility functions I assume the build system is now using.

2024-01-26 14:06 UTC, DarkDefender commented
I think this should be ready for merging now.

2024-02-07 11:27 UTC, DarkDefender commented
@0xC0ncord anything holding this up?

2024-02-09 10:08 UTC, DarkDefender commented
Fixed the missing unstable keyword :)

2024-02-09 14:41 UTC, closed without merging

2024-02-09 14:48 UTC, 0xC0ncord commented
All done. Thanks for your patience and dedication to getting fixing this up. :)