net-wireless/wireless-regdb: update 20230503, 20230213, 20220812
gentoo/gentoo pull request #31514
Opened 2023-06-17 16:23 UTC by negril

Implemented changes proposed in https://github.com/gentoo/gentoo/pull/31509#pullrequestreview-1484833642

Add blocker on net-wireless/crda, as it's no longer needed for >=kernel-4.15, and remove special treatment for it. See https://bugs.gentoo.org/693120.

Recompile regulatory.bin from db.txt.

Copy kernel config_check from net-wireless/iwd to ensure loading.

Bug: https://bugs.gentoo.org/898162

2023-06-17 16:28 UTC, ZeroChaos- requested changes
Check out what I did in the Pentoo overlay to maintain crda support please.

2023-06-17 16:38 UTC, negril commented
Is there a use case for crda? If there is, I can add a use-flag for crda.

2023-06-17 16:41 UTC, thesamesam commented
> Check out what I did in the Pentoo overlay to maintain crda support please.

You maintain crda in gentoo, is there a reason you didn't do it in ::gentoo?

2023-06-17 17:46 UTC, ZeroChaos- commented
> > Check out what I did in the Pentoo overlay to maintain crda support please.
> 
> You maintain crda in gentoo, is there a reason you didn't do it in ::gentoo?

Yes, back when there were other maintainers they didn't like the idea.  That time has long passed so I see no reason not to move that work into Gentoo.  I would do it right now but I am away from my computer the next few days.  In the mean time I simply don't want this merged and to break the crda use cases.

2023-06-17 17:50 UTC, ZeroChaos- commented
> Is there a use case for crda? If there is, I can add a use-flag for crda.

Yes, the use case for crda is that it can dynamically reload new wireless-regdb without rebuilding the whole kernel.  I know some folks change their kernel much more often than their regdb but there are use cases for rebuilding and updating the regdb which I would like to keep.  A hard blocker is a no, I am not even sure I am okay with a default off use flag unless the check for building the wireless regdb and key in as firmware actually works right.

2023-06-17 17:51 UTC, negril commented
Sounds good enough for me. Will adjust.

2023-06-17 18:43 UTC, negril commented
`net-wireless/iw` supports reloading the regulatory database as per https://patchwork.kernel.org/project/linux-wireless/patch/20180509153620.23630-1-seth.forshee@canonical.com/ with a call to `iw reg reload`.

So I don't see a need to support `net-wireless/crda`.

2023-06-17 18:55 UTC, ZeroChaos- commented
I agree to a non-default use flag in that case. Thanks for finding that.  I still don't want a blocker though, crda is on most Gentoo systems and I will probably have to adjust other wireless things with this change.  I also respectfully request a bit of testing time to make sure the checks are all good and we don't need any other ones.  I am not home till Monday so some time this week I will have this tested.

2023-06-18 09:48 UTC, negril commented
Further reading:

https://devel.fedoraproject.narkive.com/sIhqEvpX/fedora-crda-to-wireless-regdb-upgrade
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1958918
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1003903

In short, crda was a helper util to load the regdb. It got replaced in 4.15 by in kernel facilites and is no longer useful because of it's limitations.

In short it's deprecated software should no longer be used, that needs to go and will be removed with the last kernels 4.14 LTS kernels in January 2024.

2023-06-19 18:59 UTC, ZeroChaos- commented
@negril I'm back at my desk.  I really appreciate your work here.  I'm not going to let this drop, give me a little time to review this, because there are quite a few other packages.  All of this looks good, except the block on crda.

The blocker on crda makes no sense for a lot of reasons.  The main one being that the ebuilds are still installing files that only crda reads...  Please make a use flag for crda which removed the dep and doesn't install the files for crda when it's not set.  I am fine optionally removing the crda dep here, but making it a blocker will cause upgrade hiccups for no reason.

2023-06-21 03:29 UTC, ZeroChaos- commented on net-wireless/wireless-regdb/wireless-regdb-20230503.ebuild
> +DESCRIPTION="Regulatory database for Linux"
your version doesn't compile it either, so why are you changing this?

2023-06-21 03:30 UTC, ZeroChaos- commented on net-wireless/wireless-regdb/wireless-regdb-20230503.ebuild
> +	if kernel_is -ge 4 15 && has_version net-wireless/crda; then
I don't really have a problem with this, but it should probably go after the config checks and mention that the config needs to be correct to support not using crda.

2023-06-21 03:32 UTC, ZeroChaos- commented on net-wireless/wireless-regdb/wireless-regdb-20230503.ebuild
> +	if kernel_is -lt 4 15; then
this is flat wrong.  The kernel checks above are not fatal (nor should they be) so users may be on a newer kernel which isn't configured properly and need crda.  I've said multiple times to add a crda use flag, I know you hate crda, but a non-default use flag is going to provide the best user experience here.

2023-06-21 03:33 UTC, ZeroChaos- commented on net-wireless/wireless-regdb/wireless-regdb-20230503.ebuild
> +	doman -i18n= regulatory.bin.5 regulatory.db.5
if we don't install regulatory.bin why are we installing regulatory.bin.5?  again, a crda use flag really makes sense here.

2023-06-27 14:06 UTC, ZeroChaos- commented
per @thesamesam on irc there was some confusion with an earlier statement I made so I will clarify here.

Please introduce a use flag for crda.  It should be disabled by default.  When it is disabled, crda is not pulled in as a dep, and files needed by crda should not be installed.  DO NOT add a blocker against crda, it's an easier upgrade path if we simply allow it to get depcleaned.  Other packages still depend on crda, and while I'm willing to change that it would complicate the upgrade path to add the blocker at this time.

2023-06-27 15:26 UTC, ZeroChaos- commented
I just took a look at net-wireless/iwd and some of the warning in there might make sense.  If we can use this work as a "let's get rid of crda" plan I'd like the checks to be as complete as possible so we can copy and paste them into the other ebuilds to improve checking and make sure users are good.

2023-06-29 01:27 UTC, ZeroChaos- commented on net-wireless/wireless-regdb/wireless-regdb-20230503.ebuild
> +	if linux_config_exists && linux_chkconfig_builtin CFG80211 &&
we should also add a warning for when CFG80211 isn't selected at all.

2023-08-19 16:52 UTC, closed without merging