pam.eclass: remove EAPI 6
gentoo/gentoo pull request #31917
Opened 2023-07-16 18:32 UTC by SoapGentoo

2023-07-17 09:09 UTC, ulm requested changes

2023-07-17 09:09 UTC, ulm commented on eclass/pam.eclass
> +		has $1 "${authlevels}" || die "unknown level type"
This change doesn't look right. AFAICS you want word-splitting on `${authlevels}`.

2023-07-17 09:09 UTC, ulm commented on eclass/pam.eclass
> +	if in_iuse pam && ! use pam; then
This test occurs multiple times. Maybe define it as a function like this?
```
_pam_flag_disabled() {
	in_iuse pam && ! use pam
}
```
Also, must these be `if` blocks?
```
	_pam_flag_disabled && return 0
```

2023-07-17 09:09 UTC, ulm commented on eclass/pam.eclass
> +		"${pamdfile}" || die
The `>>` at the end of the line looks strange, maybe move it to the following line?

2023-07-18 15:13 UTC, thesamesam approved these changes

2023-07-18 16:25 UTC, ulm approved these changes

2023-07-31 15:12 UTC, closed without merging