dev-vcs/git-cola: add 4.3.1
gentoo/gentoo pull request #32414
Opened 2023-08-22 18:36 UTC by bearsh

Closes: https://bugs.gentoo.org/912845

2023-08-25 16:36 UTC, arthurzam requested changes

2023-08-25 16:36 UTC, arthurzam commented on dev-vcs/git-cola/git-cola-4.3.1.ebuild
> +RESTRICT="!test? ( test )"
Since you have declared `distutils_enable_tests pytest`, it automatically adds those 2 lines, so you can drop them:

```suggestion
```

2023-08-25 16:36 UTC, arthurzam commented on dev-vcs/git-cola/git-cola-4.3.1.ebuild
> +}
If you change the inherit `xdg-utils` -> `xdg`, you can drop those 2 functions (it automatically finds you have added desktop files and calls database update).

2023-08-27 12:41 UTC, bearsh commented
thanks @arthurzam for the review and the suggestions!

2023-08-27 15:21 UTC, arthurzam approved these changes

2023-08-27 15:23 UTC, closed without merging