gnome-extra/snapshot: New package 45_beta DRAFT WIP
gentoo/gentoo pull request #32439
Opened 2023-08-24 21:00 UTC by flint2

Work In Progress

compile:
```
[28/31] /usr/bin/env CARGO_HOME=/var/tmp/portage/gnome-extra/snapshot-45_beta/work/snapshot-45_beta-build/cargo-home /usr/bin/cargo build --manifest-path /var/tmp/portage/gnome-extra/snapshot-45_beta/work/snapshot-45.beta/Cargo.toml --target-dir /var/tmp/portage/gnome-extra/snapshot-45_beta/work/snapshot-45_beta-build/src --release && cp src/release/snapshot src/snapshot
    Updating crates.io index
warning: spurious network error (3 tries remaining): [6] Couldn't resolve host name (Could not resolve host: index.crates.io)
warning: spurious network error (2 tries remaining): [6] Couldn't resolve host name (Could not resolve host: index.crates.io)
warning: spurious network error (1 tries remaining): [6] Couldn't resolve host name (Could not resolve host: index.crates.io)
error: failed to get `libadwaita` as a dependency of package `snapshot v45.0.0-beta (/var/tmp/portage/gnome-extra/snapshot-45_beta/work/snapshot-45.beta)`

Caused by:
  failed to query replaced source registry `crates-io`

Caused by:
  download of config.json failed

Caused by:
  failed to download from `https://index.crates.io/config.json`

Caused by:
  [6] Couldn't resolve host name (Could not resolve host: index.crates.io)
```

install:
```
 * cargo install --path ./ --root /var/tmp/portage/gnome-extra/snapshot-45_beta/image/usr
error: binary `snapshot` already exists in destination
Add --force to overwrite
 * ERROR: gnome-extra/snapshot-45_beta::gentoo failed (install phase):
 *   cargo install failed
 * 
 * Call stack:
 *     ebuild.sh, line  136:  Called src_install
 *   environment, line 3373:  Called cargo_src_install
 *   environment, line 1454:  Called die
 * The specific snippet of code:
 *       "${@}" || die "cargo install failed";
 * 
 * If you need support, post the output of `emerge --info '=gnome-extra/snapshot-45_beta::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=gnome-extra/snapshot-45_beta::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/gnome-extra/snapshot-45_beta/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/gnome-extra/snapshot-45_beta/temp/environment'.
 * Working directory: '/var/tmp/portage/gnome-extra/snapshot-45_beta/work/snapshot-45.beta'
 * S: '/var/tmp/portage/gnome-extra/snapshot-45_beta/work/snapshot-45.beta'

```

2024-07-05 23:54 UTC, cfuga commented on gnome-extra/snapshot/snapshot-46.3.ebuild
> +	>=gui-libs/gtk-4.11.0
Snapshot version 46.3 requires ```>=gui-libs/gtk-4.13.6```

2024-07-05 23:56 UTC, cfuga commented
Snapshot version 46.3 requires ```>=gui-libs/gtk-4.13.6```

2025-01-06 14:32 UTC, cfuga commented on media-libs/libcamera/libcamera-0.2.0.ebuild
> +	dev-python/jinja
Fix dependency: ```dev-python/jinja``` => ```dev-python/jinja2```

2025-01-06 14:49 UTC, cfuga commented on gnome-extra/snapshot/snapshot-46.3.ebuild
> +	>=virtual/rust-1.70.0
You should omit ```>=virtual/rust-1.70.0```. Now it's handled by ```inherit cargo```

2025-01-12 19:58 UTC, flint2 commented on media-libs/libcamera/libcamera-0.2.0.ebuild
> +	dev-python/jinja
Done in https://github.com/gentoo/gentoo/pull/32439/commits/489ac0765c977d59b3b22bab08afa8dcc58bde9f

2025-01-12 19:59 UTC, flint2 commented on gnome-extra/snapshot/snapshot-46.3.ebuild
> +	>=virtual/rust-1.70.0
Done in https://github.com/gentoo/gentoo/pull/32439/commits/368ab74c20d0ea3c1a7129e4ece80c81ce017d30

2025-03-19 02:14 UTC, thesamesam requested changes
The libcamera commits also don't tag the bug.

2025-03-19 02:14 UTC, thesamesam commented on media-libs/libcamera/libcamera-0.4.0.ebuild
> +	SRC_URI="https://github.com/kbingham/libcamera/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz"
Please use https://gitlab.freedesktop.org/camera/libcamera/-/releases/v0.4.0 instead. We lobbied upstream hard to add that.

2025-03-19 02:14 UTC, thesamesam commented on media-libs/libcamera/libcamera-0.4.0.ebuild
> +	(
This isn't the usual style - you know that by now?

2025-03-19 02:14 UTC, thesamesam commented on media-libs/libcamera/libcamera-0.4.0.ebuild
> +	|| (
|| ( ... ) for two linked-against libraries _can't_ be correct.

2025-03-19 02:14 UTC, thesamesam commented on media-libs/libcamera/libcamera-0.4.0.ebuild
> +	meson_src_configure "-Dpipelines=uvcvideo,ipu3"
Why not add those arguments to `emesonargs`?

2025-03-19 02:14 UTC, thesamesam commented on media-libs/libcamera/metadata.xml
> +<pkgmetadata>
There's no maintainer listed here, which `pkgcheck scan --commits` should warn about. See also https://projects.gentoo.org/qa/policy-guide/maintainer.html#pg0602.

2025-03-19 02:14 UTC, thesamesam commented on media-libs/libcamera/metadata.xml
> +    <flag name="libevent">Compile the cam test application.</flag>
Not sure this is worth having then?

2025-03-19 02:14 UTC, thesamesam commented on media-video/pipewire/pipewire-1.2.7-r2.ebuild
> +# Copyright 1999-2024 Gentoo Authors
Please update (only) 9999 for now to ease review and avoid conflicts.

2025-03-19 02:14 UTC, thesamesam commented on media-libs/libcamera/Manifest
> +DIST libcamera-0.4.0.tar.gz 1677692 BLAKE2B 9bb29f04525c2ee6d570e139a8899091b0cfb6444d4140caf3bf3366d5f79f636faf70772d280ea494c6eb1196e07d377282c28ed4c15ab8351c9e498fcfdeaf SHA512 fd4c0ecd9b6b4c384b5
Please just add the latest version for now.

2025-03-19 02:14 UTC, thesamesam commented on media-libs/libcamera/libcamera-0.4.0.ebuild
> +	qt5?
Can we please avoid adding new qt5? Does it support qt6?

2025-03-19 02:14 UTC, thesamesam commented on media-libs/libcamera/libcamera-0.4.0.ebuild
> +	libevent?
Surely this isn't right if it's all purely for the demo application per metadata.xml?

2025-03-19 02:14 UTC, thesamesam commented on media-libs/libcamera/libcamera-0.4.0.ebuild
> +IUSE="debug drm gnutls gstreamer jpeg libevent qt5 sdl tiff trace udev unwind v4l2"
Many of these USE make no difference to `src_configure`, meaning they're automagic.

2025-03-19 05:11 UTC, cfuga commented on media-libs/libcamera/libcamera-0.4.0.ebuild
> +	qt5?
The port to Qt6 was completed since version 0.3.2.

- [apps: qcam: Port to Qt 6](https://gitlab.freedesktop.org/camera/libcamera/-/commit/71aa3ceec30b152fe5a02aba968c8c72cb47149e)
- [py: cam: Convert to PyQt6](https://gitlab.freedesktop.org/camera/libcamera/-/commit/15a51caae8811817f55af0a925915d8fa45ca7a4)

2025-05-11 22:36 UTC, closed without merging