sys-process/cronbase: Changed Homepage from No_homepage to Cron + added
gentoo/gentoo pull request #32633
Opened 2023-09-05 15:58 UTC by lima-limon-inc

einfo message informing about the cron group and how to add a user to said group.

This is in reference to commit: [6fd345466e6afddbc2e4231dd7eb45b1685586a1](https://github.com/gentoo/gentoo/commit/6fd345466e6afddbc2e4231dd7eb45b1685586a1) 
and
Bug: https://bugs.gentoo.org/913346

2023-09-05 16:15 UTC, floppym requested changes

2023-09-05 16:15 UTC, floppym commented on sys-process/cronbase/cronbase-0.3.7-r10.ebuild
> +	einfo "https://wiki.gentoo.org/wiki/Cron                               "
Please change it to elog instead of einfo. Also get rid of the trailing spaces on lines 34 and 35.

2023-09-05 16:17 UTC, floppym commented
Also, this should really be broken into 2 commits: one to update HOMEPAGE, and the other to add the elog message.

That should help you write a more concise commit message for each change.

2023-09-05 16:20 UTC, lima-limon-inc commented
> Also, this should really be broken into 2 commits: one to update HOMEPAGE, and the other to add the elog message.
> 
> That should help you write a more concise commit message for each change.

Noted. I'll keep that in mind. I apologize for the long commit message.
Can/Should I amend the commit?

2023-09-05 17:19 UTC, floppym commented
> Can/Should I amend the commit?

Yes, if you don't mind. Otherwise I can take care of it.

You might find the following posts helpful in that effort:

https://stackoverflow.com/questions/6217156/break-a-previous-commit-into-multiple-commits

https://stackoverflow.com/questions/1085162/commit-only-part-of-a-files-changes-in-git

2023-09-05 21:35 UTC, lima-limon-inc commented
> > Can/Should I amend the commit?
> 
> Yes, if you don't mind. Otherwise I can take care of it.
> 
> You might find the following posts helpful in that effort:
> 
> https://stackoverflow.com/questions/6217156/break-a-previous-commit-into-multiple-commits
> 
> https://stackoverflow.com/questions/1085162/commit-only-part-of-a-files-changes-in-git

I think it worked. Thank you for the feedback and links!

2023-09-05 23:36 UTC, lima-limon-inc commented
In retrospect, I think I was not able to split the commits correctly

2023-09-06 01:23 UTC, closed without merging

2023-09-06 01:29 UTC, lima-limon-inc commented
New pull request: https://github.com/gentoo/gentoo/pull/32642