app-admin/mkosi: bump to v15.1
gentoo/gentoo pull request #32657
Opened 2023-09-06 18:29 UTC by 257

2023-09-27 21:02 UTC, Flowdalic commented on app-admin/mkosi/metadata.xml
> +		<remote-id type="github">webcamoid/webcamoid</remote-id>
That looks wrong.

2023-09-27 21:03 UTC, Flowdalic commented
Latest version is 17.1. Could you bump to that?

2023-09-27 21:38 UTC, 257 commented on app-admin/mkosi/metadata.xml
> +		<remote-id type="github">webcamoid/webcamoid</remote-id>
it is. good catch, thanks.

2023-09-27 21:43 UTC, 257 commented
i have not looked into gentoo bits of mkosi after 15.1 and upstream stopped touching that. lets go with 15.1 for now; i will look into 17.1 in the next round.

2023-09-27 22:00 UTC, dwfreed requested changes

2023-09-27 22:00 UTC, dwfreed commented on app-admin/mkosi/mkosi-15.1.ebuild
> +KEYWORDS="amd64"
This is a straight-to-stable...

2023-09-27 22:09 UTC, 257 commented
oops! fixed.

2023-09-28 06:37 UTC, Flowdalic commented
Your fixed of the first commit went into the second commit. Furthermore, I'd like to keep mkosi 14 as a future stable version. Please drop the drop commit. :)

2023-09-28 07:28 UTC, closed without merging