verify-sig.eclass: minisig support
gentoo/gentoo pull request #32771
Opened 2023-09-14 06:13 UTC by thesamesam

Closes: https://bugs.gentoo.org/783066
Signed-off-by: Sam James <sam@gentoo.org>

2023-09-14 08:34 UTC, mgorny requested changes

2023-09-14 08:34 UTC, mgorny commented on eclass/verify-sig.eclass
> +			minisign -V -P "$(<${key})" -x "${sig}" -m "${file}" ||
```suggestion
			minisign -V -P "$(<"${key}")" -x "${sig}" -m "${file}" ||
```

2023-09-15 02:56 UTC, mgorny approved these changes
LGTM

2023-09-16 09:49 UTC, thesamesam commented
Merged.

2023-09-16 09:49 UTC, closed without merging