app-containers/containers-{common,storage}: with stable & live of deps
gentoo/gentoo pull request #32976
Opened 2023-09-21 19:14 UTC by rahilarious

Common configs & docs for Containers eco-system (i.e. podman buildah skopeo...)

Go realm, executables are all in compiled, static, tidy in one binary but docs & configs...OMG all over the place. Spent whole day coding all these (such noob, I know), but was fun & fulfilling. Once this is merged the foundation of podman-stack is built, so will proceed to update frontend packages of eco-system.

Closes: https://bugs.gentoo.org/907805
Closes: https://bugs.gentoo.org/904433
Closes: https://bugs.gentoo.org/914456
Closes: https://bugs.gentoo.org/907804

2023-09-21 20:28 UTC, thesamesam requested changes

2023-09-21 20:28 UTC, thesamesam commented on app-containers/containers-common/containers-common-0.56.0.ebuild
> +DEPEND="
BDEPEND (because we execute it during the build)

2023-09-21 20:28 UTC, thesamesam commented on app-containers/containers-common/containers-common-0.56.0.ebuild
> +DESCRIPTION="Common config files and docs for Containers eco-system"
Change the whitespace so it's like:
```
DESCRIPTION
HOMEPAGE
SRC_URI

LICENSE
SLOT
BDEPEND
...

src_prepare() {

}

...

This roughly matches skel.ebuild.

2023-09-21 20:28 UTC, thesamesam commented on app-containers/containers-common/containers-common-0.56.0.ebuild
> +if is_live; then
I don't really see the benefit here, you could just put it above with SRC_URI (as suggested above).

Look at what other ebuilds do (e.g. ntpsec-9999)

2023-09-21 20:28 UTC, thesamesam commented on app-containers/containers-common/containers-common-0.56.0.ebuild
> +	emake docs || die
No need for || die with newer EAPIs for builtins like emake. Still needed for external commands which may fail.

2023-09-21 20:28 UTC, thesamesam commented on app-containers/containers-common/containers-common-0.56.0.ebuild
> +	eapply "${T}/fix-warnings.patch" || die
No need for die.

2023-09-21 20:28 UTC, thesamesam commented on app-containers/containers-common/containers-common-0.56.0.ebuild
> +	cat <<"EOF" > "${T}/fix-warnings.patch"
Can't you put this in a proper patch in files/ and then add it to PATCHES in the ebuild?

2023-09-21 20:28 UTC, thesamesam commented on app-containers/containers-common/containers-common-0.56.0.ebuild
> +	sed -i -e 's|/usr/local|/usr|g' docs/Makefile
die

2023-09-21 22:17 UTC, closed without merging

2026-04-22 10:27 UTC, eternal-sorrow commented
Why does containers-common unconditionally require iptables?