dev-java/openjfx: drop ffmpeg dependency
gentoo/gentoo pull request #33053
Opened 2023-09-25 12:34 UTC by fedeliallalinea

Closes: https://bugs.gentoo.org/834369

2023-09-25 12:40 UTC, thesamesam commented
Needs rationale in commit message please

2023-09-25 12:44 UTC, ulm requested changes

2023-09-25 12:44 UTC, ulm commented on dev-java/openjfx/openjfx-11.0.11_p1-r1.ebuild
> +EAPI=6
EAPI 6 is banned from the Gentoo repository, so please don't add any new EAPI 6 ebuilds.

2023-09-25 12:44 UTC, ulm commented on dev-java/openjfx/openjfx-11.0.9_p0-r1.ebuild
> +EAPI=6
Same here.

2023-09-25 14:33 UTC, ulm commented on dev-java/openjfx/openjfx-11.0.11_p1-r1.ebuild
> +	virtual/opengl
You may want to depend on `app-accessibility/at-spi2-core` and `media-libs/libjpeg-turbo` directly, instead of `dev-libs/atk` and `virtual/jpeg`.

2023-09-26 20:01 UTC, thesamesam commented
is openjfx actually usable w/o ffmpeg?

2023-09-27 06:57 UTC, ulm commented
> is openjfx actually usable w/o ffmpeg?

I am using `dev-java/openjdk[javafx]` with `sci-mathematics/geogebra-bin` and AFAICS things work fine.

The only two other reverse dependencies are `app-text/jabref-bin` and `dev-db/sqldeveloper`. Not entirely sure about these, but from their description it seems unlikely that they would use video or audio.

2023-09-27 07:10 UTC, ulm commented
Last point, the patch should be cleaned up, see https://devmanual.gentoo.org/ebuild-writing/misc-files/patches/index.html#clean-patch-howto. For example, the scrub-patch command from app-portage/iwdevtools can be used for this

I'll do this when merging, so no need to update the PR.

2023-09-27 07:11 UTC, ulm commented
Thank you!

2023-09-27 07:11 UTC, closed without merging

2023-09-27 07:31 UTC, fedeliallalinea commented
> > is openjfx actually usable w/o ffmpeg?
> 
> I am using `dev-java/openjdk[javafx]` with `sci-mathematics/geogebra-bin` and AFAICS things work fine.
> 
> The only two other reverse dependencies are `app-text/jabref-bin` and `dev-db/sqldeveloper`. Not entirely sure about these, but from their description it seems unlikely that they would use video or audio.

I confirm that `dev-db/sqldeveloper` works fine also without ffmpeg support on `dev-java/openjfx`.