sys-libs/compiler-rt: float16 ABI build condition.
gentoo/gentoo pull request #33900
Opened 2023-11-19 07:51 UTC by heroxbd

As this becomes a blocker for HIP-5.7 bump, it makes more sense to carry the patch with Gentoo for a while.

Bug: https://github.com/llvm/llvm-project/pull/69842
Bug: https://github.com/gentoo/gentoo/pull/33400
Reference: https://github.com/llvm/llvm-project/issues/56854

2023-11-19 07:54 UTC, thesamesam commented
The bug discusses why we haven't merged it yet (test failures with LLVM 16 which make us wonder if it's even OK for 17 without some analysis).

You need to use a full link for `Bug:`, by the way.

2023-11-19 09:51 UTC, mgorny requested changes
We don't do `PATCHES`. Plz lemme know which versions need it, and I'll add it to the patchset.

2023-11-19 09:52 UTC, mgorny commented
> The bug discusses why we haven't merged it yet (test failures with LLVM 16 which make us wonder if it's even OK for 17 without some analysis).
> 
> You need to use a full link for `Bug:`, by the way.

Ah, thanks, I forgot about that. Then yes, research that too.

2023-11-19 10:45 UTC, heroxbd commented
Sam James ***@***.***> writes:

> The bug discusses why we haven't merged it yet (test failures with
> LLVM 16 which make us wonder if it's even OK for 17 without some
> analysis).

I suppose "the bug" means
https://github.com/llvm/llvm-project/pull/69842, or else?

Excuse me, which test failures to be specific?

> You need to use a full link for Bug:, by the way.

I did use full link. Github made abbreviations.

Michał Górny writes:

> We don't do PATCHES. Plz lemme know which versions need it, and I'll
> add it to the patchset.

The latest compiler-rt-17.0.5 is enough.  But I don't mind it to be
applied to more versions.

> Ah, thanks, I forgot about that. Then yes, research that too.

I thought you had approved it at
https://github.com/llvm/llvm-project/pull/69842#pullrequestreview-1691380395 .

2023-11-19 10:50 UTC, thesamesam commented
> Sam James ***@***.***> writes:
> The bug discusses why we haven't merged it yet (test failures with LLVM 16 which make us wonder if it's even OK for 17 without some analysis).
> I suppose "the bug" means [llvm/llvm-project#69842](https://github.com/llvm/llvm-project/pull/69842), or else? Excuse me, which test failures to be specific?

It's on the Gentoo bug at https://bugs.gentoo.org/916069#c8.

> You need to use a full link for Bug:, by the way.
> I did use full link. Github made abbreviations.

I misunderstood -- you'd missed the link to the Gentoo bug instead.

>  Michał Górny writes:
> We don't do PATCHES. Plz lemme know which versions need it, and I'll add it to the patchset.
> The latest compiler-rt-17.0.5 is enough. But I don't mind it to be applied to more versions.
> Ah, thanks, I forgot about that. Then yes, research that too.
> I thought you had approved it at [llvm/llvm-project#69842 (review)](https://github.com/llvm/llvm-project/pull/69842#pullrequestreview-1691380395) .

We did, but then we found the test failures with 16, and asked for an investigation at https://bugs.gentoo.org/916069#c8.

2023-11-19 15:32 UTC, heroxbd commented
Sam James ***@***.***> writes:

> It's on the Gentoo bug at https://bugs.gentoo.org/916069#c8.
>
>  I did use full link. Github made abbreviations.
>
> I misunderstood -- you'd missed the link to the Gentoo bug instead.

Oops, I missed it. Added a line "Close: " to the commit message.

>  Michał Górny writes:
>  We don't do PATCHES. Plz lemme know which versions need it, and I'll add it to the patchset.
>  The latest compiler-rt-17.0.5 is enough. But I don't mind it to be applied to more versions.
>  Ah, thanks, I forgot about that. Then yes, research that too.
>  I thought you had approved it at llvm/llvm-project#69842 (review) .
>
> We did, but then we found the test failures with 16, and asked for an
> investigation at https://bugs.gentoo.org/916069#c8.

Will do my research.

2023-11-24 19:35 UTC, thesamesam commented
The analysis in the bug sounds good. @mgorny can you merge the patch? Thanks.

2023-11-24 21:59 UTC, thesamesam commented
commit 866069267e1b71a27b1dc1d718180c731696fd92
Author: Michał Górny <mgorny@gentoo.org>
Date:   Fri Nov 24 21:18:33 2023 +0100

    sys-libs/compiler-rt: Add FP16 fixes

    Closes: https://bugs.gentoo.org/916069
    Signed-off-by: Michał Górny <mgorny@gentoo.org>

Thanks!

2023-11-24 21:59 UTC, closed without merging

2023-11-25 12:44 UTC, heroxbd commented
Thanks a lot guys!