llvm.eclass: add tuple -> LLVM_TARGETS translate function
gentoo/gentoo pull request #33996
Opened 2023-11-26 04:35 UTC by matoro

To be used in support of dev-lang/rust under crossdev.  Cross-compiled rust needs LLVM with support for both host and destination targets.

2023-11-26 14:50 UTC, mgorny requested changes

2023-11-26 14:50 UTC, mgorny commented on eclass/llvm.eclass
> +# @FUNCTION: get_llvm_target
Let's call it `llvm_tuple_to_target`.

2023-11-26 14:50 UTC, mgorny commented on eclass/llvm.eclass
> +	case "${1:-${CHOST}}" in
No need to quote `case` arg in bash.

2023-11-26 16:20 UTC, thesamesam commented
cc @parona-source @kchibisov

2023-11-26 17:40 UTC, matoro commented on eclass/llvm.eclass
> +# @FUNCTION: get_llvm_target
Done

2023-11-26 17:40 UTC, matoro commented on eclass/llvm.eclass
> +	case "${1:-${CHOST}}" in
Done

2023-11-26 18:59 UTC, mgorny approved these changes
LGTM. Let's give others 2-3 days to chime in, then ask anyone to push it.

2023-11-26 19:12 UTC, parona-source approved these changes

2023-12-07 08:46 UTC, kchibisov commented
I guess it's fine now?

2023-12-07 13:01 UTC, closed without merging