media-video/haruna: new ebuild
gentoo/gentoo pull request #34514
Opened 2023-12-28 09:05 UTC by oniGino

Add haruna video player

2023-12-28 09:58 UTC, a17r requested changes
Should use kde.org.eclass and ecm.eclass instead.
Tags are no releases. There will be a proper tarball on kde.org mirrors to download from.

2023-12-28 10:18 UTC, oniGino commented
> Should use kde.org.eclass and ecm.eclass instead. Tags are no releases. There will be a proper tarball on kde.org mirrors to download from.

1. fixed eclass request
2. they post flatpaks and appimages but no tarballs (unfortunately )

2023-12-28 10:26 UTC, oniGino commented
> > Should use kde.org.eclass and ecm.eclass instead. Tags are no releases. There will be a proper tarball on kde.org mirrors to download from.
> 
>     1. fixed eclass request
> 
>     2. they post flatpaks and appimages but no tarballs (unfortunately )

my mistake I found it, thank you.

2023-12-28 10:26 UTC, a17r requested changes
If 5.112.0 is the minimum for ECM, then all KDE Frameworks must have this minimum dep.

Our standardised method for enforcing this is adding `KFMIN=5.112.0` pre-inherit and change all `kde-frameworks/*` lines to use it. `ecm.eclass` will also apply `KFMIN`.

2023-12-28 10:26 UTC, a17r commented on media-video/haruna/haruna-0.12.3.ebuild
> +	dev-qt/qtx11extras:5
keep them sorted please. dev-qt/qtcore can be dropped, it is always provided by ecm.eclass.

2023-12-28 10:26 UTC, a17r commented on media-video/haruna/haruna-0.12.3.ebuild
> +inherit xdg kde.org ecm
xdg can be dropped, done by ecm.eclass.

2023-12-28 10:26 UTC, a17r commented on media-video/haruna/haruna-0.12.3.ebuild
> +	>=kde-frameworks/extra-cmake-modules-5.112.0:0
ECM can be dropped, it is always provided by ecm.eclass.

2023-12-28 10:29 UTC, a17r requested changes

2023-12-28 10:29 UTC, a17r commented on media-video/haruna/haruna-0.12.3.ebuild
> +}
can be dropped since using `ecm.eclass` now.

2023-12-28 10:29 UTC, a17r requested changes

2023-12-28 10:29 UTC, a17r commented on media-video/haruna/haruna-0.12.3.ebuild
> +	youtube? ( net-misc/yt-dlp )"
This is not connected to any kind of build option? How does it work, then?

2023-12-30 13:46 UTC, a17r requested changes

2023-12-30 13:46 UTC, a17r commented on media-video/haruna/haruna-0.12.3.ebuild
> +	cmake_src_configure
You call `ecm_src_configure` only, not `cmake_src_configure`.

2023-12-30 13:46 UTC, a17r commented on media-video/haruna/haruna-0.12.3.ebuild
> +QTMIN=5.15.11
`KFMIN` and `QTMIN` shall be set **pre**-inherit

2023-12-30 13:46 UTC, a17r commented on media-video/haruna/haruna-0.12.3.ebuild
> +LICENSE="GPL-3"
```suggestion
SRC_URI="https://download.kde.org/stable/${PN}/${P}.tar.xz"

LICENSE="GPL-3"
```

2023-12-30 13:46 UTC, a17r commented on media-video/haruna/haruna-0.12.3.ebuild
> +KEYWORDS="~amd64 ~x86"
- did you test this on ~x86?

2023-12-30 13:46 UTC, a17r commented on media-video/haruna/haruna-0.12.3.ebuild
> +IUSE="youtube"
correct sorting per https://github.com/gentoo/gentoo/blob/master/skel.ebuild:
- LICENSE
- SLOT
- KEYWORDS
- IUSE

2024-09-12 19:13 UTC, closed without merging