net-print/hplip: disable dbus dependency when minmal USE flag is active
gentoo/gentoo pull request #34855
Opened 2024-01-17 06:13 UTC by neeshy

DBus isn't required when only the hpcup/hpijs driver is being built.

2024-01-18 18:32 UTC, billie80 requested changes
Thanks for your contribution.

Can you please fix your sign-off. It should be signed by the autor but the display name between author and sign-off address is different thus Git is complaining.

Author: neeshy <neeshy@tfwno.gf>
vs.
Signed-off-by: Nima Sadeghi <neeshy@tfwno.gf>

Thanks

2024-01-18 18:32 UTC, billie80 commented on net-print/hplip/hplip-3.23.12-r1.ebuild
> +# Copyright 1999-2023 Gentoo Authors
Please adjust the copyright year.

2024-01-18 23:40 UTC, neeshy commented
Ok, done.

2024-01-22 04:44 UTC, neeshy commented
@billie80 Pinging for visibility.

2024-01-22 06:22 UTC, billie80 commented
No need! I am aware and will deal with it when I find the time. Most likely today.

2024-01-22 19:25 UTC, closed without merging