dev-libs/miniaudio: add 0.11.21
gentoo/gentoo pull request #35152
Opened 2024-02-02 18:28 UTC by stkw0

Previously the website and other miscellaneous files were also installed in /usr/include. This version corrects that behaviour

2024-06-05 16:52 UTC, antecrescent requested changes

2024-06-05 16:52 UTC, antecrescent commented on dev-libs/miniaudio/miniaudio-0.11.21.ebuild
> +LICENSE="|| ( public-domain MIT-0 )"
```suggestion
LICENSE="|| ( Unlicense MIT-0 )"
```
This also affects the other versions in ::gentoo. Maybe you could fix that as well :+1:

2024-06-05 19:32 UTC, misanthropos commented
Looks good to me.

2024-11-25 14:29 UTC, stkw0 commented
> Please make sure the commit message contains the PR description so that information isn't lost

Done. I also rephrase it to make it more clear with the next : `Correct installation of website and miscellaneous files. Now are installed to /usr/share instead of /usr/include.`

2024-11-25 14:34 UTC, closed without merging