app-admin/syslog-ng: add 4.6.0, drop old
gentoo/gentoo pull request #35169
Opened 2024-02-03 18:32 UTC by hydrapolic

Copy of previous ebuild, tests pass on ~amd64

```
============================================================================
Testsuite summary for syslog-ng 4.6.0
============================================================================
# TOTAL: 184
# PASS:  184
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
>>> Completed testing app-admin/syslog-ng-4.6.0
```

2024-02-04 09:13 UTC, arkamar requested changes

2024-02-05 10:02 UTC, hydrapolic commented on app-admin/syslog-ng/syslog-ng-4.6.0.ebuild
>  SRC_URI="https://github.com/balabit/syslog-ng/releases/download/${P}/${P}.tar.gz"
Hello @arkamar, sure, updated, thanks for the notice.

2024-02-05 10:09 UTC, Flowdalic commented
@hydrapolic thanks for your contribution.

Could you may look into the automagic MQTT dependency of syslog-ng ([bug #92201](https://bugs.gentoo.org/922201)). I wouldn't be surprised if there are further automagic dependencies.

2024-02-06 03:16 UTC, thesamesam commented
I'll merge it now given https://bugs.gentoo.org/914364.

2024-02-06 03:27 UTC, closed without merging

2024-02-06 04:59 UTC, hydrapolic commented
Thanks @Flowdalic for the bug, didn't get to it as of now. Thanks @thesamesam for the help too.