Bump kcolorpicker-0.3.0 and kimageannotator-0.7.0 and add split qt5/qt6 support
gentoo/gentoo pull request #35274
Opened 2024-02-11 15:28 UTC by dflogeras

I need some guidance on how to proceed.  The libraries build and tests pass (with a last minute patch from upstream).  However, the libraries now install as libxyz-Qt5.so and libxyz-Qt6.so, breaking old packages that expect just libxyz.so

Not sure what the proposed solution should be to keep in-tree happy.

2024-02-11 20:32 UTC, a17r commented
> However, the libraries now install as libxyz-Qt5.so and libxyz-Qt6.so, breaking old packages that expect just libxyz.so

Do we need a `:=` slot op on Qt5-based revdeps or is patching needed for them to link against >=0.7.0 correctly?

2024-02-11 20:44 UTC, a17r requested changes
kcolorpicker review comments also mostly apply to kimageannotator.

2024-02-11 20:44 UTC, a17r commented on media-libs/kcolorpicker/kcolorpicker-0.3.0.ebuild
> +	)
can be made in a single line, minor nitpick

2024-02-11 20:44 UTC, a17r commented on media-libs/kcolorpicker/kcolorpicker-0.3.0.ebuild
> +S="${WORKDIR}/${MY_P}"
We typically set this below `SRC_URI` these days, since subdir is usually linked with tarball name.

2024-02-11 20:44 UTC, a17r commented on media-libs/kcolorpicker/kcolorpicker-0.3.0.ebuild
> +		esac
```suggestion
		local mycmakeargs=( -DBUILD_TESTS=$(usex test) )
		[[ ${MULTIBUILD_VARIANT} == qt6 ]] && mycmakeargs+=( -DBUILD_WITH_QT6=ON )
```

2024-02-11 20:44 UTC, a17r commented on media-libs/kcolorpicker/kcolorpicker-0.3.0.ebuild
> +		esac
(unless we should also set Qt6 definitely OFF for qt5 build for future version bumps?)

2024-02-11 20:44 UTC, a17r commented on media-libs/kcolorpicker/kcolorpicker-0.3.0.ebuild
> +		BUILD_DIR="${BUILD_DIR}/tests" virtx cmake_src_test
Maybe it works without `virtualx` entirely by setting

``local -x QT_QPA_PLATFORM=offscreen``

instead?

2024-02-11 20:44 UTC, a17r commented on media-libs/kimageannotator/kimageannotator-0.7.0.ebuild
> +)
`PATCHES` should go below DEPENDencies, before phase functions.

2024-02-12 08:49 UTC, a17r commented on media-libs/kcolorpicker/kcolorpicker-0.3.0.ebuild
> +		esac
(also note the `\` is completely unnecessary in arrays)

2024-02-22 12:04 UTC, a17r commented
ping - this is now blocking 24.02.0 (among many other things though ;))

2024-02-24 11:53 UTC, alexxy commented
@dflogeras i added version based on this pr to gentoo. So please check

2024-02-25 01:43 UTC, dflogeras commented
First, I apologize as I was traveling this week and unable to finish figuring out how to handle splitting the qt5/qt6 libs for gwenview.

Second, I have to say I am slightly annoyed and am not sure what I am to check.  I was respectfully asked in the original bug request to figure out how to have qt5 and qt6 coexisting libraries.  The version checked into the tree ignored that, and my efforts, and simply jumped to qt6 only.  I could have done that weeks ago.

2024-02-25 16:01 UTC, dflogeras commented
Furthermore, the tests for kimageannotator do not pass with QT_QPA_PLATFORM=offscreen, while they do with virtx.

2024-02-26 21:18 UTC, a17r commented
@dflogeras: Apologies about the situation, I usually try my best to avoid wasted efforts. The bug was filed before I knew about the need for Qt5-based revdeps to be patched to work with the new version due to the way they implemented the split. Then, since there is only `kde-apps/gwenview` left as consumer, I deemed it not worth the effort after all, and incidentally @alexxy had already pushed their ebuilds to kde overlay like that in the meantime.

> Furthermore, the tests for kimageannotator do not pass with QT_QPA_PLATFORM=offscreen, while they do with virtx.

@alexxy can you reproduce the test failure or did it work for you when making the change?

2024-02-27 19:41 UTC, a17r commented
I'm getting:

```
----------------------------------------------------------
********* Start testing of KeyInputHelperTest *********
Config: Using QtTest library 6.6.2, Qt 6.6.2 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 13.2.1 20240113), gentoo 2.14
PASS   : KeyInputHelperTest::initTestCase()
PASS   : KeyInputHelperTest::TestHandleKeyPress_Should_EmitRemoveSignal_When_KeyIsBackspace()
PASS   : KeyInputHelperTest::TestHandleKeyPress_Should_EmitRemoveSignal_When_KeyIsDelete()
PASS   : KeyInputHelperTest::TestHandleKeyPress_Should_EmitInsertSignalWithNewLine_When_KeyIsReturnAndModifierShift()
PASS   : KeyInputHelperTest::TestHandleKeyPress_Should_EmitInsertSignalWithNewLine_When_KeyIsEnterAndModifierShift()
PASS   : KeyInputHelperTest::TestHandleKeyPress_Should_EmitEscape_When_KeyIsReturnAndNoModifier()
PASS   : KeyInputHelperTest::TestHandleKeyPress_Should_EmitEscape_When_KeyIsEnterAndNoModifier()
PASS   : KeyInputHelperTest::TestHandleKeyPress_Should_EmitEscapeSignal_When_KeyIsEscape()
PASS   : KeyInputHelperTest::TestHandleKeyPress_Should_EmitMoveSignal_When_KeyIsHome()
PASS   : KeyInputHelperTest::TestHandleKeyPress_Should_EmitMoveSignal_When_KeyIsEnd()
PASS   : KeyInputHelperTest::TestHandleKeyPress_Should_EmitMoveSignal_When_KeyIsArrowLeft()
PASS   : KeyInputHelperTest::TestHandleKeyPress_Should_EmitMoveSignal_When_KeyIsArrowLeftAndModifierCtrl()
PASS   : KeyInputHelperTest::TestHandleKeyPress_Should_EmitMoveSignal_When_KeyIsArrowRight()
PASS   : KeyInputHelperTest::TestHandleKeyPress_Should_EmitMoveSignal_When_KeyIsArrowRightAndModifierCtrl()
PASS   : KeyInputHelperTest::TestHandleKeyPress_Should_EmitMoveSignal_When_KeyIsArrowUp()
PASS   : KeyInputHelperTest::TestHandleKeyPress_Should_EmitMoveSignal_When_KeyIsArrowDown()
PASS   : KeyInputHelperTest::TestHandleKeyPress_Should_EmitPasteSignal_When_KeyIsPaste()
PASS   : KeyInputHelperTest::TestHandleKeyPress_Should_EmitPasteSignal_When_KeySequenceIsPaste()
Received signal 11 (SIGSEGV), code 1, for address 0x00000000000000f8
         TestHandleKeyPress_Should_EmitInsertSignal_When_KeyIsCharacter function time: 0ms, total time: 1ms
<end of output>
Test time =   0.04 sec
----------------------------------------------------------
Test Failed.
"KeyInputHelperTest" end time: Feb 27 20:39 CET
"KeyInputHelperTest" time elapsed: 00:00:00
----------------------------------------------------------
```

2024-02-28 06:47 UTC, dflogeras commented
@a17r It's all good.  I wasn't aware you were consulted prior to the decision; we'll just move forward.  I see upstream _just_ changed how they call find_package() in gwenview.  Before the change in direction, I was going to suggest we patch gwenview's CMakeLists.txt with something like:

```
find_package( kImageAnnotator NAMES libkImageAnnotator libKimageAnnotator-qt5 ) [for gwenview 5]
```

to bridge the gap if we were going to keep it for coexistence.  I assume it will be dropped long before we care about hanging on to kimageannotator-0.6.x and kcolorpicker-0.2.0?

2024-02-28 07:41 UTC, a17r commented
Thanks for checking back. Yes, for kde-apps/gwenview:5 cleanup there will be 2 parameters weighed against each other:
- Plasma 6 stabilisation (unlikely for 6.0.x, but 6.1 will follow shortly) - you don't want Qt6-based applications in Plasma 5
- Qt5 support burden (Qt5WebEngine is a huge one, and we should get rid of it sooner than later)

2024-03-07 14:17 UTC, a17r commented
@dflogeras wanna turn this into 0.3.1/0.7.1 bump?

2024-03-08 14:51 UTC, dflogeras commented
Sure thing.  I'm going to try to get upstream to fix the unittest bug since Alexxy seems to have lost interest.  What's your preference: wait for upstream, revert to virtx until a fix is available, something else?

2024-03-08 15:23 UTC, a17r commented
No need to revert to virtx, we can always just disable the flaky test instead, with a comment/link to the upstream issue.

2024-03-08 15:36 UTC, closed without merging