media-libs/opencv: add 4.9.0
gentoo/gentoo pull request #35322
Opened 2024-02-14 11:28 UTC by negril

media-libs/quirc: new package, add 1.2, 9999

Closes: https://bugs.gentoo.org/921968
Closes: https://bugs.gentoo.org/924005

2024-02-21 01:33 UTC, thesamesam requested changes
Left some small comments but they apply elsewhere too.

2024-02-21 01:33 UTC, thesamesam commented on profiles/arch/x86/use.stable.mask
> +# media-libs/jasper is not stable
Please move the comment line above as it's not well-formed right now.

2024-02-21 01:33 UTC, thesamesam commented on media-libs/quirc/quirc-9999.ebuild
> +	KEYWORDS="~amd64 ~arm ~arm64 ~loong ~ppc ~ppc64 ~riscv ~x86"
Please do a keywording bug once it's merged.

2024-02-21 01:33 UTC, thesamesam commented on media-libs/opencv/opencv-4.9.0.ebuild
> +multilib_src_test() {
Please don't do newline after function starts.

Also, multilib_src_test should go before multilib_src_install to reflect phase execution order.

2024-03-11 12:21 UTC, Jamim commented
_Hello @negril,_

Would you mind updating this PR in order to address review comments?
Please let me know if any help is needed.

_Thanks!_

2024-03-18 16:35 UTC, closed without merging