sci-libs/opencascade: add 7.7.1, 7.7.2, 7.8.0, 9999, drop obsolete blocks, add myself as maintainer
gentoo/gentoo pull request #35374
Opened 2024-02-16 15:06 UTC by negril

Closes: https://bugs.gentoo.org/923350
Closes: https://bugs.gentoo.org/911578
Closes: https://bugs.gentoo.org/908889

2024-02-16 15:07 UTC, negril commented
Waiting for https://bugs.gentoo.org/924721

2024-02-21 01:43 UTC, thesamesam requested changes

2024-02-21 01:43 UTC, thesamesam commented on sci-libs/opencascade/opencascade-7.7.1.ebuild
> +# USE_{DRACO,FFMPEG,FREEIMAGE,FREETYPE,GLES2,OPENGL,OPENVR,RAPIDJSON,TBB,TK,VTK,XLIB}
? And why is this up here?

2024-02-21 01:43 UTC, thesamesam commented on sci-libs/opencascade/opencascade-7.7.1.ebuild
> +# There's no easy way to test. Testing needs a rather big environment properly set up.
This should be in the standard location, not here.

2024-02-21 01:43 UTC, thesamesam commented on sci-libs/opencascade/opencascade-7.7.1.ebuild
> +SLOT="0/$(ver_cut 1-2)"
Swap SLOT/LICENSE.

2024-02-21 01:43 UTC, thesamesam commented on sci-libs/opencascade/opencascade-7.7.1.ebuild
> +
Drop newline

2024-02-21 01:43 UTC, thesamesam commented on sci-libs/opencascade/opencascade-7.7.1.ebuild
> +src_test() {
Phase execution order.

2024-03-18 09:01 UTC, vowstar commented on sci-libs/opencascade/opencascade-7.7.1.ebuild
> +		sci-libs/vtk:=[rendering]
```suggestion
		sci-libs/vtk:=[opencascade,rendering]
```
``>=sci-libs/vtk-9.3.0`` require ``opencascade`` use flag

2024-03-18 09:02 UTC, vowstar commented on sci-libs/opencascade/opencascade-7.8.0.ebuild
> +		sci-libs/vtk:=[rendering]
```suggestion
		sci-libs/vtk:=[opencascade,rendering]
```
``>=sci-libs/vtk-9.3.0`` require ``opencascade`` use flag

2024-03-23 08:34 UTC, closed without merging