net-misc/freerdp: Require x11-libs/libXrandr if gstreamer and X Use flag are set
gentoo/gentoo pull request #35412
Opened 2024-02-18 14:45 UTC by fictitiousexistence

Require x11-libs/libXrandr only if gstreamer and X flag are set since wayland systems don't use libXrandr.

2024-02-18 16:18 UTC, fictitiousexistence commented
My apologies for opening / closing prs. Was having issues I didn't understand. Thanks.

2024-03-15 18:54 UTC, floppym requested changes
Changing RDEPEND will require revbumping each ebuild. Please do that via renames.

Please rebase on current master and include the newly added 3.4.0 ebuild.

2024-03-15 18:54 UTC, floppym commented on net-misc/freerdp/freerdp-2.11.1.ebuild
> +		)
Please collapse this to a single line.
```suggestion
		X? ( x11-libs/libXrandr )
```

2024-03-16 20:01 UTC, fictitiousexistence commented
@floppym  Is this correct? I synced again since you pushed #35659 and renamed the r1's to r2. And made the single line change requested. Thanks.

2024-03-16 23:27 UTC, closed without merging