files/netkit-timed-0.17: porting to C99
gentoo/gentoo pull request #36019
Opened 2024-03-31 16:54 UTC by NHOrus

Changing code to semantically identical, but syntactically correct. There's some warnings remain that I don't want to touch, because I don't understand the code and swapping float to double or adding brakets around assignment that ought to be inside if block can cause unintended consequences.

Closes: https://bugs.gentoo.org/919876

2024-05-09 00:16 UTC, thesamesam requested changes
I'm going to review the semantics later, but the commit message is wrong. It should be `cat/pkg: port to C99`.

2024-05-09 06:12 UTC, NHOrus commented
Fixed, also moved seds in ebuild to patch

2024-06-08 06:49 UTC, juippis commented on net-misc/netkit-timed/netkit-timed-0.17-r13.ebuild
> +KEYWORDS="~amd64 ~x86"
You are dropping the last remaining stable ebuild with this, and dropping other currently supported architechtures with it. I'd recommend just doing a new revision copy and **not** deleting the current -r11 ebuild.

2024-07-20 05:37 UTC, juippis reviewed
```
measure.c: In function 'measure':
measure.c:132:41: error: passing argument 6 of 'recvfrom' from incompatible pointer type [-Wincompatible-pointer-types[https://gcc.gnu.org/onlinedocs/gcc-14.1.0/gcc/Warning-Options.html#index-Wincompatible-pointer-types]]
  132 |                                       0,&length);
      |                                         ^~~~~~~
      |                                         |
      |                                         size_t * {aka long unsigned int *}
In file included from /usr/include/sys/socket.h:343,
                 from ../timed/globals.h:42,
                 from measure.c:44:
/usr/include/bits/socket2.h:62:56: note: expected 'socklen_t * restrict' {aka 'unsigned int * restrict'} but argument is of type 'size_t *' {aka 'long unsigned int *'}
   62 |           __SOCKADDR_ARG __addr, socklen_t *__restrict __addr_len)
      |                                  ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
measure.c:221:41: error: passing argument 6 of 'recvfrom' from incompatible pointer type [-Wincompatible-pointer-types[https://gcc.gnu.org/onlinedocs/gcc-14.1.0/gcc/Warning-Options.html#index-Wincompatible-pointer-types]]
  221 |                                       0,&length);
      |                                         ^~~~~~~
      |                                         |
      |                                         size_t * {aka long unsigned int *}
/usr/include/bits/socket2.h:62:56: note: expected 'socklen_t * restrict' {aka 'unsigned int * restrict'} but argument is of type 'size_t *' {aka 'long unsigned int *'}
   62 |           __SOCKADDR_ARG __addr, socklen_t *__restrict __addr_len)
      |                                  ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
make[2]: *** [../../MRULES:4: measure.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/var/tmp/portage/net-misc/netkit-timed-0.17-r11/work/netkit-timed-0.17/timed/lib'
make[1]: *** [Makefile:2: compile] Error 2
make[1]: Leaving directory '/var/tmp/portage/net-misc/netkit-timed-0.17-r11/work/netkit-timed-0.17/timed'
make: *** [Makefile:7: timed.build] Error 2
 * ERROR: net-misc/netkit-timed-0.17-r11::gentoo failed (compile phase):
 *   emake failed
```

2025-01-09 18:15 UTC, NHOrus commented
Okay, you may have checked wrong ebuild, that error is from -r11
Either way, I updated the ebuild and patches, now it works with C23

2025-01-17 13:28 UTC, juippis approved these changes

2025-01-17 13:36 UTC, closed without merging