sys-apps/attr: Add missing libgen.h include for basename(3)
gentoo/gentoo pull request #36010
Opened 2024-03-31 04:13 UTC by lanodan

Fixes compilation issue with musl and modern C99 compilers.

Closes: https://bugs.gentoo.org/926294

2024-04-28 11:50 UTC, akhuettel requested changes
This means the code does not use GNU basename but POSIX basename, which modifies its argument. For sure compiles, but does it run or does it crash?
=> Not a valid solution.

2024-05-05 12:46 UTC, closed without merging

2024-05-13 22:41 UTC, neheb commented
```
#include <stdio.h>
#include <stdint.h>
#include <libgen.h>
#include <string.h>

int main(int argc, char **argv)
{
        char* cpy = strdup(argv[0]);
        printf("%s\n", cpy);
        printf("MANGIX: %s\n", basename(cpy));
        printf("%s\n", cpy);
}
```

```
~> /home/mangix/a.out
/home/mangix/a.out
MANGIX: a.out
/home/mangix/a.out
```

I see no modification.

2024-05-14 00:41 UTC, floppym commented
Your test case is insufficient.
```
% cat basename.c
#include <stdio.h>
#include <stdint.h>
#include <libgen.h>
#include <string.h>

int main(int argc, char **argv)
{
        char* cpy = strdup(argv[1]);
        printf("%s\n", cpy);
        printf("MANGIX: %s\n", basename(cpy));
        printf("%s\n", cpy);
}

% make basename
cc     basename.c   -o basename

% ./basename /usr/
/usr/
MANGIX: usr
/usr
```

2024-05-14 01:06 UTC, neheb commented
sure but you're using argv[1]. argv[0] is used here.

2024-05-14 01:40 UTC, floppym commented
I was simply demonstrating how basename() an in fact modify its argument. argv[0] vs argv[1] is irrelevant.

If you are trying to say that argv[0] can never have a value which basename() might modify, you would be incorrect.

2024-05-14 01:46 UTC, floppym commented
That said, in this particular case, it probably doesn't matter if argv[0] is modified, but that's a separate issue.

2024-05-14 01:51 UTC, lanodan commented
Yeah, by the way, one way you can see it is with executing with a fullpath:

```
% cat /tmp/basename.c
#include <stdio.h>
#include <stdint.h>
#include <libgen.h>
#include <string.h>

int main(int argc, char **argv)
{
         char* cpy = strdup(argv[0]);
         printf("%s\n", cpy);
         printf("MANGIX: %s\n", basename(cpy));
         printf("%s\n", cpy);
}

% ${CC:-cc} -o /tmp/basename /tmp/basename.c
% /tmp/basename
/tmp/basename
MANGIX: basename
/tmp/basename
```

2024-05-14 01:54 UTC, floppym commented
```
% (exec -a /any/old/path/ ./basename)
/any/old/path/
MANGIX: path
/any/old/path
```

2024-05-14 02:09 UTC, lanodan commented
And in any case, I think the more safe/conservative fix done in 4b0abe03311391d346cd1c5a80f1b96318585d64 is preferable, at least until upstream reponse.

Althought it would mean attr could have been getting some side-effects prior to the declaration cleaning in musl-1.2.5.

2024-05-14 03:17 UTC, neheb commented
I’ve heard of implementing basename in terms of strrchr to be a poor man’s basename. Not sure how much truth there is to that.