sys-kernel/dracut: 101 revbump for systemd 255 incompatibility
gentoo/gentoo pull request #36135
Opened 2024-04-06 09:27 UTC by LaszloGombos

dracutdevs/dracut --> dracut-ng/dracut-ng

Thank you for your consideration !

CC @AndrewAmmerlaan

2024-04-06 09:36 UTC, AndrewAmmerlaan approved these changes
Thanks, looks good to me :+1:.

We should also adjust `metadata.xml` with the new upstream:
```
	<upstream>
		<remote-id type="github">dracutdevs/dracut</remote-id>
	</upstream>
```

2024-04-06 09:54 UTC, AndrewAmmerlaan commented
> Thanks @AndrewAmmerlaan . Seems there is a build failure that i need some help with, please.
> 
> `distfile missing from Manifest: [ dracut-100.tar.gz ]`

This just means that the entry in the manifest for the new version is missing. It's resolved by regenerating the manifest with `pkgdev manifest`.

2024-04-06 10:41 UTC, Dessa commented on sys-kernel/dracut/dracut-9999.ebuild
>  	EGIT_REPO_URI="https://github.com/dracutdevs/dracut"
```suggestion
	EGIT_REPO_URI="https://github.com/dracut-ng/dracut-ng"
```

2024-04-06 19:31 UTC, floppym commented
I think this should be added as dracut-100 (no -r1).

2024-04-06 20:21 UTC, Dessa commented on sys-kernel/dracut/dracut-100.ebuild
> +fi
needs
``	S="${WORKDIR}/${PN}-ng-${PV}"``
after SRC_URI

2024-04-06 23:37 UTC, Dessa approved these changes
builds fine now, generated image works too

2024-04-07 15:26 UTC, Dessa requested changes

2024-04-07 15:26 UTC, Dessa commented on sys-kernel/dracut/Manifest
> +DIST dracut-100.tar.gz 556103 BLAKE2B 639855491ac7800a1ad35f97b87dde637c4e1a0e4de2b644277df38c9bf7a9b179ad595de2e8a7cd580c51b8b953f995c16de9a5b9728120c9bf5f79b7a305ed SHA512 260c0c5761f9a9b12488a0a01
``pkgdev manifest``

2024-04-07 16:56 UTC, AndrewAmmerlaan approved these changes

2024-04-07 16:57 UTC, AndrewAmmerlaan commented on sys-kernel/dracut/dracut-101.ebuild
> +	"${FILESDIR}"/dracut-060-grub-layout.patch
This patch should become unnecessary after merging https://github.com/dracut-ng/dracut-ng/pull/111 upstream.

2024-04-09 02:52 UTC, floppym approved these changes

2024-04-09 07:44 UTC, closed without merging

2024-04-09 07:44 UTC, AndrewAmmerlaan commented
Thanks :+1: