*/*: Bump qalculate packages
gentoo/gentoo pull request #36217
Opened 2024-04-11 23:04 UTC by csfore

- sci-calculators/qalculate-{gtk,qt} to 5.0.0
- sci-libs/libqalculate to 5.0.0
- SONAME did not change in libqalculate

All tests pass on amd64.

2024-04-11 23:21 UTC, thesamesam requested changes
One commit per package please

2024-04-11 23:21 UTC, thesamesam commented on sci-calculators/qalculate-gtk/qalculate-gtk-5.0.0.ebuild
> +KEYWORDS="~alpha amd64 ~arm64 ~hppa ~ppc ~ppc64 ~sparc ~x86 ~amd64-linux ~x86-linux"
pkgcheck scan --commits

2024-04-12 01:51 UTC, csfore commented on sci-calculators/qalculate-gtk/qalculate-gtk-5.0.0.ebuild
> +KEYWORDS="~alpha amd64 ~arm64 ~hppa ~ppc ~ppc64 ~sparc ~x86 ~amd64-linux ~x86-linux"
Fixed!

2024-04-12 11:46 UTC, closed without merging

2024-04-12 11:46 UTC, AndrewAmmerlaan commented
Thanks :+1: