media-sound/lollypop: Add me as maintainer, add 1.4.38, enable py3.12, fix shebang, print only relevant elogs, remove old
gentoo/gentoo pull request #36229
Opened 2024-04-12 17:51 UTC by Leo3418

Some other distributions have started to ship Lollypop 1.4.38 already (e.g. [Debian](https://salsa.debian.org/python-team/packages/lollypop/-/tree/debian/1.4.38-1?ref_type=tags), [Fedora](https://src.fedoraproject.org/rpms/lollypop/c/fd98d19ddd553d8e1ed7264464268c5b67c17b54?branch=rawhide), [openSUSE](https://build.opensuse.org/request/show/1164230)).  The upstream GitLab repo had a 1.4.38 tag a few weeks ago, but the tag has gone for unknown reason as of now, so we still have to use the `SRC_URI` on an unaffiliated domain (adishatz.org) instead of a GitLab tarball.  For this reason, I was a bit skeptical about adding 1.4.38 at first considering how a non-Git tarball could be added a backdoor in the recent xz-utils event; however, since Fedora is still using the same domain in their source URL, I would trust it for now.

2024-04-13 14:14 UTC, mgorny requested changes

2024-04-13 14:14 UTC, mgorny commented on media-sound/lollypop/lollypop-1.4.38.ebuild
> +inherit python-single-r1 gnome2-utils meson xdg
Please keep inherits sorted.

2024-04-13 14:14 UTC, mgorny commented on media-sound/lollypop/lollypop-1.4.38.ebuild
> +PYTHON_COMPAT=( python3_{10..12} )
I suppose you want to use `Closes:` in the commit message to close the relevant bug.

2024-04-13 14:14 UTC, mgorny commented on media-sound/lollypop/lollypop-1.4.38.ebuild
> +	gui-libs/libhandy:1[introspection]
Please sort, it makes it easier to check things afterwards.

2024-04-14 15:01 UTC, Leo3418 commented
Upstream just released 1.4.39

2024-04-16 09:11 UTC, Leo3418 commented
> @Leo3418 with newly 1.4.39, I saw you still use tarball from adishatz, so is this your plan? and still works fine? (I think there would be some extra work if want to switch to use tag/release from upstream..)

Nice catch. I had added a brief comment above `SRC_URI` explaining why using tarballs from adishatz.org is necessary. The upstream Git repo uses a submodule, which is required to build the package but not included in GitLab tarballs. adishatz.org tarballs do include the submodules' files.

2024-04-18 11:33 UTC, closed without merging