www-apps/hugo: add 0.125.4
gentoo/gentoo pull request #36403
Opened 2024-04-24 12:52 UTC by tastytea

2024-04-25 23:03 UTC, Jamim requested changes
_Hello @tastytea,_

First of all, thank you for keeping **Hugo** up-to-date in Gentoo Linux! 🙇🏼

I noticed that **Hugo** `0.125.4` [has been released](https://github.com/gohugoio/hugo/releases/tag/v0.125.4).
Would you mind updating the PR in favor of the latest version?

_Thanks in advance!_

2024-04-26 09:26 UTC, tastytea commented
sure, on it!

2024-04-26 10:40 UTC, Jamim approved these changes

2024-04-29 08:43 UTC, ceamac approved these changes

2024-04-29 08:43 UTC, ceamac commented on www-apps/hugo/hugo-0.125.4.ebuild
> +KEYWORDS="amd64 ~arm64 ~loong ~riscv ~x86"
```suggestion
KEYWORDS="~amd64 ~arm64 ~loong ~riscv ~x86"
```
I'll fix this while merging

2024-04-29 08:47 UTC, closed without merging

2024-04-29 08:49 UTC, tastytea commented on www-apps/hugo/hugo-0.125.4.ebuild
> +KEYWORDS="amd64 ~arm64 ~loong ~riscv ~x86"
oops, thank you! 💖