New package: app-emacs/eldoc-box
gentoo/gentoo pull request #36476
Opened 2024-04-29 10:01 UTC by ArsenArsen

2024-04-29 10:13 UTC, ArsenArsen commented
hmm, no - that should not be proxy-maint, but rather @gentoo/gnu-emacs

2024-04-29 10:41 UTC, xgqt requested changes

2024-04-29 10:41 UTC, xgqt commented on app-emacs/eldoc-box/files/50eldoc-box-gentoo.el
We can easily make use of the defined modes in the source.
No need to use `elisp-make-autoload-file` here. I think it is pretty safe to include only those 2 modes.

```lisp
;;;###autoload
(define-minor-mode eldoc-box-hover-mode
  "Display hover documentations in a childframe.
The default position of childframe is upper corner."
  :lighter eldoc-box-lighter
  (if eldoc-box-hover-mode
      (progn (when eldoc-box-hover-at-point-mode
               (eldoc-box-hover-at-point-mode -1))
             (eldoc-box--enable))
    (eldoc-box--disable)))

;;;###autoload
(define-minor-mode eldoc-box-hover-at-point-mode
  "A convenient minor mode to display doc at point.
You can use \\[keyboard-quit] to hide the doc."
```

2024-04-29 10:41 UTC, xgqt commented on app-emacs/eldoc-box/metadata.xml
> +    <remote-id type="github">casouri/eldoc-box</remote-id>
\+ issues https://github.com/casouri/eldoc-box/issues

2024-04-29 10:43 UTC, xgqt commented
I personally do not split add VERSION and add 9999, but its up to you.

2024-04-29 11:19 UTC, ArsenArsen commented on app-emacs/eldoc-box/files/50eldoc-box-gentoo.el
that seems valid but I see no upside over generating the autoloads (I'm of the opinion that repetitive code that can be generated should be generated).  what's the advantage?

2024-04-29 11:35 UTC, xgqt commented on app-emacs/eldoc-box/files/50eldoc-box-gentoo.el
> that seems valid but I see no upside over generating the autoloads (I'm of the opinion that repetitive code that can be generated should be generated). what's the advantage?

- adding less autoloaded functions - you will only see the 2 modes in interactive function selection (M-x), not the support function that also is marked as autoload
- additionally sometimes authors do not add function doc which maintainer can add in the gentoo.el
- easier to know if modes might clash on auto-mode-alist (for lang modes)
- smaller install size (but of course only few kilobytes)
- you skip the call which is faster to install (of course <1ms most of the time)

2024-04-29 12:38 UTC, ulm commented on app-emacs/eldoc-box/files/50eldoc-box-gentoo.el
> that seems valid but I see no upside over generating the autoloads (I'm of the opinion that repetitive code that can be generated should be generated). what's the advantage?

In addition to what @xgqt already said, some packages tend to add autoload cookies somewhat at random. For example, it makes little sense to autoload commands that are useful only inside a mode, in addition to autoloading that mode itself. This just adds unnecessary ballast which slows startup of Emacs.

2024-04-29 14:59 UTC, ArsenArsen commented on app-emacs/eldoc-box/files/50eldoc-box-gentoo.el
looking over the generated autoloads I see three autoloads:

```el
(autoload 'eldoc-box-help-at-point "eldoc-box" "\
(autoload 'eldoc-box-hover-mode "eldoc-box" "\
(autoload 'eldoc-box-hover-at-point-mode "eldoc-box" "\
```

arguably all three are user facing functionality (for instance, I use the former without the latter two modes)

so, while I know of examples in the general case that I can agree with you on, this particular instance seems to be generating the correct autoloads

2024-04-29 15:37 UTC, xgqt commented on app-emacs/eldoc-box/files/50eldoc-box-gentoo.el
> looking over the generated autoloads I see three autoloads:
> 
> ```emacs-lisp
> (autoload 'eldoc-box-help-at-point "eldoc-box" "\
> (autoload 'eldoc-box-hover-mode "eldoc-box" "\
> (autoload 'eldoc-box-hover-at-point-mode "eldoc-box" "\
> ```
> 
> arguably all three are user facing functionality (for instance, I use the former without the latter two modes)

Wasn't the package designed to automatically open a eldoc frame on moving a point to a object that has documentation associated with it? In my opinion the only function that the user would want is that core one - the `eldoc-box-hover-at-point-mode` if im not mistaken.

I approach `elisp-make-autoload-file` as a "hammer" when:
package has weird internal logic and/or
when package somehow requires a lot of autoloads and/or
when package was shown to change around the function names or use pipeline (and break workflows).

But `elisp-make-autoload-file` can also be seen as general automation and there is nothing wrong with that as long as it is not a performance penalty (when package autoloads are overzealous). 
Me (and Ulm) and You would never agree on this case here because our approaches are completely different as described BUT your PR is correct and I will not modify this package to use the other method. I think it is ready to be merged.

2024-04-29 15:59 UTC, ArsenArsen commented on app-emacs/eldoc-box/files/50eldoc-box-gentoo.el
> > looking over the generated autoloads I see three autoloads:
> > ```emacs-lisp
> > (autoload 'eldoc-box-help-at-point "eldoc-box" "\
> > (autoload 'eldoc-box-hover-mode "eldoc-box" "\
> > (autoload 'eldoc-box-hover-at-point-mode "eldoc-box" "\
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > arguably all three are user facing functionality (for instance, I use the former without the latter two modes)
> 
> Wasn't the package designed to automatically open a eldoc frame on moving a point to a object that has documentation associated with it? In my opinion the only function that the user would want is that core one - the `eldoc-box-hover-at-point-mode` if im not mistaken.

yes, but it also documents manually popping up a buffer on request (and does so while explicitly mentioning that the mode is not required in the readme):

> **`eldoc-box-help-at-point`** :: Display the documentation of the symbol at point in a temporary childframe, moving point or typing `C-g` disposes the childframe. This command simply displays what would be displayed by `eldoc-doc-buffer` in a childframe, so it requires Emacs 28, and  `eldoc-box-hover-mode` doesn’t need to be on for this command to work.

... so I think it is intended for general use

> I approach `elisp-make-autoload-file` as a "hammer" when: package has weird internal logic and/or when package somehow requires a lot of autoloads and/or when package was shown to change around the function names or use pipeline (and break workflows).
> 
> But `elisp-make-autoload-file` can also be seen as general automation and there is nothing wrong with that as long as it is not a performance penalty (when package autoloads are overzealous). Me (and Ulm) and You would never agree on this case here because our approaches are completely different as described BUT your PR is correct and I will not modify this package to use the other method. I think it is ready to be merged.

thanks for understanding.  to be clear, I do steer towards hand-written autoloads when there is a penalty ;)  I looked at the autoload cookies ahead of time also to confirm that they aren't wrong when writing the ebuild

2024-04-29 23:18 UTC, closed without merging

2024-04-30 05:54 UTC, Flowdalic commented on app-emacs/eldoc-box/files/50eldoc-box-gentoo.el
This seems to be a common point where different views emerge, since we had a similar discussion when I added `app-emacs/scala-ts-mode`. Not saying that one side is correct while the other isn't. That indicates that we may want to document the pros and cons of the two different approaches. Is that maybe already done somewhere on the wiki?

2024-04-30 06:05 UTC, ulm commented on app-emacs/eldoc-box/files/50eldoc-box-gentoo.el
There's a writeup at https://wiki.gentoo.org/wiki/Project:GNU_Emacs/Developer_guide#The_site-lisp_directory_and_package_loading but it is sparse. (At least it says that `load` commands should be avoided because they make start-up slow.)