dev-libs/libclc: Use correct LLVM_COMPAT version
gentoo/gentoo pull request #36478
Opened 2024-04-29 10:34 UTC by FireBurn

libclc 18 should be compiled against llvm 18

2024-04-29 19:01 UTC, mgorny requested changes
Also set 19.0.0.9999 to the same.

2024-04-29 19:01 UTC, mgorny commented on dev-libs/libclc/libclc-18.1.4.ebuild
> +LLVM_COMPAT=( 18 )
Make it `17..18`. The only reasons older versions ain't here are limited keywords on spirv-llvm-translator.

2024-05-06 05:49 UTC, leio commented
https://bugs.gentoo.org/931280

2024-05-06 15:07 UTC, mgorny commented
I'm sorry, but this is taking too long. I'm going to fix it myself.

2024-05-06 15:07 UTC, closed without merging