media-libs/nas: Fix passing of incompatible pointer type
gentoo/gentoo pull request #36484
Opened 2024-04-29 19:55 UTC by listout

Closes: https://bugs.gentoo.org/927451

2024-05-22 21:41 UTC, parona-source commented
Seeing the discussion you had upstream maybe its better to close this and handle it with libXaw? 

Otherwise it would get weird if the change is backported meaning this breaks again.

https://sourceforge.net/p/nas/bugs/15/

2024-06-29 10:01 UTC, fordfrog requested changes

2024-06-29 18:01 UTC, listout commented on media-libs/nas/files/nas-1.9.5-gcc14-build-fix.patch
> ++    int             i;
Should be good now, what do you think?

2024-06-30 11:01 UTC, closed without merging

2024-06-30 11:01 UTC, fordfrog commented
@listout thanks! i also dropped -r1