sys-apps/dstat: upgrade to python 3.12
gentoo/gentoo pull request #36571
Opened 2024-05-05 14:11 UTC by lmiphay

add python 3.12
fix use of unescaped backslashes in regex strings

Bug: https://bugs.gentoo.org/929807
Signed-off-by: Paul Healy <lmiphay@gmail.com>

2024-05-08 16:01 UTC, arthurzam requested changes

2024-05-08 16:01 UTC, arthurzam commented on sys-apps/dstat/dstat-0.7.4-r3.ebuild
> +EAPI=7
can you bump to EAPI=8?

2024-05-08 16:01 UTC, arthurzam commented on sys-apps/dstat/dstat-0.7.4-r3.ebuild
> +PYTHON_COMPAT=( python3_{9..12} )
```suggestion
PYTHON_COMPAT=( python3_{10..12} )
```

2024-05-08 16:01 UTC, arthurzam commented on sys-apps/dstat/dstat-0.7.4-r3.ebuild
> +}
put it before `src_install`, since it is called before install

2024-05-14 18:08 UTC, lmiphay commented
Updated as per comments. Thanks!

2024-05-16 14:48 UTC, closed without merging