gnome-extra/gnome-browser-connector: enable py3.12
gentoo/gentoo pull request #36586
Opened 2024-05-06 16:09 UTC by roarc0

enable py3.12

2024-05-06 16:14 UTC, nE0sIghT commented
Fixes: https://bugs.gentoo.org/929602

P.S.: I didn't tested it yet

2024-05-07 05:52 UTC, roarc0 commented
I've compiled it with the 3.12 flag then rebooted chrome and extensions.gnome.org shows my currently installed extensions. When I try to install one it just downloads the extension archive.

2024-05-28 10:38 UTC, mgorny requested changes
Need signoff on this.

2024-05-28 10:38 UTC, mgorny commented on gnome-extra/gnome-browser-connector/gnome-browser-connector-42.1.ebuild
> +PYTHON_COMPAT=( python3_{9..12} )
Please remove 3.9 while at it.

2024-05-28 11:52 UTC, closed without merging