gui-libs/wlroots: fix automagic of libliftoff and lcms, drop USE=tinywl; add gui-wm/tinywl
gentoo/gentoo pull request #37060
Opened 2024-06-06 18:52 UTC by sevz17

---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

2024-06-06 18:53 UTC, sevz17 commented on gui-wm/tinywl/metadata.xml
> +	<maintainer type="person" proxied="yes">
@arthurzam @prometheanfire do you want me to add you as maintainers?

2024-06-07 08:54 UTC, thesamesam commented
Please update the commit messages to explain rationale.

2024-06-07 08:55 UTC, thesamesam requested changes

2024-06-07 08:55 UTC, thesamesam commented on gui-wm/tinywl/tinywl-0.17.3.ebuild
> +	!!gui-libs/wlroots[tinywl(-)]
A hard blocker isn't right here and it prevents the dependency being resolved cleanly by Portage (it requires manual intervention). Hard blockers are only needed if something can't even be built if the other thing is installed, as opposed to a file collision which "allows" a file collision.

2024-06-07 08:55 UTC, thesamesam commented on gui-wm/tinywl/tinywl-0.17.3.ebuild
> +	make -C tinywl
This should be `emake` to handle failing and also parallel jobs.

2024-06-10 14:25 UTC, ezzieyguywuf commented on gui-libs/wlroots/files/wlroots-0.17-fix-automagic-libliftoff.patch
Tested this patch locally, it does solve the build-time error with `USE=-liftoff`

2024-06-11 05:55 UTC, arthurzam approved these changes

2024-06-11 05:56 UTC, closed without merging