sys-apps/eza: add 0.18.17
gentoo/gentoo pull request #37063
Opened 2024-06-06 23:38 UTC by sevz17

---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

2024-06-23 00:25 UTC, Jamim requested changes
_Hello @sevz17,_

Thank you for your work on **eza** in Gentoo!
I have a couple of minor suggestions. Hope you'll find them useful.

_Best regards!_

2024-06-23 00:25 UTC, Jamim commented on sys-apps/eza/eza-0.18.19.ebuild
> +	# Known failing test, upstream says it could potentially be ignored for know
```suggestion
	# Known failing test, upstream says it could potentially be ignored for now
```

2024-06-23 00:25 UTC, Jamim commented on sys-apps/eza/eza-0.18.19.ebuild
> +HOMEPAGE="https://github.com/eza-community/eza"
```suggestion
HOMEPAGE="https://eza.rocks https://github.com/eza-community/eza"
```

2024-06-24 05:04 UTC, sevz17 commented
@Jamim Thank you for the suggestions!

2024-06-24 09:59 UTC, Jamim approved these changes

2024-06-25 19:48 UTC, Jamim commented
_Hello @arthurzam,_

Would you mind merging this PR?

_Thanks in advance!_

2024-07-04 01:18 UTC, closed without merging