games-server/crossfire-server: add 1.75.0
gentoo/gentoo pull request #37270
Opened 2024-06-24 11:41 UTC by NHOrus

Bug: https://bugs.gentoo.org/734314
Bug: https://bugs.gentoo.org/871441
Bug: https://bugs.gentoo.org/904073

Version bump of the server to fix bugs;

I can't make a client work, due to unpiped USE=sound flag (it compules with USE=sound, it fails with USE=-sound, because only roughly half of the code is wired to disable sound)
---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

2024-07-04 08:07 UTC, mm1ke commented on games-server/crossfire-server/crossfire-server-1.75.0.ebuild
> +S="${WORKDIR}/${MY_P}"
could you move that below `SRC_URI`?

2024-07-04 08:08 UTC, mm1ke commented on games-server/crossfire-server/crossfire-server-1.75.0.ebuild
> +}
I think `src_configure` could be removed entirely. `EAPI8` already pass `--disable-static` per default (if it's available in the configure script)

2024-07-28 20:44 UTC, chewi requested changes
@mm1ke is right, please make those changes.

2024-12-29 15:57 UTC, NHOrus commented
Changes made

2025-02-10 09:16 UTC, closed without merging