sys-fs/rar2fs: Upgrade to rar2fs 1.29.7
gentoo/gentoo pull request #37316
Opened 2024-06-27 00:27 UTC by fdegros

Bug: https://bugs.gentoo.org/930341
Bug: https://bugs.gentoo.org/931078

---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

2024-07-04 08:01 UTC, mm1ke commented
while at it, could you also update the `LICENSE`, should be `GPL-3+`, see: https://github.com/hasse69/rar2fs/blob/master/src/rar2fs.c#L4-L7

2024-07-12 05:04 UTC, eli-schwartz requested changes
Just to note: the "Bug" metadata should be "Closes".

Unfortunately, the SRC_URI appears to be invalid, since this release doesn't have any tarballs attached to the release -- only the github autogenerated tarball.

Hence:
```
!!! Couldn't download 'rar2fs-1.29.7.tar.gz'. Aborting.
```

2024-08-15 09:50 UTC, tfiskgul commented
Thanks for your merge request @fdegros. In an attempt to get rar2fs to compile on my machine, I added your gentoo repository as an overlay, but get a strange error when trying to merge the ebuild:
`no configure script found`

Which is strange, since the configure scripts doesn't appear to have been changed between the tarballs of 1.29.6 vs 1.29.7 

```
$ sudo cat /var/tmp/portage/sys-fs/rar2fs-1.29.7/temp/build.log
Password:
 * Package:    sys-fs/rar2fs-1.29.7:0
 * Repository: fdegros
 * Maintainer: fdegros@chromium.org proxy-maint@gentoo.org
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux
 * FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking rar2fs-1.29.7.tar.gz to /var/tmp/portage/sys-fs/rar2fs-1.29.7/work
>>> Source unpacked in /var/tmp/portage/sys-fs/rar2fs-1.29.7/work
>>> Preparing source in /var/tmp/portage/sys-fs/rar2fs-1.29.7/work/rar2fs-1.29.7 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/sys-fs/rar2fs-1.29.7/work/rar2fs-1.29.7 ...
 * ERROR: sys-fs/rar2fs-1.29.7::fdegros failed (configure phase):
 *   no configure script found
 *
 * Call stack:
 *          ebuild.sh, line 136:  Called src_configure
 *        environment, line 514:  Called econf '--with-unrar=/usr/include/libunrar' '--disable-static-unrar' '--disable-debug'
 *   phase-helpers.sh, line 725:  Called die
 * The specific snippet of code:
 *              die "no configure script found"
 *
 * If you need support, post the output of `emerge --info '=sys-fs/rar2fs-1.29.7::fdegros'`,
 * the complete build log and the output of `emerge -pqv '=sys-fs/rar2fs-1.29.7::fdegros'`.
 * The complete build log is located at '/var/tmp/portage/sys-fs/rar2fs-1.29.7/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sys-fs/rar2fs-1.29.7/temp/environment'.
 * Working directory: '/var/tmp/portage/sys-fs/rar2fs-1.29.7/work/rar2fs-1.29.7'
 * S: '/var/tmp/portage/sys-fs/rar2fs-1.29.7/work/rar2fs-1.29.7'
```

2024-08-16 00:10 UTC, fdegros commented
Strange, indeed. But sorry, I cannot help you there. I don't maintain this [package](https://packages.gentoo.org/packages/sys-fs/rar2fs) anymore. You might have to find a new maintainer for this package.

2024-09-04 06:24 UTC, hasse69 commented
Since the released artifact is not built using 'make dist', there is no configure script in the tar-ball. You need to update the build procedure according to how it is described in the wiki, e,g

autoreconf -f -i
./configure && make
sudo make install

2024-12-22 14:05 UTC, ceamac commented
You need to add `eautoreconf` in `src_prepare()`.  Also switching `econf` to array format would be nice.

2025-01-08 00:57 UTC, fdegros commented
I don't maintain this [package](https://packages.gentoo.org/packages/sys-fs/rar2fs) anymore.

2025-01-08 00:57 UTC, closed without merging