app-misc/keyd: new package, add 2.4.3
gentoo/gentoo pull request #37504
Opened 2024-07-09 23:24 UTC by waffle87

acct-group/keyd: add 2.4.3

[keyd](https://github.com/rvaiya/keyd) is a key remapping daemon for Linux. This PR adds support for the program itself, the group it requires (I am not sure if patching the Makefile to not manually create the group is best practice), and an OpenRC script (Systemd is natively supported in Makefile). I am unsure the `docompress` usage is correct, as the man pages are already gzip archives in the source.

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

2025-02-24 21:23 UTC, closed without merging

2025-02-24 22:30 UTC, eli-schwartz requested changes

2025-02-24 22:30 UTC, eli-schwartz commented on app-misc/keyd/keyd-2.5.0.ebuild
> +	docompress -x /usr/share/man/man1/keyd-application-mapper.1.gz
Note that these should actually be decompressed in the ebuild so that portage can perform its own compression as controlled by the user (not using gzip, even, since Gentoo defaults to bzip2 instead).

2025-02-24 22:30 UTC, eli-schwartz commented on app-misc/keyd/files/keyd-2.5.0-makefile.patch
> ++PREFIX=$(EPREFIX)/usr
Typically you'd pass `PREFIX="${EPREFIX}/usr"` as an argument to `emake install` instead of patching the Makefile. Also consider pleading with upstream to use a real build system, such as Meson or autoconf.

2025-02-24 22:30 UTC, eli-schwartz commented on app-misc/keyd/files/keyd-2.5.0-makefile.patch
> +-	-groupadd keyd
Consider submitting an upstream patch to only execute this if DESTDIR is unset.

2025-03-15 21:37 UTC, waffle87 commented
Thank you for these reviews, I will what I can manage! Albeit this PR is closed, I have submitted this to the GURU repository, so I will make changes there.