net-mail/gnubiff-2.2.17: Fix 880267 (clang compilation), 930500 (LICENSE), 933241 (EAPI)
gentoo/gentoo pull request #37513
Opened 2024-07-10 19:32 UTC by UnixRonin

net-mail/gnubiff: add 2.2.17-r3

Also adds a new LICENSE GPL-3+-with-openssl-exception

Closes: https://bugs.gentoo.org/880267
Closes: https://bugs.gentoo.org/930500
Closes: https://bugs.gentoo.org/933241

---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

2024-07-10 19:46 UTC, UnixRonin commented
This is a clean resubmission of the original PR, after I made a complete and utter mess of squashing commits because I didn't understand how squashing worked, then proceeded to dig myself deeper from there.

2024-07-10 20:18 UTC, AngryLoki commented on net-mail/gnubiff/gnubiff-2.2.17-r3.ebuild
> +}
```suggestion
PATCHES=(
	"${FILESDIR}"/${PN}-2.2.17-clang.patch
)

src_prepare() {
	default
	eautoreconf
}
```

2024-07-10 20:18 UTC, AngryLoki commented on net-mail/gnubiff/files/gnubiff-2.2.17-clang.patch
> +--- gnubiff-2.2.17/src/Makefile.am.orig	2016-06-12 04:18:12.000000000 -0400
Please apply `scrub-patch` (https://devmanual.gentoo.org/ebuild-writing/misc-files/patches/index.html#clean-patch-howto)
and add short description mentioning #930500

2024-07-11 10:58 UTC, arthurzam requested changes
please handle QA issue:
```
UnnecessaryManifest	unnecessary files in Manifest: [ gnubiff-2.2.17-clang.patch, gnubiff-2.2.17-configure.patch, gnubiff-2.2.17-fix-nls.patch, gnubiff-2.2.17-r2.ebuild, gnubiff-2.2.17-r3.ebuild, metadata.xml ]
```

I also think you drop patches used by the previous version, meaning premature removal

2024-07-11 10:58 UTC, arthurzam commented on net-mail/gnubiff/gnubiff-2.2.17-r3.ebuild
> +# This package depends upon deprecated gnome-base/libglade.  An
wrong place for the comment, put it just above RDEPEND

2024-07-11 10:58 UTC, arthurzam commented on net-mail/gnubiff/gnubiff-2.2.17-r3.ebuild
> +inherit autotools
```suggestion
EAPI=8

inherit autotools
```

2024-07-11 10:58 UTC, arthurzam commented on net-mail/gnubiff/gnubiff-2.2.17-r3.ebuild
> +}
```suggestion
src_configure() {
	local myeconfargs=(
		--disable-gnome # avoid deprecated gnome-panel-2.x
		$(use_enable debug)
		$(use_enable nls)
		$(use_enable fam)
		$(use_with password)
		$(use_with password password-string ${RANDOM}${RANDOM}${RANDOM}${RANDOM})
	)
	econf "${myeconfargs[@]}"
}
```

2024-07-12 14:24 UTC, closed without merging