www-servers/spawn-fcgi: add 1.6.5
gentoo/gentoo pull request #37529
Opened 2024-07-12 08:26 UTC by AndCycle

version bump

---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

2024-07-19 03:21 UTC, mattst88 commented
Is there any reason to disable IPv6 support in this package? We've been removing `IUSE=ipv6` when there's not a good reason to disable it.

2024-07-19 03:28 UTC, AndCycle commented
> Is there any reason to disable IPv6 support in this package? We've been removing `IUSE=ipv6` when there's not a good reason to disable it.

I just copy the old ebuild for this version bump

https://redmine.lighttpd.net/projects/spawn-fcgi/repository/13/revisions/master/entry/NEWS
```
- 1.6.5 - 2022-12-21
  * Configure script cleanups (fixing detection of IPv6)
  * Update links and email addresses
```
there is an old bug related to ipv6 been fixed so think it's safe to remove `IUSE=ipv6`

2024-07-20 16:06 UTC, mattst88 commented
```
!!! Fetched file: spawn-fcgi-1.6.5.tar.gz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      14369
!!! Expected: 14403
```

I don't know whether this is the result of the tarball being generated by github vs lighttpd's gitea.

I'd just get the file from http://download.lighttpd.net/spawn-fcgi/releases-1.6.x/spawn-fcgi-1.6.5.tar.gz which appears to be a static archive, and not generated on the fly.

Even better, there's an xz archive: http://download.lighttpd.net/spawn-fcgi/releases-1.6.x/spawn-fcgi-1.6.5.tar.xz

2024-07-20 16:10 UTC, mattst88 commented
These archives also have a `configure` script, so no need to `inherit autotools` or run `eautoreconf`.

2024-07-20 16:12 UTC, mattst88 requested changes

2024-07-20 16:12 UTC, mattst88 commented on www-servers/spawn-fcgi/spawn-fcgi-1.6.5.ebuild
> +"
Switch to

```
SRC_URI="http://download.lighttpd.net/spawn-fcgi/releases-1.6.x/${P}.tar.xz"
```

2024-07-20 16:12 UTC, mattst88 commented on www-servers/spawn-fcgi/spawn-fcgi-1.6.5.ebuild
> +S="${WORKDIR}/${PN}"
Can drop this with the new tarball.

2024-07-20 16:12 UTC, mattst88 commented on www-servers/spawn-fcgi/spawn-fcgi-1.6.5.ebuild
> +RDEPEND=""
Can drop these.

2024-07-20 16:12 UTC, mattst88 commented on www-servers/spawn-fcgi/spawn-fcgi-1.6.5.ebuild
> +}
Drop `src_prepare()`.

2024-07-20 16:12 UTC, mattst88 commented on www-servers/spawn-fcgi/spawn-fcgi-1.6.5.ebuild
> +inherit autotools
Can drop this with the new tarball.

2024-07-20 16:13 UTC, mattst88 commented
Can add a `remote-id` to github:

```
MissingRemoteId: missing <remote-id type="github">lighttpd/spawn-fcgi</remote-id> (inferred from URI 'https://github.com/lighttpd/spawn-fcgi/archive/refs/tags/spawn-fcgi-1.6.5.tar.gz')
```

2024-07-20 16:31 UTC, AndCycle commented
thanks for the in depth review

2024-07-20 17:19 UTC, closed without merging