media-libs/libsdl2: fix static build with >=gui-libs/libdecor-0.2.0
gentoo/gentoo pull request #37657
Opened 2024-07-21 16:40 UTC by AngryLoki

This applies https://github.com/libsdl-org/SDL/commit/4ce935b9106a0311436e41c5f28f00db30a93de1 to libsdl2-2.28.

No revbump (it is just a compilation fix).
Issue only affects libsdl-2.28 (no fix needed for 2.30).

Closes: https://bugs.gentoo.org/936443

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

2024-07-21 20:27 UTC, eli-schwartz commented
> No revbump (it is just a compilation fix).

Compilation fixes actually do affect codegen and can result in changing a crashing program to one that doesn't crash. General recommendation is you *should* revbump it.

2024-07-22 07:49 UTC, AngryLoki commented
@eli-schwartz , exactly this fix does not affect codegen and will not add/remove runtime crashes ("incompatible function pointer types assigning" - i. e. https://devmanual.gentoo.org/general-concepts/ebuild-revisions/index.html#:~:text=without%20a%20revision%20bump). Do you want me to bump the ebuild anyways?

2024-07-31 22:09 UTC, eli-schwartz requested changes
Commit message talks about USE=static-libs which is simply wrong :) it errors out on a pure shared lib build.

Upstream's commit message can say whatever it wishes but the fact remains that the failure is with --disable-static.

2024-08-01 05:49 UTC, AngryLoki commented
> Commit message talks about USE=static-libs which is simply wrong :) it errors out on a pure shared lib build.

Removed word "static"

2024-08-01 07:05 UTC, closed without merging