sys-apps/iproute2: Fix building on musl profile
gentoo/gentoo pull request #37658
Opened 2024-07-21 18:09 UTC by listout

Closes: https://bugs.gentoo.org/926341
Closes: https://bugs.gentoo.org/936234

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

2024-07-22 17:41 UTC, floppym commented
Please send patches upstream first. We can backport from there.

2024-07-23 06:22 UTC, listout commented
I did some time ago, but probably it got lost or something https://lore.kernel.org/netdev/20240514063811.383371-1-brahmajit.xyz@gmail.com/T/#u

2024-08-03 23:02 UTC, floppym requested changes
Please send a follow-up message to the upstream maintainers.

2024-08-03 23:02 UTC, floppym commented on sys-apps/iproute2/files/iproute2-6.10.0-fix-implecit-declaration-of-basename-on-musl.patch
> +On musl there is only one implementation of musl which comes from
```suggestion
On musl there is only one implementation of basename which comes from
```

2024-08-03 23:02 UTC, floppym commented on sys-apps/iproute2/files/iproute2-6.10.0-fix-implecit-declaration-of-basename-on-musl.patch
> +the posix implementation of basename.
If you are not sure the POSIX implementation is correct here, please look into it and confirm it.

2024-08-04 11:08 UTC, hhoffstaette commented
There are exactly two calls to `basename`:
```
$grep -r 'basename('
lib/bpf_legacy.c:			 basename(strdupa(cfg->object)),
rdma/rdma.c:	filename = basename(argv[0]);
```
`strdupa()` makes potential mutation safe, and AFAIK elements of argv can be mutated due to being declared non-const historically. Apparently [C99 also says this](https://stackoverflow.com/a/963777/99851). I don't see why applying the patch using libgen.h should not work.

2024-08-04 14:56 UTC, floppym commented
> `strdupa()` makes potential mutation safe, and AFAIK elements of `argv` can be mutated due to historically being declared non-const. Apparently [C99 also says this](https://stackoverflow.com/a/963777/99851). I don't see why applying the patch using libgen.h should not work.

Thanks, that's good enough for me.

2024-08-04 16:17 UTC, closed without merging