net-mail/*: EAPI=8 bumps & pkgcheck fixes
gentoo/gentoo pull request #37861
Opened 2024-07-31 12:41 UTC by fkobi

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

2024-08-01 16:44 UTC, a17r requested changes
If you are going to touch EAPI-7 ebuilds for minor stylistic changes, at least bump them to EAPI-8 at the same time (with all the necessary care doing so).

That also means you do the revbump necessary for an EAPI change and leave the existing stable ebuild alone.

2024-08-01 16:44 UTC, a17r commented on net-mail/qmhandle/qmhandle-1.3.2-r1.ebuild
> -DEPEND=""
does this really build without any dependencies?

2024-08-01 16:44 UTC, a17r commented on net-mail/qmhandle/qmhandle-1.3.2.ebuild
> -DEPEND=""
does this really build without any dependencies?

2024-08-01 16:44 UTC, a17r commented on net-mail/vqadmin/vqadmin-2.3.7-r1.ebuild
> +WEBAPP_MANUAL_SLOT="yes"
That looks like something we would normally put directly atop the `inherit` line, even if `webapp.eclass` completely lacks documentation in that regard.

Also, check (and fix) HOMEPAGE.

2024-08-02 09:33 UTC, arkamar requested changes

2024-08-02 09:33 UTC, arkamar commented on net-mail/qmail-notify/qmail-notify-0.93-r2.ebuild
>  RDEPEND="${DEPEND}
```suggestion
RDEPEND="
```
This is also not needed.

2024-08-07 19:34 UTC, closed without merging

2024-08-08 08:18 UTC, arkamar commented
All 3 were merged, look at https://github.com/gentoo/gentoo/commit/7279d36da8233714ed49d361d774d11614e15bb7 and two previous commits https://github.com/gentoo/gentoo/commit/ec86de6055d104bfdcbf39f62145efc483aa0c45 and https://github.com/gentoo/gentoo/commit/439e9a3498c34a6988246ae0877ccb2c6b810384.