dev-libs/libportal: add 9999 with qt6 support
gentoo/gentoo pull request #38065
Opened 2024-08-10 15:15 UTC by negril

needed to enable qt6 for x11-misc/input-leap::guru

Bug: https://github.com/flatpak/libportal/issues/152
Bug: https://github.com/input-leap/input-leap/issues/1912

2024-09-07 17:33 UTC, a17r requested changes
I see there is `0.8.1` available upstream, which presumably supports Qt6 already?

https://github.com/flatpak/libportal/releases/tag/0.8.1

That would benefit more users and may be easier to get merged here by gnome proj.

2024-09-07 17:33 UTC, a17r commented on dev-libs/libportal/libportal-9999.ebuild
> +if [[ ${PV} == *9999 ]]; then
```suggestion
if [[ ${PV} == *9999* ]]; then
```

2024-09-07 17:33 UTC, a17r commented on dev-libs/libportal/libportal-9999.ebuild
> +IUSE="gtk gtk-doc +introspection qt5 qt6 test +vala wayland X"
let's drop `qt5` here and in the follow-up `*DEPEND` and `emesonargs` blocks.

2024-09-07 17:58 UTC, negril commented
> I see there is `0.8.1` available upstream, which presumably supports Qt6 already?
> 
> https://github.com/flatpak/libportal/releases/tag/0.8.1
> 
> That would benefit more users and may be easier to get merged here by gnome proj. (maybe you want to `s/9999/0.8.1/`)

The PR predates the release of `0.8.0` by a month. But I'll see that I get this updated.

2024-09-07 18:09 UTC, a17r commented
> The PR predates the release of `0.8.0` by a month. But I'll see that I get this updated.

Sure, I'm aware of that. ;)

2025-01-06 20:43 UTC, a17r commented
see also https://github.com/gentoo/gentoo/pull/39717

2025-01-13 17:26 UTC, a17r requested changes

2025-01-13 17:26 UTC, a17r commented on dev-libs/libportal/libportal-0.9.0.ebuild
> +"
```suggestion
	qt6? ( dev-qt/qtbase[gui,wayland?,widgets,X?] )
"
DEPEND="${RDEPEND}"
```

2025-01-13 17:26 UTC, a17r commented on dev-libs/libportal/libportal-0.9.0.ebuild
> +		gui-libs/gtk:4[X?,wayland?]
```suggestion
		gui-libs/gtk:4[wayland?,X?]
		x11-libs/gtk+:3[wayland?,X?]
```

2025-02-16 23:10 UTC, closed without merging