net-irc/weechat: add 4.3.6, 4.4.0
gentoo/gentoo pull request #38189
Opened 2024-08-18 20:23 UTC by sevz17

---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

2024-08-23 01:30 UTC, eli-schwartz requested changes
```
>>> Preparing source in /var/tmp/portage/net-irc/weechat-4.4.1/work/weechat-4.4.1 ...
 * Source directory (CMAKE_USE_DIR): "/var/tmp/portage/net-irc/weechat-4.4.1/work/weechat-4.4.1"
 * Build directory  (BUILD_DIR):     "/var/tmp/portage/net-irc/weechat-4.4.1/work/weechat-4.4.1_build"
 * Applying weechat-3.3-cmake_lua_version.patch ...
patching file cmake/FindLua.cmake
Hunk #1 FAILED at 35.
1 out of 1 hunk FAILED -- saving rejects to file cmake/FindLua.cmake.rej                                                                                                                                    [ !! ]
 * ERROR: net-irc/weechat-4.4.1::gentoo failed (prepare phase):
 *   patch -p1  failed with /var/tmp/portage/net-irc/weechat-4.4.1/files/weechat-3.3-cmake_lua_version.patch
```

2024-08-23 01:31 UTC, eli-schwartz commented
See https://github.com/weechat/weechat/pull/2174

I guess this is actually what we want anyways, right? :)

2024-08-29 05:38 UTC, xen0n commented on net-irc/weechat/weechat-4.4.1.ebuild
> +LANGS=" cs de es fr it ja pl ru"
According to the 4.4.1 source:

```suggestion
LANGS=" cs de es fr hu it ja pl pt_BR pt ru sr tr"
```

2024-08-29 05:38 UTC, xen0n commented on net-irc/weechat/weechat-4.4.1.ebuild
> +	"${FILESDIR}"/${PN}-3.3-cmake_lua_version.patch
This is no longer needed for 4.4.1.

2024-09-01 06:09 UTC, sevz17 commented
I'm sorry for the very long delay.

And thank you @xen0n for the review.

2024-09-01 06:37 UTC, eli-schwartz commented
Upgrading to 4.4.1 works fine for me. I did try to /upgrade and it crashed when it tried to reload, but I could not reproduce it when I tried reproducing the upgrade scenario...

2024-09-01 06:41 UTC, closed without merging