sys-process/runit: fix compilation errors & warnings with clang 18/gc…
gentoo/gentoo pull request #38425
Opened 2024-09-04 11:11 UTC by clan

…c 15, update doc & obsoleted function

This PR is not ready for merged until:
1.  Gentoo Devs make decision on what to be merged of following 6 categories. Category 1, 2 are required.
2. After decision made by 1, I'll prepare the final patches either in FILESDIR or SRC_URI (via ithub release).

Patches divided into the following categories:

1. patch: 0001 purpose: helpful for development & debug: make full command line & result available in build.log, otherwise extra directives are required when debug
2. patch: 0002, 0003, 0004, 0005, 0006 purpose: required, build will failed if not apply 0005 & 0006 are warnings only for gcc < 14, errors if gcc >= 14
3. patch: 0007 purpose: patch from author w/ new feature provided, but don't change any "user-observable functionality"
4. patch: 0008 purpose: documentation change: w/ tiny (unlikely to cause problem) modification of source code
5. patch: 0009 - 0019 purpose: fix compilation warnings reported by gcc/clang, with -Wall, -Wextra
6. patch: 0020 purpose: usleep is obsoleted in POSIX.1-2001, handled this in compile time by feature test macro, replace w/ nanosleep if available

Closes: https://bugs.gentoo.org/934410
Closes: https://bugs.gentoo.org/938262
Closes: https://bugs.gentoo.org/938282
Closes: https://github.com/clan/runit/issues/2
Signed-off-by: Z. Liu <zhixu.liu@gmail.com> 
Tested-by: Alex Efros <powerman-asdf@yandex.ru>

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

2024-09-04 11:41 UTC, powerman commented
Patches LGTM.

I'm tired arguing for how many patches should be in the first PR and is it good idea to include patch 0007. All patches are fine and safe, at least as much as I can check.

2024-09-04 14:48 UTC, floppym requested changes
This looks pretty reasonable to me.

pkgcheck complains about the size of the patches, so they will need to be moved to a tarball.

Please add yourself as a maintainer to metadata.xml.

2024-09-05 14:34 UTC, clan commented
> pkgcheck complains about the size of the patches, so they will need to be moved to a tarball.
> 
> Please add yourself as a maintainer to metadata.xml.

updated, please review, thanks.

2024-09-05 14:37 UTC, floppym approved these changes

2024-09-05 14:42 UTC, closed without merging