app-editors/dav: add 0.9.0, update sources
gentoo/gentoo pull request #38432
Opened 2024-09-04 13:56 UTC by fkobi

- bump EAPI
- update SRC_URI & HOMEPAGE
- remove empty src_configure

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

2024-09-08 15:13 UTC, thesamesam commented on app-editors/dav/dav-0.9.0.ebuild
> +SRC_URI="https://github.com/atsb/dav-text/archive/refs/tags/dav-text-${PV}.tar.gz -> ${P}.tar.gz"
Why rename it at all?

2024-09-08 16:22 UTC, thesamesam commented on app-editors/dav/dav-0.9.0.ebuild
> +SRC_URI="https://github.com/atsb/dav-text/archive/refs/tags/dav-text-${PV}.tar.gz -> ${P}.tar.gz"
Yeah, don't do it. It's nicer if it matches upstream names as long as it's not generic for e.g. archival purposes and so on.

2024-09-09 10:21 UTC, arkamar requested changes
emerge gives me this warning:
```
 * QA Notice: The ebuild is installing to one or more unexpected directories:
 *
 *   /usr/local
 *
 * Please fix the ebuild to use correct FHS/Gentoo policy paths.
strip: x86_64-pc-linux-gnu-strip --strip-unneeded -N __gentoo_check_ldflags__ -R .comment -R .GCC.command.line -R .note.gnu.gold-version
   /usr/local/bin/dav
```
Additionally, I noticed that the man page is installed with exec bit set. It is because upstream uses default install mask, see https://github.com/atsb/dav-text/blob/dav-text-0.9.0/Makefile#L21. Maybe it would be nice to change that as well.

2024-09-09 10:21 UTC, arkamar commented on app-editors/dav/Manifest
> +DIST dav-0.9.0.tar.gz 23882 BLAKE2B 6845b40bbb74d57438625c2736758c52fbe4cff3e020fd451dee540f06fb893d71e11469f828845c193e9fbbd8a8e0b31dcb9a6fa29383053b61dd9a9d7b0ce4 SHA512 8bb9d111c25e7e41c7d75ee559a
You have to regenerate manifest, it does not fit the archive name after last push.

2024-09-09 12:22 UTC, arkamar commented on app-editors/dav/files/dav-0.9.0-manpage-no-exec.patch
> +From b8750775a1f38eebe5d49ca1dfff9d6527289d00 Mon Sep 17 00:00:00 2001
The patch is no longer needed, since you decided to do it according to my suggestion.

2024-09-09 12:49 UTC, arkamar approved these changes

2024-09-09 12:51 UTC, closed without merging