dev-libs/cgreen: add 1.6.3 with many improvements
gentoo/gentoo pull request #38502
Opened 2024-09-07 17:17 UTC by fkobi

Please see the commit message for more

- TODO file a bug upstream about ODR violation when compiling with LTO

Also documentation could be built in either HTML or PDF.
Then, should the flag be named `doc`, `html` or `html-doc`?

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

2024-09-07 21:22 UTC, thesamesam requested changes
_Please_ stop rushing to make so many PRs. Please make one at a time and learn from the feedback on them once they're reviewed.

2024-09-07 21:22 UTC, thesamesam commented on dev-libs/cgreen/cgreen-1.6.3.ebuild
> +# NOTE(fkobi): Makefile is a wrapper for cmake, ignore it
I don't see a need to leave this in. You can put a line in src_configure if you want.

2024-09-07 21:22 UTC, thesamesam commented on dev-libs/cgreen/files/cgreen-1.6.3_no-fortify-source.patch
> +Subject: [PATCH] no-fortify-source
This needs an explanation and a bug link.

2024-09-07 21:22 UTC, thesamesam commented on dev-libs/cgreen/metadata.xml
> +		<flag name="libxml2">Use <pkg>dev-libs/libxml2</pkg> for output formatting in reports</flag>
This is normally USE=xml.

2024-09-08 15:00 UTC, thesamesam commented on dev-libs/cgreen/metadata.xml
> +		<flag name="libxml2">Use <pkg>dev-libs/libxml2</pkg> for output formatting in reports</flag>
What is the simpler alternative here? You didn't explain that in the USE flag description nor in the commit message.

2024-09-08 15:01 UTC, thesamesam commented on dev-libs/cgreen/cgreen-1.6.3.ebuild
> +# NOTE(fkobi): Makefile is a wrapper for cmake, ignore it
I'm saying the comment shouldn't be in "global scope". We also don't generally do "TYPE(person):" comments.

Just put it in src_configure if no src_prepare exists.

2024-09-08 15:02 UTC, thesamesam commented on dev-libs/cgreen/cgreen-1.6.3.ebuild
> +	filter-lto # LTO violates ODR
This comment isn't accurate. The ODR violation is there either way, it just shows up with LTO, and it makes LTO unsafe to use. The ODR violation is still bad.

2024-09-08 16:01 UTC, thesamesam commented on dev-libs/cgreen/metadata.xml
> +		<flag name="libxml2">Use <pkg>dev-libs/libxml2</pkg> for output formatting in reports</flag>
Please explain this in the commit message and USE flag description.

2024-09-08 16:01 UTC, thesamesam commented on dev-libs/cgreen/cgreen-1.6.3.ebuild
> +	filter-lto # LTO violates ODR
Looks better.

2024-09-08 23:20 UTC, eli-schwartz commented on dev-libs/cgreen/cgreen-1.6.3.ebuild
> +	filter-lto # fails to compile with LTO because of ODR violation
I would really love to have an upstream bug report filed for this.

2025-05-21 10:14 UTC, closed without merging

2025-05-21 10:15 UTC, thesamesam commented on dev-libs/cgreen/cgreen-1.6.3.ebuild
> +KEYWORDS="amd64 ~x86"
Don't commit as stable!

2025-05-21 10:15 UTC, thesamesam commented
Thanks.

2025-05-24 01:52 UTC, thesamesam commented
Yeah, I could still reproduce it:
```
FAILED: [code=1] tests/libcgreen_cpp_tests.so
: && /usr/lib/ccache/bin/x86_64-pc-linux-gnu-g++ -fPIC -O3 -march=native -mtls-dialect=gnu2 -flto=jobserver -fno-semantic-interposition -g1 -pipe -fcf-protection=none -fdiagnostics-color
=always -fdiagnostics-urls=never -frecord-gcc-switches -fdiagnostics-set-output=text:experimental-nesting=yes -Wa,-O2 -Wa,-mtune=znver2 -Warray-bounds --param=ggc-min-expand=120  -Wstric
t-aliasing -Wfree-nonheap-object -Wuninitialized -Wmaybe-uninitialized -Wreturn-type -Werror=lto-type-mismatch -Werror=strict-aliasing -Werror=odr -Warray-bounds -Wstringop-overread -Wst
ringop-overflow -Wstringop-truncation -Wformat-overflow -Wformat-truncation  -ggdb3 -Wformat -Werror=format-security -std=c++98 -Weffc++  -O3 -march=native -mtls-dialect=gnu2 -flto=jobse
rver -fno-semantic-interposition -g1 -pipe -fcf-protection=none -fdiagnostics-color=always -fdiagnostics-urls=never -frecord-gcc-switches -fdiagnostics-set-output=text:experimental-nesti
ng=yes -Wa,-O2 -Wa,-mtune=znver2 -Warray-bounds --param=ggc-min-expand=120  -Werror=lto-type-mismatch -Werror=strict-aliasing -Werror=odr -Warray-bounds -Wstringop-overread -Wstringop-ov
erflow -Wstringop-truncation -Wformat-overflow -Wformat-truncation -Wl,-O1 -Wl,--as-needed -Wl,-z,pack-relative-relocs -flto=jobserver -Wl,--defsym=__gentoo_check_ldflags__=0  -ggdb3 -Wl
,--dependency-file=tests/CMakeFiles/cgreen_cpp_tests.dir/link.d -shared -Wl,-soname,libcgreen_cpp_tests.so -o tests/libcgreen_cpp_tests.so tests/CMakeFiles/cgreen_cpp_tests.dir/assertion
_tests.cpp.o tests/CMakeFiles/cgreen_cpp_tests.dir/breadcrumb_tests.cpp.o tests/CMakeFiles/cgreen_cpp_tests.dir/cdash_reporter_tests.cpp.o tests/CMakeFiles/cgreen_cpp_tests.dir/cgreen_va
lue_tests.cpp.o tests/CMakeFiles/cgreen_cpp_tests.dir/constraint_tests.cpp.o tests/CMakeFiles/cgreen_cpp_tests.dir/cute_reporter_tests.cpp.o tests/CMakeFiles/cgreen_cpp_tests.dir/double_
tests.cpp.o tests/CMakeFiles/cgreen_cpp_tests.dir/environment_variables_tests.cpp.o tests/CMakeFiles/cgreen_cpp_tests.dir/message_formatting_tests.cpp.o tests/CMakeFiles/cgreen_cpp_tests
.dir/messaging_tests.cpp.o tests/CMakeFiles/cgreen_cpp_tests.dir/mocks_tests.cpp.o tests/CMakeFiles/cgreen_cpp_tests.dir/mocks_struct_tests.cpp.o tests/CMakeFiles/cgreen_cpp_tests.dir/pa
rameters_tests.cpp.o tests/CMakeFiles/cgreen_cpp_tests.dir/reflective_runner_no_teardown_tests.cpp.o tests/CMakeFiles/cgreen_cpp_tests.dir/reflective_tests.cpp.o tests/CMakeFiles/cgreen_
cpp_tests.dir/text_reporter_tests.cpp.o tests/CMakeFiles/cgreen_cpp_tests.dir/unit_tests.cpp.o tests/CMakeFiles/cgreen_cpp_tests.dir/vector_tests.cpp.o tests/CMakeFiles/cgreen_cpp_tests.
dir/xml_reporter_tests.cpp.o tests/CMakeFiles/cgreen_cpp_tests.dir/cpp_assertion_tests.cpp.o  -Wl,-rpath,/var/tmp/portage/dev-libs/cgreen-1.6.4/work/cgreen-1.6.4_build/src  src/libcgreen
.so.1.6.4  -lstdc++  -lm  -lgcc_s  -lgcc  -lc  -lgcc_s  -lgcc  -lc && :
/var/tmp/portage/dev-libs/cgreen-1.6.4/work/cgreen-1.6.4/tests/mocks_tests.c:469:16: error: type ‘struct Struct’ violates the C++ One Definition Rule [-Werror=odr]
  469 | typedef struct Struct {
      |                ^
/var/tmp/portage/dev-libs/cgreen-1.6.4/work/cgreen-1.6.4/tests/mocks_struct_tests.c:28:3: note: a different type is defined in another translation unit
   28 | } Struct;
      |   ^
/var/tmp/portage/dev-libs/cgreen-1.6.4/work/cgreen-1.6.4/tests/mocks_tests.c:470:9: note: the first difference of corresponding definitions is field ‘height’
  470 |     int height;
      |         ^
/var/tmp/portage/dev-libs/cgreen-1.6.4/work/cgreen-1.6.4/tests/mocks_struct_tests.c:26:9: note: a field with different name is defined in another translation unit
   26 |     int i;
      |         ^
lto1: some warnings being treated as errors
lto-wrapper: fatal error: /usr/bin/x86_64-pc-linux-gnu-g++ returned 1 exit status
compilation terminated.
```

2025-07-26 20:23 UTC, fkobi commented
I cannot, even with -O3 and -fPIC ([build.log](https://github.com/user-attachments/files/21448591/build.log)).
Maybe you could reproduce it due to some compilation files being cached?