gnome-base/gnome-shell, x11-wm/mutter, gnome-extra/gnome-shell-extensions: Bump to 47.0
gentoo/gentoo pull request #38650
Opened 2024-09-17 22:09 UTC by flint2

- **x11-wm/mutter: Bump to 47.0**
- **gnome-base/gnome-shell: Bump to 47.0**
- **gnome-extra/gnome-shell-extensions: Bump to 47.0**

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

2024-10-07 23:30 UTC, jhatler requested changes

2024-10-10 14:11 UTC, WavyEbuilder commented on x11-wm/mutter/mutter-47.0.ebuild
> +#	)"
Adding to this, upstream also has an xwayland build option to build mutter without support for xwayland:
https://gitlab.gnome.org/GNOME/mutter/-/blob/main/meson_options.txt?ref_type=heads#L42

We should probably add an xwayland USE flag for this.

2024-10-18 11:28 UTC, mechakotik commented
Currently trying out your gnome47 repository. Things I've noticed so far:

- If mutter is built without X11 support, even Wayland session will crash with "something has gone wrong" error a few minutes after logging in.
- Unable to build glib with `abi_x86_32`: when I enable this flag and run update, Portage says that `-abi_x86_32` is required.
- Search is really slow, especially font search, which may cause apps to freeze for a few seconds. Idk if it's ebuild or GNOME related.
- There aren't any animated settings previews in GNOME Control Center, boxes where they should be are just empty.

2024-12-16 14:43 UTC, lkraav commented
I just tried building `mutter-47.2`, but failed at not finding `libdisplay-info`. I'm currently cherry-picking packages out of `gnome47` branch into my own local overlay, trying to emerge and seeing what deps are missing, then adding those.

It seems `libdisplay-info` is an undeclared dependency then?

```
>>> Configuring source in /run/zram/portage/x11-wm/mutter-47.2/work/mutter-47.2 ...                                              
meson setup -Db_lto=false --libdir lib64 --localstatedir /var/lib --prefix /usr --sysconfdir /etc --wrap-mode nodownload --build.pkg-config-path /run/zram/portage/x11-wm/mutter-47.2/temp/python3.12/pkgconfig:/usr/share/pkgconfig --pkg-config-path /run/zram/po
rtage/x11-wm/mutter-47.2/temp/python3.12/pkgconfig:/usr/share/pkgconfig --native-file /run/zram/portage/x11-wm/mutter-47.2/temp/meson.x86_64-pc-linux-gnu.amd64.ini -Db_pch=false -Dwerror=false -Dbuildtype=plain -Dopengl=true -Dgles2=true -Degl=true -Dglx=true
 -Dwayland=true -Dxwayland=true -Dsystemd=true -Dnative_backend=true -Dremote_desktop=true -Dlibgnome_desktop=true -Dudev=true -Dudev_dir=/usr/lib/udev -Dlibwacom=false -Dsound_player=true -Dstartup_notification=true -Dlibdisplay_info=enabled -Dsm=true -Dintr
ospection=true -Ddocs=false -Dcogl_tests=false -Dclutter_tests=false -Dmutter_tests=false -Dtests=disabled -Dkvm_tests=false -Dtty_tests=false -Dprofiler=true -Dinstalled_tests=false -Dx11=false -Degl_device=false -Dwayland_eglstream=false /run/zram/portage/x
11-wm/mutter-47.2/work/mutter-47.2 /run/zram/portage/x11-wm/mutter-47.2/work/mutter-47.2-build
The Meson build system                                          
Version: 1.5.2                                                  
Source dir: /run/zram/portage/x11-wm/mutter-47.2/work/mutter-47.2                                                                
Build dir: /run/zram/portage/x11-wm/mutter-47.2/work/mutter-47.2-build                                                           
Build type: native build                                        
Project name: mutter                                            
Project version: 47.2                                           
C compiler for the host machine: x86_64-pc-linux-gnu-gcc (gcc 14.2.1 "x86_64-pc-linux-gnu-gcc (Gentoo 14.2.1_p20241116 p3) 14.2.1 20241116")                                                                                                                       
C linker for the host machine: x86_64-pc-linux-gnu-gcc ld.bfd 2.42                                                               
Host machine cpu family: x86_64                                 
Host machine cpu: x86_64                                        
Compiler for C supports link arguments -Wl,--disable-new-dtags: YES                                                              
Library m found: YES                                            
Found pkg-config: YES (/usr/bin/x86_64-pc-linux-gnu-pkg-config) 2.3.0                                                            
Run-time dependency graphene-gobject-1.0 found: YES 1.10.8      
Run-time dependency gdk-pixbuf-2.0 found: YES 2.42.10           
Run-time dependency pango found: YES 1.52.1                     
Run-time dependency cairo found: YES 1.18.2                     
Run-time dependency pangocairo found: YES 1.52.1                
Run-time dependency pixman-1 found: YES 0.43.4                  
Run-time dependency fribidi found: YES 1.0.13                   
Run-time dependency gsettings-desktop-schemas found: YES 47.1                                                                    
Run-time dependency glib-2.0 found: YES 2.82.4                  
Run-time dependency gio-unix-2.0 found: YES 2.82.4              
Dependency gio-unix-2.0 found: YES 2.82.4 (cached)              
Run-time dependency gobject-2.0 found: YES 2.82.4               
Dependency gobject-2.0 found: YES 2.82.4 (cached)               
Run-time dependency gmodule-no-export-2.0 found: YES 2.82.4     
Run-time dependency gnome-settings-daemon found: YES 47.2       
Run-time dependency xkbcommon found: YES 1.7.0                  
Run-time dependency atk found: YES 2.52.0                       
Run-time dependency colord found: YES 1.4.7                     
Run-time dependency lcms2 found: YES 2.16                       
Run-time dependency harfbuzz found: YES 9.0.0                   
Run-time dependency libeis-1.0 found: YES 1.3.0                 
Run-time dependency libei-1.0 found: YES 1.3.0                  
Found CMake: /usr/bin/cmake (3.30.5)                            
Run-time dependency gvdb found: NO (tried pkgconfig and cmake)                                                                   
Looking for a fallback subproject for the dependency gvdb       

Executing subproject gvdb                                       

gvdb| Project name: gvdb                                        
gvdb| Project version: 0.0                                      
gvdb| C compiler for the host machine: x86_64-pc-linux-gnu-gcc (gcc 14.2.1 "x86_64-pc-linux-gnu-gcc (Gentoo 14.2.1_p20241116 p3) 14.2.1 20241116")                                                                                                                 
gvdb| C linker for the host machine: x86_64-pc-linux-gnu-gcc ld.bfd 2.42                                                         
gvdb| Run-time dependency gio-2.0 found: YES 2.82.4             
gvdb| Build targets in project: 1                               
gvdb| Subproject gvdb finished.                                 

Dependency gvdb found: YES 0.0 (overridden)                     
Run-time dependency gtk4 found: YES 4.16.7                      
Run-time dependency x11 found: YES 1.8.10                       
Run-time dependency xcomposite found: YES 0.4.6                 
Run-time dependency xcursor found: YES 1.2.3                    
Run-time dependency xdamage found: YES 1.1.6                    
Run-time dependency xext found: YES 1.3.6                       
Run-time dependency xfixes found: YES 6.0.1                     
Run-time dependency xi found: YES 1.8.2                         
Run-time dependency xkbfile found: YES 1.1.3                    
Run-time dependency xkeyboard-config found: YES 2.43            
Run-time dependency x11-xcb found: YES 1.8.10                   
Run-time dependency xrandr found: YES 1.5.4                     
Run-time dependency xcb-res found: YES 1.17.0                   
Run-time dependency xinerama found: YES 1.1.5                   
Run-time dependency xau found: YES 1.0.11                       
Run-time dependency libdisplay-info found: NO (tried pkgconfig and cmake)                                                        

meson.build:174:22: ERROR: Dependency "libdisplay-info" not found, tried pkgconfig and cmake                                     

A full log can be found at /run/zram/portage/x11-wm/mutter-47.2/work/mutter-47.2-build/meson-logs/meson-log.txt                  
 * ERROR: x11-wm/mutter-47.2::lkraav failed (configure phase):                                                                   
 *   configure failed                                           
 *                                                              
 * Call stack:                                                  
 *     ebuild.sh, line  136:  Called src_configure              
 *   environment, line 4236:  Called meson_src_configure        
 *   environment, line 3347:  Called die                        
 * The specific snippet of code:                                
 *       [[ ${rv} -eq 0 ]] || die -n "configure failed";        
 *                                                              
 * If you need support, post the output of `emerge --info '=x11-wm/mutter-47.2::lkraav'`,                                        
 * the complete build log and the output of `emerge -pqv '=x11-wm/mutter-47.2::lkraav'`.                                         
 * The complete build log is located at '/run/zram/p [...]

2024-12-19 02:41 UTC, flint2 commented
> I just tried building `mutter-47.2`, but failed at not finding `libdisplay-info`. I'm currently cherry-picking packages out of `gnome47` branch into my own local overlay, trying to emerge and seeing what deps are missing, then adding those.
> 
> It seems `libdisplay-info` is an undeclared dependency then?
> 
> ```
> >>> Configuring source in /run/zram/portage/x11-wm/mutter-47.2/work/mutter-47.2 ...                                              
> meson setup -Db_lto=false --libdir lib64 --localstatedir /var/lib --prefix /usr --sysconfdir /etc --wrap-mode nodownload --build.pkg-config-path /run/zram/portage/x11-wm/mutter-47.2/temp/python3.12/pkgconfig:/usr/share/pkgconfig --pkg-config-path /run/zram/po
> rtage/x11-wm/mutter-47.2/temp/python3.12/pkgconfig:/usr/share/pkgconfig --native-file /run/zram/portage/x11-wm/mutter-47.2/temp/meson.x86_64-pc-linux-gnu.amd64.ini -Db_pch=false -Dwerror=false -Dbuildtype=plain -Dopengl=true -Dgles2=true -Degl=true -Dglx=true
>  -Dwayland=true -Dxwayland=true -Dsystemd=true -Dnative_backend=true -Dremote_desktop=true -Dlibgnome_desktop=true -Dudev=true -Dudev_dir=/usr/lib/udev -Dlibwacom=false -Dsound_player=true -Dstartup_notification=true -Dlibdisplay_info=enabled -Dsm=true -Dintr
> ospection=true -Ddocs=false -Dcogl_tests=false -Dclutter_tests=false -Dmutter_tests=false -Dtests=disabled -Dkvm_tests=false -Dtty_tests=false -Dprofiler=true -Dinstalled_tests=false -Dx11=false -Degl_device=false -Dwayland_eglstream=false /run/zram/portage/x
> 11-wm/mutter-47.2/work/mutter-47.2 /run/zram/portage/x11-wm/mutter-47.2/work/mutter-47.2-build
> The Meson build system                                          
> Version: 1.5.2                                                  
> Source dir: /run/zram/portage/x11-wm/mutter-47.2/work/mutter-47.2                                                                
> Build dir: /run/zram/portage/x11-wm/mutter-47.2/work/mutter-47.2-build                                                           
> Build type: native build                                        
> Project name: mutter                                            
> Project version: 47.2                                           
> C compiler for the host machine: x86_64-pc-linux-gnu-gcc (gcc 14.2.1 "x86_64-pc-linux-gnu-gcc (Gentoo 14.2.1_p20241116 p3) 14.2.1 20241116")                                                                                                                       
> C linker for the host machine: x86_64-pc-linux-gnu-gcc ld.bfd 2.42                                                               
> Host machine cpu family: x86_64                                 
> Host machine cpu: x86_64                                        
> Compiler for C supports link arguments -Wl,--disable-new-dtags: YES                                                              
> Library m found: YES                                            
> Found pkg-config: YES (/usr/bin/x86_64-pc-linux-gnu-pkg-config) 2.3.0                                                            
> Run-time dependency graphene-gobject-1.0 found: YES 1.10.8      
> Run-time dependency gdk-pixbuf-2.0 found: YES 2.42.10           
> Run-time dependency pango found: YES 1.52.1                     
> Run-time dependency cairo found: YES 1.18.2                     
> Run-time dependency pangocairo found: YES 1.52.1                
> Run-time dependency pixman-1 found: YES 0.43.4                  
> Run-time dependency fribidi found: YES 1.0.13                   
> Run-time dependency gsettings-desktop-schemas found: YES 47.1                                                                    
> Run-time dependency glib-2.0 found: YES 2.82.4                  
> Run-time dependency gio-unix-2.0 found: YES 2.82.4              
> Dependency gio-unix-2.0 found: YES 2.82.4 (cached)              
> Run-time dependency gobject-2.0 found: YES 2.82.4               
> Dependency gobject-2.0 found: YES 2.82.4 (cached)               
> Run-time dependency gmodule-no-export-2.0 found: YES 2.82.4     
> Run-time dependency gnome-settings-daemon found: YES 47.2       
> Run-time dependency xkbcommon found: YES 1.7.0                  
> Run-time dependency atk found: YES 2.52.0                       
> Run-time dependency colord found: YES 1.4.7                     
> Run-time dependency lcms2 found: YES 2.16                       
> Run-time dependency harfbuzz found: YES 9.0.0                   
> Run-time dependency libeis-1.0 found: YES 1.3.0                 
> Run-time dependency libei-1.0 found: YES 1.3.0                  
> Found CMake: /usr/bin/cmake (3.30.5)                            
> Run-time dependency gvdb found: NO (tried pkgconfig and cmake)                                                                   
> Looking for a fallback subproject for the dependency gvdb       
> 
> Executing subproject gvdb                                       
> 
> gvdb| Project name: gvdb                                        
> gvdb| Project version: 0.0                                      
> gvdb| C compiler for the host machine: x86_64-pc-linux-gnu-gcc (gcc 14.2.1 "x86_64-pc-linux-gnu-gcc (Gentoo 14.2.1_p20241116 p3) 14.2.1 20241116")                                                                                                                 
> gvdb| C linker for the host machine: x86_64-pc-linux-gnu-gcc ld.bfd 2.42                                                         
> gvdb| Run-time dependency gio-2.0 found: YES 2.82.4             
> gvdb| Build targets in project: 1                               
> gvdb| Subproject gvdb finished.                                 
> 
> Dependency gvdb found: YES 0.0 (overridden)                     
> Run-time dependency gtk4 found: YES 4.16.7                      
> Run-time dependency x11 found: YES 1.8.10                       
> Run-time dependency xcomposite found: YES 0.4.6                 
> Run-time dependency xcursor found: YES 1.2.3                    
> Run-time dependency xdamage found: YES 1.1.6                    
> Run-time dependency xext found: YES 1.3.6                       
> Run-time dependency xfixes found: YES 6.0.1                     
> Run-time dependency xi found: YES 1.8.2                         
> Run-time dependency xkbfile found: YES 1.1.3                    
> Run-time dependency xkeyboard-config found: YES 2.43            
> Run-time dependency x11-xcb found: YES 1.8.10                   
> Run-time dependency xrandr found: YES 1.5.4                     
> Run-time dependency xcb-res found: YES 1.17.0                   
> Run-time dependency xinerama found: YES 1.1.5                   
> Run-time dependency xau found: YES 1.0.11                       
> Run-time dependency libdisplay-info found: NO (tried pkgconfig and cmake)                                                        
> 
> meson.build:174:22: ERROR: Dependency "libdisplay-info" not found, tried pkgconfig and cmake                                     
> 
> A full log can be found at /run/zram/portage/x11-wm/mutter-47.2/work/mutter-47.2-build/meson-logs/meson-log.txt                  
>  * ERROR: x11-wm/mutter-47.2::lkraav failed (configure phase):                                                                   
>  *   configure failed                                           
>  *                                                              
>  * Call stack:                                                  
>  *     ebuild.sh, line  136:  Called src_configure              
>  *   environment, line 4236:  Called meson_src_configure        
>  *   environment, line 3347:  Called die                        
>  * The specific snippet of code:                                
>  *       [[ ${rv} -eq 0 ]] || die -n "configure failed";        
>  *                                                              
>  * If you need support, post the output of `emerge --info '=x11-wm/mutter-47.2::lkraav'`,                                      [...]

2025-01-06 12:38 UTC, reagentoo commented
gtk-4.16.12 / libadwaita-1.6.2 has been updated. Is it possible to merge this PR?

2025-01-26 17:33 UTC, closed without merging

2025-04-22 20:58 UTC, eli-schwartz commented on x11-wm/mutter/mutter-47.4.ebuild
> +	libdisplay? ( media-libs/libdisplay-info )
You broke this!!!

Before this PR, libdisplay-info was an unconditional dependency that used a `media-libs/libdisplay-info:=` dependency. It was added in 7d2273a9e780199b7a28bd06d17234130bc469e5, you rebased against this commit but didn't incorporate the changes. I could maybe understand keeping the USE flag but dropping this from `:=` to an unqualified dependency?