app-misc/localsearch, app-misc/tinysparql: New package 3.8.0, app-cdr/brasero, gnome-base/gnome-extra-apps, gnome-base/gnome-core-libs, media-gfx/gnome-photos, media-sound/gnome-music, media-plugins/grilo-plugins, gnome-extra/gnome-boxes, profiles/base: Rename tracker to localsearch
gentoo/gentoo pull request #38654
Opened 2024-09-18 01:19 UTC by flint2

- **app-misc/tinysparql: New package 3.8.0**
- **app-misc/localsearch: New package 3.8.0**
- **app-cdr/brasero: Rename tracker to localsearch**
- **gnome-base/gnome-extra-apps: Rename tracker to localsearch**
- **gnome-base/gnome-core-libs: Rename tracker to localsearch**
- **media-gfx/gnome-photos: Rename tracker to localsearch**
- **media-sound/gnome-music: Rename tracker to localsearch**
- **media-plugins/grilo-plugins: Rename tracker to localsearch**
- **gnome-extra/gnome-boxes: Rename tracker to localsearch**
- **profiles/base: Rename tracker to localsearch**

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

2024-09-18 21:43 UTC, a17r requested changes
app-misc/localsearch is really just app-misc/tracker renamed? If so, this is not the right way to do it and probably goes beyond what make sense to push through proxy-maint.

app-misc/tracker is maintained by **gnome proj**, file a bug about the upstream repository renaming/3.8.0 version bump first, to start the process. But even then, 3.8 tag was only created 2 days ago, so cut them some slack.

Again, hanging out in #gentoo-dev-help or #gentoo-proxy-maint and simply asking around in advance would go a long way to avoid wasting your time on such an attempt.

2024-09-18 21:48 UTC, a17r commented on gnome-base/gnome-extra-apps/metadata.xml
> -	<flag name="tracker">Install the <pkg>app-misc/tracker</pkg> indexer and the GNOME packages that require it</flag>
this is purely educational and no instruction to fix this PR, but: 45.2 is still around, so you can't remove this.

2024-09-18 21:49 UTC, a17r commented on media-plugins/grilo-plugins/metadata.xml
> -    <flag name="tracker">Build support for content discovery using the <pkg>app-misc/tracker</pkg> indexer</flag>
this is purely educational and no instruction to fix this PR, but: 0.3.16 is still around, so you can't remove this.

2024-09-18 21:49 UTC, a17r commented on profiles/base/package.use.mask
> +gnome-base/gnome-extra-apps localsearch
this is purely educational and no instruction to fix this PR, but: what happens to still existing 45.2 when you do that?

2025-01-16 11:02 UTC, pacho2 commented
Hello,

I leave here this link explaining the context:
https://blogs.gnome.org/carlosg/2024/07/14/goodbye-tracker-hello-tinysparql-and-localsearch/
(tracker-miners -> localsearch; tracker -> tinysparql)

I am a bit unsure about how to proceed:
- Global renaming of the USE flag from "tracker" to "localsearch" -> IMHO, that could be done even before localsearch lands the tree, as I also find the new name better explaining the function that is enabled/disabled (but I must confess I never liked much the "tracker" name for the USE as I felt that people not maintaining the tracker package wouldn't know its meaning until looking into the description).
But if you prefer to temporarily have both USE flags (to avoid some immediate pkg rebuilds), I am also ok with that. 
- Even if 3.8.x version is still fully compatible with the old tracker* naming style, that is going to change in the future. I wouldn't do then a pkgmove, and I would add them as new packages.
- Maybe one option would be to create dummy tracker-3.8.x.ebuild and tracker-miner-3.8.x.ebuild that would simply install the right localsearch/tinyspqrql versions. That would be interesting as we would migrate the RDEPENDs to the new names when the applications are really migrating to the new style (not relying on compatibility links that are going to be dropped in version 4).

2025-02-17 13:59 UTC, pacho2 commented
> Hello,
> 
> I leave here this link explaining the context: https://blogs.gnome.org/carlosg/2024/07/14/goodbye-tracker-hello-tinysparql-and-localsearch/ (tracker-miners -> localsearch; tracker -> tinysparql)
> 
> I am a bit unsure about how to proceed:
> 
> * Global renaming of the USE flag from "tracker" to "localsearch" -> IMHO, that could be done even before localsearch lands the tree, as I also find the new name better explaining the function that is enabled/disabled (but I must confess I never liked much the "tracker" name for the USE as I felt that people not maintaining the tracker package wouldn't know its meaning until looking into the description).
>   But if you prefer to temporarily have both USE flags (to avoid some immediate pkg rebuilds), I am also ok with that.
> * Even if 3.8.x version is still fully compatible with the old tracker* naming style, that is going to change in the future. I wouldn't do then a pkgmove, and I would add them as new packages.
> * Maybe one option would be to create dummy tracker-3.8.x.ebuild and tracker-miner-3.8.x.ebuild that would simply install the right localsearch/tinyspqrql versions. That would be interesting as we would migrate the RDEPENDs to the new names when the applications are really migrating to the new style (not relying on compatibility links that are going to be dropped in version 4).

Hello,

Thinking a bit more into this, maybe one option could be to:
- Add "localsearch" as a global USE flag with the same description and default enabling as "tracker" in the relevant profiles.
- Add localsearch and tinysparql new packages.
- Add dummy "tracker-3.8.x" and "tracker-miners-3.8.x" ebuilds to avoid some ugly blockers in the (hopefully short) transition period. Doing this, old reverse deps would pull the non-blocking tracker-*-3.8 ebuilds, while new packages will pull localsearch/tinysparql.

2025-05-11 22:34 UTC, thesamesam commented
https://github.com/gentoo/gentoo/pull/41095#issuecomment-2870251377

2025-05-11 22:34 UTC, closed without merging