dev-libs/re2: build using cmake
gentoo/gentoo pull request #38866
Opened 2024-10-04 00:18 UTC by Peter-Levine

Supports building re2 with CMake.  A patch is included to support building and linking the benchmarking binary statically, as the Makefile version does, instead of having to install a `libtesting.so` library just to resolve symbols for an auxiliary binary.

Closes: https://bugs.gentoo.org/940734

---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

2024-10-04 15:29 UTC, mattst88 commented
cc: @Jamim

2024-10-05 10:41 UTC, Jamim commented
_Hello @Peter-Levine,_

Thank you for your work! 🙇🏼
I've tried to compile `re2` using your changes. It compiles but most of the tests fail.

<details><summary>Test phase: <b>dev-libs/re2-0.2024.07.02-r2</b></summary>
<p>

``` * abi_x86_64.amd64: running multilib-minimal_abi_src_test
 * Source directory (CMAKE_USE_DIR): "/var/tmp/portage/dev-libs/re2-0.2024.07.02-r2/work/re2-2024-07-02"
 * Build directory  (BUILD_DIR):     "/var/tmp/portage/dev-libs/re2-0.2024.07.02-r2/work/re2-2024-07-02_build-abi_x86_64.amd64"
ctest -j 7 --test-load 999
Test project /var/tmp/portage/dev-libs/re2-0.2024.07.02-r2/work/re2-2024-07-02_build-abi_x86_64.amd64
      Start  1: charclass_test
      Start  2: compile_test
      Start  3: filtered_re2_test
      Start  4: mimics_pcre_test
      Start  5: parse_test
      Start  6: possible_match_test
      Start  7: re2_test
 1/20 Test  #1: charclass_test ...................***Failed    0.02 sec
 2/20 Test  #2: compile_test .....................***Failed    0.01 sec
 3/20 Test  #3: filtered_re2_test ................   Passed    0.01 sec
 4/20 Test  #4: mimics_pcre_test .................***Failed    0.01 sec
      Start  8: re2_arg_test
      Start  9: regexp_test
      Start 10: required_prefix_test
      Start 11: search_test
 5/20 Test  #5: parse_test .......................***Failed    0.02 sec
 6/20 Test  #6: possible_match_test ..............***Failed    0.02 sec
 7/20 Test  #7: re2_test .........................***Failed    0.01 sec
 8/20 Test  #9: regexp_test ......................***Failed    0.01 sec
      Start 12: set_test
      Start 13: simplify_test
      Start 14: string_generator_test
      Start 15: dfa_test
 9/20 Test  #8: re2_arg_test .....................   Passed    0.02 sec
10/20 Test #10: required_prefix_test .............***Failed    0.02 sec
11/20 Test #11: search_test ......................***Failed    0.01 sec
      Start 16: exhaustive1_test
      Start 17: exhaustive2_test
      Start 18: exhaustive3_test
12/20 Test #12: set_test .........................   Passed    0.02 sec
13/20 Test #13: simplify_test ....................***Failed    0.01 sec
14/20 Test #14: string_generator_test ............***Failed    0.01 sec
15/20 Test #15: dfa_test .........................***Failed    0.01 sec
      Start 19: exhaustive_test
      Start 20: random_test
16/20 Test #16: exhaustive1_test .................***Failed    0.01 sec
17/20 Test #17: exhaustive2_test .................***Failed    0.01 sec
18/20 Test #18: exhaustive3_test .................***Failed    0.01 sec
19/20 Test #19: exhaustive_test ..................***Failed    0.01 sec
20/20 Test #20: random_test ......................***Failed    0.01 sec

15% tests passed, 17 tests failed out of 20

Total Test time (real) =   0.06 sec

The following tests FAILED:
          1 - charclass_test (Failed)
          2 - compile_test (Failed)
          4 - mimics_pcre_test (Failed)
          5 - parse_test (Failed)
          6 - possible_match_test (Failed)
          7 - re2_test (Failed)
          9 - regexp_test (Failed)
         10 - required_prefix_test (Failed)
         11 - search_test (Failed)
         13 - simplify_test (Failed)
         14 - string_generator_test (Failed)
         15 - dfa_test (Failed)
         16 - exhaustive1_test (Failed)
         17 - exhaustive2_test (Failed)
         18 - exhaustive3_test (Failed)
         19 - exhaustive_test (Failed)
         20 - random_test (Failed)
```

</p>
</details>

Meanwhile, for `dev-libs/re2-0.2024.07.02-r1`, all the tests pass.
Do tests pass on your system?

2024-10-06 01:10 UTC, Peter-Levine commented
Wierd.  All tests pass for me on both ABIs.  Could you post the file `${WORKDIR}/re2-2024-07-02_build-abi_x86_64.amd64/Testing/Temporary/LastTest.log` and the output of `emerge --info`

2024-10-06 22:49 UTC, eli-schwartz requested changes
This fails to build for me -- in fact it fails during configure because USE="-benchmark" but the cmake files require building the benchmarks. Seems rather awkward.

The Makefile seems to handle this ok.

2024-10-06 22:54 UTC, eli-schwartz commented
```diff
@@ -20,57 +20,38 @@ LICENSE="BSD"
 SONAME="11"
 SLOT="0/${SONAME}"
 KEYWORDS="~alpha ~amd64 ~arm ~arm64 ~loong ~ppc64 ~riscv ~sparc ~x86"
-IUSE="benchmark icu test test-full"
-REQUIRED_USE="
-       test-full? ( test )
-"
+IUSE="benchmark icu test"
+
 RESTRICT="!test? ( test )"
```

BTW it appears that cmake does not support skipping the "exhaustive tests", which are described in metadata.xml as such:

```
		<flag name="test-full">Run additional, quite slow tests</flag>
```

That's a real pity as it disincentivizes running the tests at all.

2024-10-07 01:40 UTC, Peter-Levine commented
> That's a real pity as it disincentivizes running the tests at all.

It takes 21.71 seconds for me to run all of them which, in the context of the average test phase, isn't all that long.  But if you want to keep `test-full`, the equivalent behaviour could be implemented  by passing `-E '.*exhaustive.*'` to ctest to filter the exhaustive tests out when `test-full` is unset.

2024-10-07 01:46 UTC, Peter-Levine commented
Actually, something like `-E '.*(exhaustive|dfa|random).*'` would be the equivalent.

2024-10-07 02:03 UTC, eli-schwartz commented
> It takes 21.71 seconds for me to run all of them which, in the context of the average test phase, isn't all that long.

`make shared-bigtest` seems to be doing an awful lot more on my system than on yours, then:

```
>>> Completed testing dev-libs/re2-0.2024.07.02-r1

real	11m27.396s
user	15m52.651s
sys	0m21.669s
```

My assumption was that an "exhaustive" test is testing a ludicrously large number of cases which is why it takes so long. I will confess I haven't attempted to debug the source code of the test case and find out what exactly it is doing. ;)

2024-10-07 02:49 UTC, Jamim commented
> Weird. All tests pass for me on both ABIs. Could you post links to the file `${WORKDIR}/re2-2024-07-02_build-abi_x86_64.amd64/Testing/Temporary/LastTest.log` and the output of `emerge --info`?

Sure, here they are:
  - [emerge re2 --info](https://github.com/user-attachments/files/17272139/emerge-re2-info.txt)
  - [LastTest.log](https://github.com/user-attachments/files/17272140/LastTest.log)

2024-10-07 03:50 UTC, Peter-Levine commented
> This fails to build for me -- in fact it fails during configure because USE="-benchmark" but the cmake files require building the benchmarks. Seems rather awkward.
> 
> The Makefile seems to handle this ok.

So, it seems the CMake build makes benchmark dependent on testing.  This poses a problem in that dev-cpp/benchmark doesn't support sparc.

I'll focus on maybe having the ebuild install re2Config.cmake.in without using cmake.

2024-10-07 03:50 UTC, closed without merging