dev-cpp/sdbus-c++, gui-libs/gtk-layer-shell, gui-apps/waybar update
gentoo/gentoo pull request #39119
Opened 2024-10-26 20:06 UTC by JohnMH

Update dev-cpp/sdbus-c++, dependency of several Hypr* packages.

Update gui-apps/waybar and gui-libs/gtk-layer-shell as dep.

---

Please check all the boxes that apply:

- [ ] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [ ] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [ ] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [ ] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

2024-10-26 21:25 UTC, chewi requested changes
`src_install` doesn't even work for sdbus-c++ because it fails on removing `COPYING`. `src_compile` also fails with `USE=doc`. Did you try this package at all? :confused:

2024-10-26 21:25 UTC, chewi commented on dev-cpp/sdbus-c++/sdbus-c++-2.0.0.ebuild
> +SLOT="0/1"
Also the SLOT needs to change to `0/2`.

2024-10-26 21:31 UTC, chewi commented
> `src_install` doesn't even work for sdbus-c++ because it fails on removing `COPYING`.

Sorry, I do take that part back. That only happens when `USE=test`. That's very weird.

2024-10-26 21:46 UTC, JohnMH commented
I didn't test with USE=doc.

As soon as my systems are done running updates I'll take a look.

2024-10-26 22:11 UTC, chewi commented
I've been working through the issues. It's just the failing tests I haven't figured out yet. I'm heading to bed, but I'd be grateful if you could figure that part out. Sorry again for the misunderstanding. I'm a little grumpy because I don't actually need this package any more. :upside_down_face: Nothing in the repo depends on it.

2024-10-26 22:34 UTC, chewi commented
It seems to be because `DBUS_SESSION_BUS_ADDRESS` isn't making it through to the ebuild environment. I can't work out what's killing it, but `sudo` and such would kill it anyway. We probably need to run the tests via `dbus-run-session` or something.

2024-10-27 18:11 UTC, JonasToth commented
https://github.com/gentoo/gentoo/pull/39025
there is a pr for waybar already

2024-10-27 19:32 UTC, JohnMH commented
@JonasToth Removed 0.11.0. Removed wlroots dep from live and double checked the other deps. Live wlroots will ned gtk-layer-shell 0.9.0.

2024-10-28 17:29 UTC, lanodan approved these changes

2024-10-28 22:55 UTC, chewi commented
I've got the tests passing, but I need sleep now. Will pull this together tomorrow.

2024-10-29 21:47 UTC, closed without merging