app-misc/brewtarget: Bump to 4.0.9, remove old
gentoo/gentoo pull request #39278
Opened 2024-11-11 20:48 UTC by salahcoronya

Many, many changes have come since the last brewtarget version in Portage. A number of patches needed to be applied to the build system, too. 

I cannot get the tests to work (they always timeout, even with a big multiplier, do I've disabled them. 

See https://bugs.gentoo.org/943181 fir the other changes.

---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

2025-02-16 16:56 UTC, a17r requested changes

2025-02-16 16:56 UTC, a17r commented on app-misc/brewtarget/brewtarget-4.0.15.ebuild
> +	sed -i -e "s/if compiler.get_id() == 'gcc'/if false/" meson.build || die
these should both be patches instead. `sed` may fail to apply any changes silently.

2025-02-16 16:56 UTC, a17r commented on app-misc/brewtarget/brewtarget-4.0.15.ebuild
> +}
inherit `xdg.eclass` instead and cleanup these lines. Otherwise they would diverge from ebuild standards (bracketing).

2025-02-16 16:56 UTC, a17r commented on app-misc/brewtarget/brewtarget-4.0.15.ebuild
> +	)
```suggestion
)
```
indendation

2025-02-16 16:56 UTC, a17r commented on app-misc/brewtarget/brewtarget-4.0.15.ebuild
> +inherit meson plocale xdg-utils
Please drop plocales, we do not obsess about small files any longer.

Cleanup the commented out line also.

2025-02-16 16:56 UTC, a17r commented on app-misc/brewtarget/brewtarget-4.0.15.ebuild
> +RESTRICT="test"
RESTRICT may take more arguments, so no need to disable the above line, just both them all in one RESTRICT.

2025-02-16 16:56 UTC, a17r commented on app-misc/brewtarget/brewtarget-4.0.15.ebuild
> +#}
What purpose was `my_test` serving? Seems like cruft left behind, shouldn't be in the final ebuild.

You can drop usage of `virtx` and try with setting `local -x QT_QPA_PLATFORM=offscreen` instead.

2025-02-16 16:56 UTC, a17r commented on app-misc/brewtarget/brewtarget-4.0.15.ebuild
> +	"${FILESDIR}/${PN}-4.0.9-fix-docdir.patch"
upstream is at 4.0.17 now, maybe some of those are fixed?

2025-02-16 16:56 UTC, a17r commented on app-misc/brewtarget/brewtarget-4.0.15.ebuild
> +	dev-libs/boost[stacktrace]
if there is linking against `dev-libs/boost`, then there will be a `:=` slot operator missing.

2025-02-17 02:58 UTC, salahcoronya commented on app-misc/brewtarget/brewtarget-4.0.15.ebuild
> +}
Done

2025-02-17 02:58 UTC, salahcoronya commented on app-misc/brewtarget/brewtarget-4.0.15.ebuild
> +	)
Done

2025-02-17 02:59 UTC, salahcoronya commented on app-misc/brewtarget/brewtarget-4.0.15.ebuild
> +inherit meson plocale xdg-utils
Done

2025-02-17 02:59 UTC, salahcoronya commented on app-misc/brewtarget/brewtarget-4.0.15.ebuild
> +RESTRICT="test"
I couldn't get the tests to work, they always timeout. So I just decided to disable them.

2025-02-17 03:00 UTC, salahcoronya commented on app-misc/brewtarget/brewtarget-4.0.15.ebuild
> +	"${FILESDIR}/${PN}-4.0.9-fix-docdir.patch"
Nope, most of these patches re due to design decisions upstream. They are still needed in 4.0.17.

2025-02-17 03:00 UTC, salahcoronya commented on app-misc/brewtarget/brewtarget-4.0.15.ebuild
> +	dev-libs/boost[stacktrace]
Added

2025-02-17 03:01 UTC, salahcoronya commented on app-misc/brewtarget/brewtarget-4.0.15.ebuild
> +#}
Test removed as they always timeout.

2025-02-17 03:57 UTC, salahcoronya commented on app-misc/brewtarget/brewtarget-4.0.15.ebuild
> +#}
Actually, I take that back. with the "local -x QT_QPA_PLATFORM=offscreen" the tests work. So i will add them back.

2025-02-19 21:16 UTC, a17r approved these changes
Thanks a lot for getting this done, solid work. One thing I noticed during runtime testing was non-spec desktop file naming resulting in the wrong application icon being used. But that is easily fixed in a separate commit of mine.

2025-02-19 21:17 UTC, closed without merging