x11-terms/alacritty: Add libxkbcommon[X?]
gentoo/gentoo pull request #39272
Opened 2024-11-11 16:53 UTC by strategictraveler

Fix Alacritty not starting due to missing lib.

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

2024-11-11 17:10 UTC, kchibisov requested changes
IIRC, generally adding a use flag for a dependency requires a rev bump. However in this case, system without libxkbcommon X on X11 is not functional anyway (you lack basically every function to init xkb keymap from X11 keymap), so users should generally have it enabled one way or another, and given that it was brought just now, this doesn't affect the majority of the users.

2024-11-11 17:10 UTC, kchibisov commented on x11-terms/alacritty/alacritty-0.12.3-r1.ebuild
> +	x11-libs/libxkbcommon[X?]
This one doesn't require it.

2024-11-11 17:11 UTC, kchibisov commented on x11-terms/alacritty/alacritty-0.13.2-r1.ebuild
> +	x11-libs/libxkbcommon[X?]
Could you specify `wayland?` as well while at it?

2024-11-12 18:29 UTC, kchibisov approved these changes

2024-11-17 17:09 UTC, juippis approved these changes

2024-11-17 17:16 UTC, closed without merging