sci-libs/coinasl: fix LTO type mismatch error
gentoo/gentoo pull request #39303
Opened 2024-11-13 15:59 UTC by Tatsh

Closes: https://bugs.gentoo.org/943309

Signed-off-by: Andrew Udvare <audvare@gmail.com>

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

2024-11-13 16:08 UTC, eli-schwartz requested changes
Please report this upstream and confirm that upstream agrees with your patch! https://portal.ampl.com/~dmg/netlib/ampl/

2024-11-13 21:00 UTC, Tatsh commented
> Please report this upstream and confirm that upstream agrees with your patch! https://portal.ampl.com/~dmg/netlib/ampl/

We use a different tarball because their URL does not have a version. Their version already has these changes: https://portal.ampl.com/~dmg/netlib/ampl/solvers/fgh_read.c

2024-11-15 00:29 UTC, eli-schwartz commented
Oh hmm, good to know. In that case, why not ask coinasl if they can bump their autotools harness to the new version, citing this improvement?

2024-11-15 02:13 UTC, Tatsh commented
> Oh hmm, good to know. In that case, why not ask coinasl if they can bump their autotools harness to the new version, citing this improvement?

Filed here: https://github.com/coin-or-tools/ThirdParty-ASL/issues/8

2024-11-29 01:56 UTC, Tatsh commented
We can assume a new release will be made soon based on the comment from 2 days ago.

2024-11-30 15:03 UTC, Tatsh commented
We determined the `dtoa.patch` patch is not necessary for building or LTO.

I have requested upstream make a new tarball of solvers with the [sed patch](https://github.com/gentoo/gentoo/commit/b2f20603f241eee5adee5f6864b9d1222e1801d9#diff-52dc3af2c495a6e4a31c862f69822cb7b6ff4072b8e9b19ea8fc7ac965583ca2R33) applied to fix the last LTO issue.

2025-01-03 16:09 UTC, juippis approved these changes
Test-built this with `-flto` successfully.

2025-01-05 15:51 UTC, Tatsh commented
The file that was causing the issue [was deleted](https://github.com/ampl/asl/commit/97e10747f47fea0db03c55c9d6b8294f0b3393bf). This patch now fixes the LTO issue by bumping the version of ASL solvers. Unfortunately no new release has been made since the change so a SHA is referenced instead.

2025-01-15 06:32 UTC, eli-schwartz commented
> Unfortunately no new release has been made since the change so a SHA is referenced instead.

From https://github.com/coin-or-tools/ThirdParty-ASL/issues/8#issuecomment-2509731745 upstream said you should wait until a new asl snapshot was out, and then ask coin-or to to make a new tarball based on that. But instead you simply closed the issue and didn't communicate further with coin-or. What's going on?

2025-02-05 05:37 UTC, Tatsh commented
> > Unfortunately no new release has been made since the change so a SHA is referenced instead.
> 
> From [coin-or-tools/ThirdParty-ASL#8 (comment)](https://github.com/coin-or-tools/ThirdParty-ASL/issues/8#issuecomment-2509731745) upstream said you should wait until a new asl snapshot was out, and then ask coin-or to to make a new tarball based on that. But instead you simply closed the issue and didn't communicate further with coin-or. What's going on?

I was waiting for a new release but I thought in the meantime we could just use a SHA.

ASL 1.0.1 was released and works for both 2.0.1 and the new 2.1.0 release of coinasl. The older version still needs the getrusage patch (a check which is now removed in 2.1.0). Both ebuilds now use ASL 1.0.1 and not a SHA.

2025-04-02 22:26 UTC, Tatsh commented
No longer relevant. ASL deleted the file.

2025-04-02 22:26 UTC, closed without merging