dev-util/imediff2: pkgmove to dev-util/imediff & bump 3.3.1
gentoo/gentoo pull request #39317
Opened 2024-11-14 15:46 UTC by PPN-SD

Program name is imediff without 2, since it supports diff for not only 2 files but also 3 files.

**pkgmove imediff-1.1.2.1 :**
Set SLOT="0/1" for stable version
PYTHON_COMPAT updated to python3_13

**new imediff-3.3.1 :**
SLOT="0/3"
use setuptools
add test with unittest

---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

2024-12-05 15:31 UTC, PPN-SD commented
cc @Flowdalic

2025-01-10 09:59 UTC, PPN-SD commented
@chewi As you're the last committer, may I ask you a review ?

2025-01-10 10:20 UTC, chewi requested changes
Other than the sub-slot, looks good at a glance. I'll play with it later.

2025-01-10 10:20 UTC, chewi commented on dev-util/imediff/imediff-1.1.2.1.ebuild
> +SLOT="0/1"
Sub-slots only make sense for libraries. Keep these in plain slot 0.

2025-01-10 10:25 UTC, PPN-SD commented
> Other than the sub-slot, looks good at a glance. I'll play with it later.

Thanks. Done.

2025-01-16 23:26 UTC, chewi approved these changes
The new version is nice, but I don't like how it writes imediff.log. I've commented about that in an existing issue.

2025-01-16 23:26 UTC, chewi commented on dev-util/imediff/imediff-3.3.1.ebuild
> +KEYWORDS="~amd64 ~arm ~arm64 ~x86"
Being a new major version, it's best to reset the keywords, so I'll do that now. I've tested on amd64, so I'll keep that.

2025-01-16 23:27 UTC, closed without merging

2025-01-17 04:33 UTC, PPN-SD commented on dev-util/imediff/imediff-3.3.1.ebuild
> +KEYWORDS="~amd64 ~arm ~arm64 ~x86"
Ok. Thanks !