sys-devel/dwz: fix hardcoded readelf and <error.h>
gentoo/gentoo pull request #39409
Opened 2024-11-22 06:58 UTC by lanodan

Closes: https://bugs.gentoo.org/829239
Closes: https://bugs.gentoo.org/902197

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

2024-11-22 17:24 UTC, mgorny commented on dev-util/debugedit/files/debugedit-5.1-musl-error.h-fix.patch
> +# musl doesn't provide error.h as a result debugedit is failing to build on
Was this submitted upstream?

2024-11-22 19:11 UTC, lanodan commented
>@mgorny commented on this pull request.
>> @@ -0,0 +1,54 @@
>+# musl doesn't provide error.h as a result debugedit is failing to build on
>
>Was this submitted upstream?

Doesn't seems to have been, at least https://inbox.sourceware.org/debugedit/?q=musl doesn't returns it and it's been 2 years since.

So I sent it: ***@***.***/T/#u

2024-11-30 12:24 UTC, mgorny requested changes
I see upstream raises concerns regarding the patch today, so let's wait till it's all settled.

2024-11-30 12:54 UTC, thesamesam commented on sys-libs/error-standalone/error-standalone-1.0.ebuild
> +EAPI=7
8 for new ebuilds, please.

2024-11-30 12:55 UTC, thesamesam commented on sys-libs/error-standalone/error-standalone-1.0.ebuild
> +SRC_URI="https://hacktivis.me/releases/error-standalone/${P}.tar.gz"
With regard to error-standalone itself: AFAIK, there's implementations which require a library. You've thankfully killed that requirement. But your version doesn't install a library at all which breaks compatibility unnecessarily. Add a .pc file and install an empty library?

2024-11-30 13:09 UTC, thesamesam commented on sys-libs/error-standalone/error-standalone-1.0.ebuild
> +SRC_URI="https://hacktivis.me/releases/error-standalone/${P}.tar.gz"
Also, the `error-standalone` commit (adding it) should have some detail on the background in the commit message.

2024-11-30 13:20 UTC, lanodan commented
> @thesamesam commented on this pull request.
>With regard to error-standalone itself: AFAIK, there's implementations which require a library. You've thankfully killed that requirement. But your version doesn't install a library at all which breaks compatibility unnecessarily. Add a .pc file and install an empty library?

Do you have an example of such library (which I guess is what the .pc is for)? At least I couldn't find one in Gentoo, while Alpine and Void Linux takes a similar (but somewhat incomplete) header-only approach.

2024-11-30 13:22 UTC, thesamesam commented
I was just double-checking and you're right. I'm sorry for the confusion! I can't find any such examples.

2024-11-30 14:17 UTC, mgorny approved these changes
LGTM, thanks!

2024-12-01 11:26 UTC, closed without merging