net-libs/mbedtls: slotting version 3
gentoo/gentoo pull request #39536
Opened 2024-11-30 23:00 UTC by winterheart

MbedTLS breaks API compatibility between major versions, and some packages are unable or not willing to migrate from slowly deprecating mbedtls-2 branches, so we are forced to keep them both for a while.

Bug: https://bugs.gentoo.org/805011

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

2024-12-01 06:15 UTC, thesamesam requested changes
Thank you for doing this, it's been a mess for quite a long time. It is appreciated!

In the commit message, please mention why it's safe for us to do this:
1) link to the upstream comment indicating they're not against it;
2) explain in the commit message why reverse dependencies should be mostly okay with this (they search via CMake config files, right?)

2024-12-01 06:15 UTC, thesamesam commented on net-libs/mbedtls/files/mbedtls-3.6.2-add-version-suffix-for-all-installable-targets.patch
> +From 9ebd03bfd9f3ae7f431f868a2246c4a1d71f3f07 Mon Sep 17 00:00:00 2001
Please (always) include a link at the top of patches to any relevant upstream PRs/bugs or Gentoo bugs.

2024-12-01 06:15 UTC, thesamesam commented on www-servers/lighttpd/lighttpd-1.4.75.ebuild
> +	mbedtls? ( net-libs/mbedtls:0= )
These changes will need a revbump (`git mv` is fine for this, no keywords change as well).

2024-12-01 19:00 UTC, winterheart commented
@thesamesam I've reworked most patches based on test building with some packages. Thankfully for cmake config framework, most of packages can passed to MbedTLS 3 if they supports it with minimal patching like replacing `find_package(MbedTLS REQUIRED)` with `find_package(MbedTLS 3 REQUIRED)` in CMakeLists.txt and `"DEPEND=net-libs/mbedtls:3"`.

2024-12-01 22:59 UTC, thesamesam commented on net-libs/mbedtls/files/mbedtls-3.6.2-add-version-suffix-for-all-installable-targets.patch
> +From 9ebd03bfd9f3ae7f431f868a2246c4a1d71f3f07 Mon Sep 17 00:00:00 2001
This doesn't seem done?

2024-12-02 21:22 UTC, thesamesam commented
Thanks. Please see https://github.com/gentoo/gentoo/pull/39536#discussion_r1865045151 then it should be good to go.

2024-12-21 03:05 UTC, thesamesam commented
ping

2024-12-22 09:42 UTC, winterheart commented
Hi, I'm on vacation now, will return on it in new year.

2024-12-22 09:43 UTC, thesamesam commented
ack. Enjoy!

2025-01-05 17:04 UTC, winterheart commented on net-libs/mbedtls/files/mbedtls-3.6.2-add-version-suffix-for-all-installable-targets.patch
> +From 9ebd03bfd9f3ae7f431f868a2246c4a1d71f3f07 Mon Sep 17 00:00:00 2001
Added links to updated PR.

2025-01-05 20:33 UTC, closed without merging