sys-auth/sssd: Multilib compile and test fixes
gentoo/gentoo pull request #39644
Opened 2024-12-09 06:38 UTC by salahcoronya

mutlilib 32-bit buildn't won't work if we try to compile for both abis. Python isn't multilib, so just build the bindings for native
abi. 

Fir 2.10.0 libcap needs to be ${MULTILIB_USEDEP} too. The sed filter was wrong and didn't disable the test that required valgrind. No revbump on 2.10.0 because it wouldn't have been able to compile on 32-bit multilib anyway. 

---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

2024-12-09 15:33 UTC, Dessa requested changes
the commit for 2.10.0 is incomplete, it doesn't include the python bit

2024-12-09 15:58 UTC, salahcoronya commented
Thanks, I added the missing python bits

2024-12-09 17:46 UTC, Dessa approved these changes

2024-12-10 05:45 UTC, closed without merging

2024-12-10 05:49 UTC, thesamesam commented
Pushed with tweaked commit messages to append the version in the summary, as otherwise it looked a bit confusing to have 2 commits with the same summary that did slightly different things. Thanks!