app-admin/passook: move back
gentoo/gentoo pull request #39693
Opened 2024-12-12 08:59 UTC by clan

revert commit ebe886820c4c81769bea9cd1e45709d20ac582ac

updated ebuild to EAPI 4 -> 8 & metadata.xml

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

2024-12-12 09:06 UTC, thesamesam requested changes

2024-12-12 09:06 UTC, thesamesam commented on app-admin/passook/passook-20121001.ebuild
> +KEYWORDS="amd64 hppa ppc ppc64 x86 ~amd64-linux ~x86-linux ~ppc-macos"
Please do `ekeyword ~all`, as it's essentially a "new" package.

2024-12-12 09:06 UTC, thesamesam commented on app-admin/passook/passook-20121001.ebuild
> +SRC_URI="mirror://gentoo/${P}.tar.gz"
This is surely a dead `SRC_URI` by now as it will have been purged from our mirrors long ago?

2024-12-12 09:06 UTC, thesamesam commented on app-admin/passook/passook-20121001.ebuild
> +	eapply "${FILESDIR}"/passook.patch
Please use `PATCHES` as an array instead in global scope. No need for eapply or `cd`.

2024-12-12 09:06 UTC, thesamesam commented on app-admin/passook/passook-20121001.ebuild
> +# Copyright 1999-2017 Gentoo Foundation
This is wrong.

2024-12-12 09:06 UTC, thesamesam commented on app-admin/passook/files/passook.patch
> +--- a/passook
The patch filename should be something like `passook-2012001-prefix.patch`.

2024-12-12 09:06 UTC, thesamesam commented on app-admin/passook/passook-20121001.ebuild
> +SRC_URI="mirror://gentoo/${P}.tar.gz"
I would fetch a commit-based snapshot from github.

2024-12-12 09:07 UTC, juippis commented
Do we really want to return this? No updates in 12+ years and it's essentially a single perl script that can just be downloaded locally?

2024-12-12 09:41 UTC, thesamesam commented
We'd discussed it beforehand in return for some other bug work. It's also low-maintenance, of course :)

2024-12-12 09:44 UTC, clan commented
> Do we really want to return this? No updates in 12+ years and it's essentially a single perl script that can just be downloaded locally?

It's a useful and very simple tool.
For me, I'd like to keep this script under manged by PMS so I can run it whenever needed rather than download or copy from somewhere else.

2024-12-12 10:38 UTC, thesamesam commented
> For me, I'd like to keep this script under manged by PMS so I can run it whenever needed rather than download or copy from somewhere else.

BTW, of course, you could put it in a local repo or in guru or your own overlay (which could be added to the official list). But I'm also fine with us restoring it given it was in-tree before and it's tiny and easy to maintain.

2024-12-13 09:34 UTC, thesamesam commented
Merged with a `Bug:` tag added to https://bugs.gentoo.org/724210.

2024-12-13 09:35 UTC, closed without merging