Qt5 revdeps cleanup, porting, call to action
gentoo/gentoo pull request #39913
Opened 2024-12-30 21:22 UTC by a17r

Maintainers, please

- port your packages to Qt6 and drop Qt5 aggressively
- ACK changes to your packages in this PR

2024-12-30 21:39 UTC, chewi approved these changes
Okay for media-libs/libv4l.

Regarding app-emulation/fs-uae-launcher, which isn't in this list, I did look at the upstream pull request to migrate to Qt6, but it was against the master branch, which has diverged heavily from the last stable release, and all development has ceased. I was able to hack together my own patch at the weekend though, just need to finalise it.

2024-12-30 21:44 UTC, eli-schwartz requested changes
Commit messages are hard to read. Instead of "mechanically drop the word qt6 from the variable IUSE", consider "drop support for Qt5, require Qt6" (cmake, qtractor...) or in some cases "drop support for Qt5 backend" (lazarus). This gives a much clearer idea to someone reading the commit logs, what the practical effects of the change are...

2024-12-30 21:50 UTC, voyageur approved these changes
LGTM for net-misc/owncloud-client

2024-12-30 21:50 UTC, voyageur commented on net-misc/owncloud-client/owncloud-client-5.2.1.13040-r1.ebuild
This version is already qt6, so could be kept (latest version 5.3.1.14018 was only added a week ago), but we can go with larger cleanup  - 5.2 to 5.3 is mostly fixes and low-use package

2024-12-30 23:06 UTC, Chiitoo approved these changes

2024-12-31 07:00 UTC, Nowa-Ammerlaan approved these changes

2024-12-31 08:01 UTC, openhs approved these changes

2024-12-31 08:02 UTC, openhs approved these changes

2024-12-31 09:00 UTC, a17r commented
> Commit messages are hard to read. Instead of "mechanically drop the word qt6 from the variable IUSE" (what does that mean, does the package no longer support _Qt6_?)

Noted. However, commit messages are directed towards maintainers, not the casual reader. Knowledge about the mechanical change is at least as important as the 'spoken' change of feature set, and maintainers would know very well that "drop IUSE qt6" does not imply "drop Qt6".

2024-12-31 11:07 UTC, kripton approved these changes
ACK for app-misc/qlcplus
I will be working on migrating qlcplus-4.* ebuilds to Qt6 :+1:

2024-12-31 11:25 UTC, a17r commented
> ACK for app-misc/qlcplus I will be working on migrating qlcplus-4.* ebuilds to Qt6 👍
I'd say that is an impossible task, because of QtScript dependency. Long-term, only qlcplus-5 which has ported away from that is a Qt6 porting candidate (I see there are upstream issues/MRs already about that).

2024-12-31 11:51 UTC, kripton commented
> I'd say that is an impossible task, because of QtScript dependency. Long-term, only qlcplus-5 which has ported away from that is a Qt6 porting candidate (I see there are upstream issues/MRs already about that).

Yeah, I am currently checking with upstream. QLC+ 4.13.1 builds fine with Qt 6.8.1 but tests fail and there are bug reports in QLC+'s forum. QLC+ 5 is also not better because of the Qt3d module being used there. So in general, not a nice situation.
Some Qt6-related bugs have been fixed upstream and I will ask for a new release to be tagged that works better with Qt6. However, in the meantime I will migrate the ebuild from qmake to cmake since the upstream support seems to be stable by now. At least their GitHub Actions use cmake.

2024-12-31 12:10 UTC, rndxelement commented
ACK for media-gfx/converseen.
PR for bump with QT6 support is linked above.

2024-12-31 14:32 UTC, thesamesam commented
> Noted. However, commit messages are directed towards maintainers, not the casual reader. Knowledge about the mechanical change is at least as important as the 'spoken' change of feature set, and maintainers would know very well that "drop IUSE qt6" does not imply "drop Qt6".

This kind of change is often more user-visible as they may wonder why it was removed, but also, I think it does matter in terms of whether or not we're removing e.g. the only GUI because it's a deprecated toolkit, or just changing the default choice.

It's also important to give a good example for future, as even if _you're_ not making that kind of change now (all your changes here IIRC are for just where 2 toolkits are supported, changing to just qt6, etc), others may look at it in future when making the other type of change and not realise the distinction in why it was okay to perhaps be a bit more vague.

(It also matters especially for the silly case of all that 3D stuff where we have weird USE=qt6 etc where we're not even sure what reverse dependencies should even do about it when it gets removed)

2024-12-31 21:07 UTC, Nowa-Ammerlaan approved these changes

2024-12-31 22:13 UTC, chewi approved these changes
Fine for games-emulation/fceux.

2025-01-01 06:48 UTC, band-a-prend commented
ACK for dev-vcs/tortoisehg.
With the offered changes the tortoisehg is successfully built and launched.
@a17r  thank you for porting!

P.S.  
The current upstream version is `6.9rc0` of 27  Nov 2024 (the previous release `6.6.3` was  14 Feb 2024) so I hope the new release will be soon.

2025-01-01 10:12 UTC, thesamesam commented
(Thank you for the phrasing tweaks :heart:)

2025-01-01 12:48 UTC, a17r commented
@benkohler @ZeroChaos- Please check any other ebuilds of yours that you ported to Qt6 for missing USEdeps on `dev-qt/qtbase` and `dev-qt/qttools`.

2025-01-01 12:55 UTC, thesamesam approved these changes
ok for wireshark (thanks)

2025-01-01 13:36 UTC, chewi requested changes

2025-01-01 13:36 UTC, chewi commented on net-misc/moonlight/moonlight-9999.ebuild
> +BDEPEND="virtual/pkgconfig"
I guess this was wrong before, but you probably need `dev-qt/qtbase:6` in `BDEPEND` for moc.

2025-01-01 15:23 UTC, ulm commented
I've cherry picked [8d6777e](https://github.com/gentoo/gentoo/pull/39913/commits/8d6777eb1bb42f445cc2b1506aa8b74fb0637aa0), and applied with `econf` arguments reordered alphabetically.
So this commit can be dropped from the PR.

2025-01-01 18:53 UTC, a17r commented
@chewi you don't seem to be using 9999 for spinning new lgogdownloader releases ;)

2025-01-01 20:07 UTC, kripton commented
> > I'd say that is an impossible task, because of QtScript dependency. Long-term, only qlcplus-5 which has ported away from that is a Qt6 porting candidate (I see there are upstream issues/MRs already about that).
> 
> Yeah, I am currently checking with upstream. QLC+ 4.13.1 builds fine with Qt 6.8.1 but tests fail and there are bug reports in QLC+'s forum. QLC+ 5 is also not better because of the Qt3d module being used there. So in general, not a nice situation. Some Qt6-related bugs have been fixed upstream and I will ask for a new release to be tagged that works better with Qt6. However, in the meantime I will migrate the ebuild from qmake to cmake since the upstream support seems to be stable by now. At least their GitHub Actions use cmake.

Don't want to hijack this PR but it doesn't look that bad for app-misc/qlcplus: Upstream has taken care of the QtScript deprecation (ref: https://www.qlcplus.org/forum/viewtopic.php?p=75974#p75974) and a new releases with better Qt6 compatibility are "imminent". I adapted the ebuild to work with cmake but it would also take a new release since 4.13.1 is also buggy concerning cmake.
@a17r : How urgent is this? Can we wait for a new upstream release and switch to cmake & Qt6 then or shall I prepare an ebuild for 4.13.1 with all Qt6-related patches in ${FILESDIR} ?

2025-01-01 20:15 UTC, a17r commented
> Can we wait for a new upstream release and switch to cmake & Qt6 then

Definitely. This is a *someone's gotta start somewhere* PR, not the last call.

2025-01-01 21:24 UTC, chewi commented
> @chewi you don't seem to be using 9999 for spinning new lgogdownloader releases ;)

Yeah, I never got around to adapting it. It doesn't change much. Well, until now, that is. :stuck_out_tongue:

2025-01-01 21:35 UTC, chewi commented on games-util/lgogdownloader/lgogdownloader-9999.ebuild
I think this needs qtbase in `BDEPEND` for moc too. I can add it later if you want though.

2025-01-01 21:53 UTC, a17r commented on games-util/lgogdownloader/lgogdownloader-9999.ebuild
thanks, I'll let you deal with that :)

2025-01-02 20:10 UTC, benkohler commented
Yes looks good for cmst, thanks

2025-01-02 20:35 UTC, Nowa-Ammerlaan approved these changes
ACK for `dev-libs/quazip`

2025-01-02 20:36 UTC, thesamesam commented
gpgme ok

2025-01-02 20:38 UTC, thesamesam commented
pls also stable latest gpgme or I will when at pc

2025-01-03 10:12 UTC, graaff commented
xca removal ok.

2025-01-03 13:51 UTC, a17r commented
> xca removal ok.

@graaff thanks. https://bugs.gentoo.org/947186 also okay to start?

2025-01-03 15:42 UTC, ConiKost commented
Do we really want as fast as we can to get ride of qt5? I am not really happy to mask ts3 as for now. It's a binary package and while there will be ts5 in future, it's currently in beta and can be only used if you have beta access (I do have). Ebuild for ts5 is prepared for unmasking.. but given the access restriction, normal teamspeak users will be cut off.

2025-01-03 18:09 UTC, a17r commented
> Do we really want as fast as we can to get ride of qt5? I am not really happy to mask ts3 as for now. It's a binary package and while there will be ts5 in future, it's currently in beta and can be only used if you have beta access (I do have). Ebuild for ts5 is prepared for unmasking.. but given the access restriction, normal teamspeak users will be cut off.
> 
> Update: Seems, that at least anyone can now apply for beta and should get granted access to ts5 beta.

Ultimately your call, but depending on dev-qt/qtwebengine:5 and now pinning down users onto dev-libs/quazip:0/1 is really bad (the latter introducing hard blocker for people trying to build packages depending on quazip[qt6] unless someone starts working on properly slotting that.

2025-01-05 22:33 UTC, xgqt commented
ACK for melonds, old versions can be removed

2025-01-05 22:36 UTC, thesamesam commented
ok for seer

2025-01-12 22:26 UTC, Chiitoo commented on dev-util/lxqt-build-tools/lxqt-build-tools-0.13.0.ebuild
Think `x11-misc/obconf-qt-0.16.4` will need to go with this.

Thought I'd added a blocker for `>=dev-util/lxqt-build-tools-2`, but it does not seem like it actually happened...

2025-01-12 23:54 UTC, dlan17 commented
Ok for dropping <dev-util/kernelshark-2.3

2025-01-13 15:33 UTC, benkohler commented
Looks good on media-gfx/pencil.  Sorry I missed that bump, it doesn't show up on my p.g.o maintainer page, likely because of other distros calling it pencil2d.

2025-01-14 10:02 UTC, negril approved these changes
openscad affirm
vtk affirm

2025-01-21 06:03 UTC, graaff commented
xca and nagstamon removals are fine with me.

2025-01-22 17:12 UTC, ZeroChaos- approved these changes

2025-01-23 16:49 UTC, arthurzam approved these changes

2025-01-24 00:18 UTC, DarthGandalf approved these changes

2025-01-24 06:18 UTC, tamiko approved these changes

2025-01-28 18:43 UTC, closed without merging