media-gfx/converseen: add 0.12.2.4 with QT6 support (and dropped QT5 support)
gentoo/gentoo pull request #39919
Opened 2024-12-31 12:07 UTC by rndxelement

- Add ebuild for latest upstream release with support for QT6 and dropped support for QT5
- [Changelog](https://converseen.fasterland.net/changelog/) doesn't state significant changes to the build process
- Tested via pkg-testing-tool and `--feature-scope once`
- Runtime tested with `IUSE=-graphicsmagic`

Ref: #39913 

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

2024-12-31 18:22 UTC, a17r requested changes

2024-12-31 18:22 UTC, a17r commented on media-gfx/converseen/converseen-0.12.2.4.ebuild
> +MYCMAKEARGS="-DUSE_QT6=yes"
That's not how we do it - this overrides a user-defineable variable. Set it in `local mycmakeargs=( ... )` inside `src_configure()` phase.

2024-12-31 18:22 UTC, a17r commented on media-gfx/converseen/files/converseen-0.12.2.4-appdata-path.patch
> ++++ b/converseen.pro
```suggestion
diff --git a/converseen.pro b/converseen.pro
index c85620d..da49a71 100755
--- a/converseen.pro
+++ b/converseen.pro
```

2024-12-31 18:22 UTC, a17r commented on media-gfx/converseen/converseen-0.12.2.4.ebuild
> +"
missing slot def.
```suggestion
BDEPEND="dev-qt/qttools:6[linguist]"
```

2024-12-31 18:22 UTC, a17r commented on media-gfx/converseen/converseen-0.12.2.4.ebuild
> +S="${WORKDIR}/${P^}"
```suggestion
SRC_URI="https://github.com/Faster3ck/Converseen/archive/v${PV}.tar.gz -> ${P}.tar.gz"
S="${WORKDIR}/${P^}"
```

2025-01-01 16:50 UTC, a17r requested changes
```
 * Applying converseen-0.12.2.4-appdata-path.patch ...
patching file converseen.pro
Hunk #1 FAILED at 171 (different line endings).
1 out of 1 hunk FAILED -- saving rejects to file converseen.pro.rej
```

2025-01-01 17:01 UTC, rndxelement commented
> ```
>  * Applying converseen-0.12.2.4-appdata-path.patch ...
> patching file converseen.pro
> Hunk #1 FAILED at 171 (different line endings).
> 1 out of 1 hunk FAILED -- saving rejects to file converseen.pro.rej
> ```

Thanks for reviewing!
I'm currently a bit confused. It builds on my system with the patch file having the `^M` line endings. After converting the patch via dos2unix, it does not build anymore.

2025-01-01 17:08 UTC, rndxelement commented
> > ```
> >  * Applying converseen-0.12.2.4-appdata-path.patch ...
> > patching file converseen.pro
> > Hunk #1 FAILED at 171 (different line endings).
> > 1 out of 1 hunk FAILED -- saving rejects to file converseen.pro.rej
> > ```
> 
> Thanks for reviewing! I'm currently a bit confused. It builds on my system with the patch file having the `^M` line endings. After converting the patch via dos2unix, it does not build anymore.

It doesn't seem to be due to git normalizing line endings, because when downloading the file directly from Github it has the `^M` endings.

2025-01-01 18:29 UTC, a17r commented
Your editor was probably changing line endings on modifying the patch to my suggestion.

2025-01-01 18:34 UTC, a17r approved these changes
I fixed it by manually recreating the patch.

2025-01-01 18:34 UTC, closed without merging

2025-01-01 21:06 UTC, rndxelement commented
> I fixed it by manually recreating the patch.

Thanks a lot!